extends RefCounted
class_name SaveOwnerCaptureFailureV1

const SCHEMA_VERSION := 1
const FAILURE_CLASSES := [
	"OWNER_NODE_MISSING",
	"OWNER_METHOD_MISSING",
	"OWNER_CAPTURE_EXCEPTION",
	"OWNER_CAPTURE_WRONG_TYPE",
	"OWNER_CAPTURE_EMPTY",
	"OWNER_CAPTURE_NOT_PURE_DATA",
	"OWNER_CAPTURE_HEADER_INVALID",
	"OWNER_CAPTURE_VERSION_INVALID",
	"OWNER_CAPTURE_RULESET_INVALID",
	"OWNER_CAPTURE_MUTATED_RUNTIME",
	"REGISTRY_INTERNAL_ERROR",
]
const REASON_CODES := [
	"allocator_cursor_invalid",
	"allocator_cursor_missing_requires_backup",
	"allocator_cursor_regressed",
	"active_boundary_invalid",
	"active_duration_world_us_invalid",
	"active_ends_at_world_us_invalid",
	"active_monster_wagers_invalid",
	"asset_recovery_journal_binding_invalid",
	"asset_recovery_journal_order_invalid",
	"asset_recovery_journal_record_invalid",
	"asset_recovery_journal_size_invalid",
	"asset_save_field_type_invalid",
	"asset_save_header_invalid",
	"asset_save_player_rows_mismatch",
	"asset_save_reservation_invalid",
	"asset_save_revision_invalid",
	"asset_save_rows_invalid",
	"asset_save_shape_invalid",
	"asset_save_terminal_receipt_invalid",
	"asset_save_time_invalid",
	"active_starts_at_world_us_invalid",
	"ai_business_market_pressure_recovery_required",
	"ai_business_market_pressure_rollback_window_open",
	"ai_player_save_invalid",
	"ai_save_header_invalid",
	"ai_save_policy_attestation_invalid",
	"ai_save_policy_mismatch",
	"ai_save_request_sequence_invalid",
	"ai_save_shape_invalid",
	"ai_save_timer_invalid",
	"bankruptcy_save_header_invalid",
	"bankruptcy_save_invalid",
	"bankruptcy_save_shape_invalid",
	"bankruptcy_journal_record_fields_invalid",
	"bankruptcy_journal_record_invalid",
	"bankruptcy_journal_record_not_allowlisted",
	"bankruptcy_journal_request_fingerprint_invalid",
	"bankruptcy_journal_source_fingerprint_invalid",
	"bankruptcy_last_survivor_reference_invalid",
	"bankruptcy_lifecycle_token_missing",
	"bankruptcy_public_receipt_invalid",
	"bankruptcy_public_receipt_not_allowlisted",
	"bankruptcy_rent_journal_invalid",
	"bankruptcy_rent_receipt_id_invalid",
	"bankruptcy_save_authority_duplicate_forbidden",
	"bankruptcy_save_lineage_bound_invalid",
	"bankruptcy_save_not_allowlisted",
	"bankruptcy_save_not_canonical",
	"bankruptcy_save_retired_lineage_collision",
	"bankruptcy_transaction_id_invalid",
	"capture_rejected",
	"capture_result_invalid",
	"card_annotation_preflight_failed",
	"card_annotation_checkpoint_schema_invalid",
	"card_annotation_history_id_invalid",
	"card_annotation_indices_invalid",
	"card_annotation_indices_not_canonical",
	"card_annotation_indices_overlap",
	"card_annotation_role_usage_invalid",
	"card_annotation_row_invalid",
	"card_annotation_subscription_limit_invalid",
	"card_annotation_tags_invalid",
	"card_annotation_viewer_invalid",
	"card_annotation_viewer_rows_invalid",
	"card_flow_restore_contract_missing",
	"card_flow_restore_preflight_failed",
	"card_inventory_child_contract_missing",
	"card_inventory_v2_invalid",
	"card_inventory_v3_invalid",
	"card_inventory_world_authority_duplicate_forbidden",
	"card_inventory_save_owner_dependency_missing",
	"commodity_card_inventory_checkpoint_blocked",
	"commodity_card_inventory_checkpoint_capture_failed",
	"product_market_checkpoint_blocked",
	"product_market_checkpoint_capture_failed",
	"district_purchase_checkpoint_blocked",
	"district_purchase_checkpoint_capture_failed",
	"card_inventory_runtime_checkpoint_invalid",
	"card_flow_restore_belt_invalid",
	"card_flow_restore_belt_item_id_invalid",
	"card_flow_restore_belt_item_invalid",
	"card_flow_restore_children_invalid",
	"card_flow_restore_journal_invalid",
	"card_flow_restore_market_acl_invalid",
	"card_flow_restore_market_invalid",
	"card_flow_restore_market_listing_invalid",
	"card_flow_restore_state_invalid",
	"card_flow_restore_transaction_id_invalid",
	"card_flow_restore_visibility_acl_invalid",
	"card_resolution_queue_entry_binding_dangling",
	"card_resolution_queue_entry_field_missing",
	"card_resolution_queue_entry_not_codec_data",
	"card_resolution_queue_entry_not_dictionary",
	"card_resolution_queue_entry_type_invalid",
	"card_resolution_queue_entry_value_invalid",
	"card_resolution_queue_facility_binding_invalid",
	"card_resolution_queue_facility_binding_mismatch",
	"card_resolution_queue_reservation_dangling",
	"card_resolution_queue_resolution_duplicate",
	"card_resolution_queue_save_fields_invalid",
	"card_resolution_queue_save_header_invalid",
	"card_resolution_queue_save_invalid",
	"card_resolution_queue_save_not_codec_data",
	"card_resolution_queue_save_shape_invalid",
	"card_resolution_queue_sequence_dangling",
	"card_resolution_queue_target_dangling",
	"card_resolution_queue_window_dangling",
	"commodity_belt_visibility_fingerprint_invalid",
	"commodity_belt_visibility_item_ids_invalid",
	"commodity_belt_visibility_save_invalid",
	"commodity_card_inventory_save_children_invalid",
	"commodity_card_inventory_save_invalid",
	"commodity_flow_save_preflight_mutated_live_owner",
	"commodity_flow_terms_mismatch",
	"commodity_flow_save_preflight_rejected",
	"commodity_postcommit_flow_cursor_mismatch",
	"commodity_postcommit_batch_binding_invalid",
	"commodity_postcommit_batch_not_pure_data",
	"commodity_postcommit_legacy_bootstrap_reason_invalid",
	"commodity_postcommit_pending_cursor_invalid",
	"commodity_postcommit_pending_flow_cursor_mismatch",
	"commodity_postcommit_pending_identity_invalid",
	"commodity_postcommit_receipt_identity_invalid",
	"commodity_postcommit_receipt_invalid",
	"commodity_postcommit_receipt_order_invalid",
	"commodity_postcommit_save_cursor_invalid",
	"commodity_postcommit_save_header_invalid",
	"commodity_postcommit_save_record_invalid",
	"commodity_postcommit_terminal_cursor_invalid",
	"commodity_postcommit_terminal_order_incomplete",
	"commodity_postcommit_terminal_order_invalid",
	"cross_section_dependency_rejected",
	"controller_not_configured",
	"created_at_world_us_invalid",
	"detailed_capture_unavailable",
	"execution_save_invalid",
	"execution_save_schema_unsupported",
	"active_missing",
	"completed_intent_invalid",
	"completed_intents_invalid",
	"continuation_intent_missing_history",
	"dispatch_intent_missing_target_validation",
	"duplicate_execution_record",
	"effect_not_resolved",
	"execution_lineage_invalid",
	"execution_record_not_data",
	"execution_records_not_array",
	"execution_records_not_strictly_sorted",
	"execution_sequence_invalid",
	"execution_sequence_precedes_record",
	"execution_transaction_identity_invalid",
	"execution_transaction_invalid",
	"execution_transaction_not_data",
	"facility_execution_collision",
	"facility_execution_not_pending",
	"finalized_transaction_state_invalid",
	"history_intent_missing_context_restore",
	"inflight_next_intent_invalid",
	"inflight_transaction_ids_mismatch",
	"inflight_transaction_invalid",
	"inflight_transaction_missing",
	"inflight_transaction_not_resumable",
	"inflight_transaction_status_invalid",
	"inflight_transactions_invalid",
	"intent_receipt_mismatch",
	"invalid_advance_request",
	"invalid_finalize_request",
	"invalid_request",
	"invalid_resolution_id",
	"next_intent_missing_active_release",
	"next_intent_missing_counter_check",
	"next_intent_order_invalid",
	"pending_settlement_binding_invalid",
	"pending_settlement_binding_mismatch",
	"pending_settlement_missing",
	"pending_settlement_not_data",
	"pending_settlement_not_finalized",
	"pending_settlement_outcome_binding_invalid",
	"pending_settlements_invalid",
	"promotion_intent_missing_batch_finish",
	"requirement_invalid",
	"retryable_intent_invalid",
	"service_not_configured",
	"settlement_not_completed",
	"settlement_receipt_binding_mismatch",
	"target_invalid",
	"transition_checkpoint_invalid",
	"transition_checkpoint_owner_missing",
	"unsupported_intent",
	"event_field_type_invalid",
	"event_id_duplicate",
	"event_keys_invalid",
	"event_not_dictionary",
	"event_schema_version_invalid",
	"events_invalid",
	"facility_action_controller_preimage_invalid",
	"facility_action_controller_revision_changed",
	"facility_action_empty_preimage_invalid",
	"facility_action_facility_preimage_invalid",
	"facility_action_facility_state_changed",
	"facility_action_generation_preimage_invalid",
	"facility_action_intent_binding_invalid",
	"facility_action_lifecycle_key_mismatch",
	"facility_action_lifecycle_not_pure_data",
	"facility_action_lifecycle_shape_invalid",
	"facility_action_lifecycle_version_invalid",
	"facility_action_original_receipt_binding_invalid",
	"facility_action_original_receipt_invalid",
	"facility_action_owner_binding_fingerprint_invalid",
	"facility_action_owner_binding_invalid",
	"facility_action_pending_lifecycle_invalid",
	"facility_action_postimage_invalid",
	"facility_action_preimage_missing",
	"facility_action_receipt_binding_mismatch",
	"facility_action_receipt_kind_invalid",
	"facility_action_receipt_transaction_mismatch",
	"facility_action_region_preimage_invalid",
	"facility_action_region_state_changed",
	"facility_action_slot_generation_changed",
	"facility_action_slot_mapping_changed",
	"facility_action_slot_preimage_invalid",
	"facility_action_terminal_lifecycle_invalid",
	"facility_action_terminal_receipt_invalid",
	"facility_action_transaction_journal_mismatch",
	"facility_restore_actor_binding_mismatch",
	"facility_restore_actor_missing",
	"facility_restore_binding_invalid",
	"facility_restore_binding_schema_invalid",
	"facility_restore_dependency_section_missing",
	"facility_restore_escrow_binding_mismatch",
	"facility_restore_escrow_invalid",
	"facility_restore_escrow_missing",
	"facility_restore_escrow_receipt_binding_mismatch",
	"facility_restore_escrow_receipt_invalid",
	"facility_restore_escrow_slot_invalid",
	"facility_restore_escrow_state_mismatch",
	"facility_restore_execution_shape_invalid",
	"facility_restore_execution_stage_invalid",
	"facility_restore_facility_record_invalid",
	"facility_restore_free_reservation_invalid",
	"facility_restore_mana_invalid",
	"facility_restore_mana_shape_invalid",
	"facility_restore_orphan_escrow",
	"facility_restore_orphan_reservation",
	"facility_restore_player_roster_invalid",
	"facility_restore_post_effect_binding_mismatch",
	"facility_restore_post_effect_lifecycle_invalid",
	"facility_restore_post_effect_lifecycle_missing",
	"facility_restore_post_effect_postimage_mismatch",
	"facility_restore_post_effect_receipt_mismatch",
	"facility_restore_post_effect_terminal_mismatch",
	"facility_restore_queue_escrow_missing",
	"facility_restore_queue_mirror_mismatch",
	"facility_restore_queue_reservation_missing",
	"facility_restore_queue_shape_invalid",
	"facility_restore_reference_invalid",
	"facility_restore_reference_phase_collision",
	"facility_restore_reference_phase_invalid",
	"facility_restore_region_half_finalized",
	"facility_restore_region_invalid",
	"facility_restore_region_record_invalid",
	"facility_restore_region_shape_invalid",
	"facility_restore_reservation_binding_mismatch",
	"facility_restore_reservation_collision",
	"facility_restore_reservation_invalid",
	"facility_restore_reservation_missing",
	"facility_restore_reservation_overcommitted",
	"facility_restore_reservation_player_missing",
	"facility_restore_reservation_queue_mismatch",
	"facility_restore_resolution_collision",
	"facility_restore_runtime_instance_collision",
	"facility_restore_session_binding_mismatch",
	"facility_restore_session_identity_invalid",
	"facility_restore_session_invalid",
	"facility_restore_session_shape_invalid",
	"facility_restore_skill_mirror_mismatch",
	"facility_restore_stable_target_mismatch",
	"facility_restore_target_binding_mismatch",
	"facility_restore_target_region_missing",
	"facility_restore_terminal_reservation_mismatch",
	"facility_auxiliary_state_invalid",
	"facility_card_escrow_actor_player_index_invalid",
	"facility_card_escrow_card_kind_invalid",
	"facility_card_escrow_card_not_pure_data",
	"facility_card_escrow_card_record_mismatch",
	"facility_card_escrow_card_semantic_mismatch",
	"facility_card_escrow_catalog_card_invalid",
	"facility_card_escrow_catalog_card_missing",
	"facility_card_escrow_catalog_record_mismatch",
	"facility_card_escrow_checkpoint_unstable",
	"facility_card_escrow_collision",
	"facility_card_escrow_hand_slot_mismatch",
	"facility_card_escrow_instance_collision",
	"facility_card_escrow_owner_binding_invalid",
	"facility_card_escrow_player_missing",
	"facility_card_escrow_predecessor_invalid",
	"facility_card_escrow_receipt_invalid",
	"facility_card_escrow_record_invalid",
	"facility_card_escrow_request_invalid",
	"facility_card_escrow_source_record_fingerprint_mismatch",
	"facility_card_escrow_source_slot_index_invalid",
	"facility_card_escrow_source_slot_not_empty",
	"facility_card_escrow_state_invalid",
	"facility_card_escrow_validation_receipt_invalid",
	"facility_card_escrow_validator_unavailable",
	"facility_card_escrow_world_state_invalid",
	"facility_record_invalid",
	"facility_tombstone_invalid",
	"fade_boundary_invalid",
	"fade_duration_world_us_invalid",
	"fade_ends_at_world_us_invalid",
	"fixed_point_remainder_invalid",
	"market_backlog_state_invalid",
	"forecast_boundary_invalid",
	"forecast_duration_world_us_invalid",
	"forecast_starts_at_world_us_invalid",
	"fake_owner_state_invalid",
	"invalid_asset_save_payload",
	"invalid_payload",
	"history_array_invalid",
	"history_duplicate_resolution",
	"history_entry_invalid",
	"history_limit_exceeded",
	"history_limit_invalid",
	"history_lineage_array_invalid",
	"history_lineage_invalid",
	"history_lineage_mismatch",
	"history_lineage_not_canonical",
	"history_private_field_forbidden",
	"history_resolution_id_invalid",
	"history_revision_invalid",
	"history_schema_invalid",
	"history_state_not_data_only",
	"history_state_not_dictionary",
	"history_state_shape_invalid",
	"history_invalid",
	"installation_record_invalid",
	"installation_transaction_id_invalid",
	"installation_transaction_receipt_invalid",
	"legacy_backpressure_field_forbidden",
	"legacy_inflight_transaction_unrecoverable",
	"legacy_backpressure_migration_ambiguous",
	"legacy_backpressure_migration_source_invalid",
	"legacy_project_state_rejected",
	"lifecycle_end_recorded_invalid",
	"military_save_invalid",
	"military_bankruptcy_journal_too_large",
	"military_bankruptcy_record_invalid",
	"military_bankruptcy_transaction_invalid",
	"military_motion_binding_dangling",
	"military_next_uid_dangling",
	"military_save_fields_invalid",
	"military_save_header_invalid",
	"military_save_not_codec_data",
	"military_save_shape_invalid",
	"military_unit_field_missing",
	"military_unit_identity_invalid",
	"military_unit_mobility_invalid",
	"military_unit_nonfinite",
	"military_unit_not_codec_data",
	"military_unit_not_dictionary",
	"military_unit_stat_invalid",
	"military_unit_uid_duplicate",
	"monster_save_actor_invalid",
	"monster_save_actor_uid_invalid",
	"monster_save_battle_lifecycle_schema_invalid",
	"monster_save_invalid",
	"monster_save_next_auto_monster_uid_invalid",
	"monster_save_schema_attestation_invalid",
	"monster_save_shape_invalid",
	"monster_save_slot_invalid",
	"monster_battle_lifecycle_battle_limit_invalid",
	"monster_battle_lifecycle_battle_timer_started_early",
	"monster_battle_lifecycle_closed_decision_timer_invalid",
	"monster_battle_lifecycle_decision_flag_invalid",
	"monster_battle_lifecycle_decision_limit_invalid",
	"monster_battle_lifecycle_opening_attack_flag_invalid",
	"monster_battle_lifecycle_phase_flag_mismatch",
	"monster_battle_lifecycle_phase_invalid",
	"monster_battle_lifecycle_revision_invalid",
	"monster_battle_lifecycle_roster_binding_invalid",
	"monster_battle_lifecycle_roster_fingerprint_invalid",
	"monster_battle_lifecycle_roster_invalid",
	"monster_battle_lifecycle_schema_invalid",
	"monster_battle_lifecycle_side_invalid",
	"monster_battle_lifecycle_timer_invalid",
	"monster_save_active_monster_wagers_invalid",
	"monster_save_active_wager_binding_invalid",
	"monster_save_active_wager_invalid",
	"monster_save_active_wager_snapshot_invalid",
	"monster_save_applied_pending_collision",
	"monster_save_atomic_schema_mismatch",
	"monster_save_authority_duplicate_forbidden",
	"monster_save_auto_monsters_invalid",
	"monster_save_battle_competitors_invalid",
	"monster_save_battle_opening_attack_binding_invalid",
	"monster_save_battle_opening_attack_time_invalid",
	"monster_save_battle_pending_attack_invalid",
	"monster_save_battle_roster_overlap",
	"monster_save_monster_card_atomic_owner_revision_invalid",
	"monster_save_monster_card_atomic_presentation_journal_invalid",
	"monster_save_monster_card_atomic_reservations_invalid",
	"monster_save_monster_card_atomic_starter_state_invalid",
	"monster_save_monster_card_atomic_terminal_journal_invalid",
	"monster_save_monster_timer_invalid",
	"monster_save_monster_wager_sequence_invalid",
	"monster_save_monster_wager_settlement_revision_invalid",
	"monster_save_monster_wager_settlement_terminal_journal_invalid",
	"monster_save_next_special_monster_slot_invalid",
	"monster_save_not_canonical",
	"monster_save_opening_attack_binding_invalid",
	"monster_save_owner_revision_invalid",
	"monster_save_presentation_journal_invalid",
	"monster_save_public_card_bid_monster_wager_pool_invalid",
	"monster_save_reservation_binding_invalid",
	"monster_save_reservation_core_mismatch",
	"monster_save_reservation_fingerprint_invalid",
	"monster_save_reservation_invalid",
	"monster_save_resolved_monster_wager_history_invalid",
	"monster_save_same_family_duplicate",
	"monster_save_selected_auto_monster_slot_invalid",
	"monster_save_special_monster_timer_invalid",
	"monster_save_starter_state_invalid",
	"monster_save_terminal_invalid",
	"monster_save_uid_allocator_stale",
	"monster_save_wager_active_terminal_collision",
	"monster_save_wager_revision_stale",
	"monster_save_wager_sequence_stale",
	"monster_save_wager_settlement_revision_invalid",
	"monster_save_wager_terminal_invalid",
	"monster_save_wager_terminal_schema_invalid",
	"organization_save_invalid",
	"owner_binding_missing",
	"owner_capture_empty",
	"owner_capture_method_missing",
	"owner_capture_mutated_runtime",
	"owner_capture_mutation_rollback_failed",
	"owner_capture_not_pure_data",
	"owner_capture_result_not_dictionary",
	"owner_capture_valid",
	"owner_capture_verification_wrong_type",
	"owner_checkpoint_capture_failed",
	"owner_checkpoint_method_missing",
	"owner_checkpoint_not_pure_data",
	"owner_checkpoint_result_not_dictionary",
	"owner_header_invalid",
	"owner_live_fingerprint_method_missing",
	"owner_live_fingerprint_not_dictionary",
	"owner_live_fingerprint_not_pure_data",
	"owner_live_fingerprint_unavailable",
	"owner_live_fingerprint_valid",
	"owner_node_missing",
	"owner_capture_cross_owner_mutation",
	"owner_preflight_normalized_state_invalid",
	"owner_preflight_rejected",
	"owner_preflight_mutated_runtime",
	"organization_save_actor_shape_invalid",
	"organization_save_capability_secret_missing",
	"organization_save_field_type_invalid",
	"organization_save_journal_invalid",
	"organization_save_not_pure_data",
	"organization_save_player_invalid",
	"organization_save_shape_invalid",
	"organization_save_unconfigured_state_invalid",
	"organization_save_version_mismatch",
	"owner_registry_invalid",
	"owner_schema_invalid",
	"owner_state_encode_failed",
	"product_market_entry_invalid",
	"product_market_id_invalid",
	"product_market_save_invalid",
	"pending_discard_quote_invalid",
	"pending_one_shot_demand_invalid",
	"pending_one_shot_supply_invalid",
	"phase_invalid",
	"processed_transaction_index_mismatch",
	"production_state_port_journal_invalid",
	"production_state_port_save_invalid",
	"production_state_port_transaction_id_invalid",
	"purchase_session_save_invalid",
	"purchase_session_snapshot_invalid",
	"purchase_session_binding_invalid",
	"purchase_session_field_type_invalid",
	"purchase_session_pending_payload_invalid",
	"purchase_session_player_duplicate",
	"purchase_session_selection_invalid",
	"queue_entry_invalid",
	"queue_event_mismatch",
	"queue_invalid",
	"quote_authority_preflight_unavailable",
	"quote_binding_fingerprint_invalid",
	"quote_binding_invalid",
	"quote_field_type_invalid",
	"quote_fingerprint_invalid",
	"quote_key_invalid",
	"quote_lifetime_invalid",
	"quote_price_snapshot_invalid",
	"quote_schema_invalid",
	"quote_session_binding_invalid",
	"quote_snapshot_invalid",
	"receipt_sequence_regressed",
	"sequence_regressed",
	"recent_flow_event_state_invalid",
	"region_history_entry_invalid",
	"region_history_invalid",
	"region_indices_invalid",
	"region_record_invalid",
	"region_slot_catalog_invalid",
	"region_supply_card_record_invalid",
	"region_supply_catalog_index_invalid",
	"region_supply_claimed_unique_invalid",
	"region_supply_configured_state_invalid",
	"region_supply_rack_listing_invalid",
	"region_supply_region_record_invalid",
	"region_supply_region_state_content_invalid",
	"region_supply_region_state_index_invalid",
	"region_supply_region_state_type_invalid",
	"region_supply_save_fields_invalid",
	"region_supply_save_header_invalid",
	"region_supply_save_not_codec_data",
	"region_supply_save_order_invalid",
	"region_supply_save_shape_invalid",
	"region_supply_transaction_journal_invalid",
	"region_supply_unconfigured_state_invalid",
	"region_infrastructure_save_invalid",
	"region_infrastructure_facility_record_invalid",
	"region_infrastructure_facility_shape_invalid",
	"region_infrastructure_lifecycle_index_invalid",
	"region_infrastructure_lifecycle_record_invalid",
	"region_infrastructure_receipt_record_invalid",
	"region_infrastructure_region_record_invalid",
	"region_infrastructure_region_shape_invalid",
	"region_infrastructure_save_fields_invalid",
	"region_infrastructure_save_header_invalid",
	"region_infrastructure_save_not_codec_data",
	"region_infrastructure_save_revision_invalid",
	"region_infrastructure_save_shape_invalid",
	"region_infrastructure_slot_generation_invalid",
	"region_infrastructure_tombstone_invalid",
	"region_infrastructure_tombstone_shape_invalid",
	"region_infrastructure_transaction_index_invalid",
	"region_supply_save_invalid",
	"registry_busy",
	"registry_internal_error",
	"restore_capability_incomplete",
	"retired_contract_payload_rejected",
	"rollback_transaction_record_invalid",
	"route_save_invalid",
	"route_empty_topology_state_invalid",
	"route_save_fields_invalid",
	"route_save_header_invalid",
	"route_save_not_codec_data",
	"route_save_shape_invalid",
	"ruleset_attestation_header_invalid",
	"ruleset_attestation_invalid",
	"ruleset_attestation_mismatch",
	"ruleset_attestation_not_codec_data",
	"ruleset_attestation_schema_invalid",
	"ruleset_attestation_shape_invalid",
	"ruleset_fingerprint_invalid",
	"ruleset_id_mismatch",
	"run_rng_preflight_failed",
	"run_rng_save_invalid",
	"run_rng_save_shape_invalid",
	"save_keys_invalid",
	"save_header_invalid",
	"save_not_pure_data",
	"save_revision_invalid",
	"save_world_shape_invalid",
	"schema_version_invalid",
	"schema_version_mismatch",
	"session_envelope_children_invalid",
	"session_envelope_dependency_missing",
	"session_envelope_v3_invalid",
	"session_runtime_preflight_failed",
	"session_save_invalid",
	"section_wrapper_invalid",
	"session_payload_invalid",
	"slot_generation_record_invalid",
	"source_item_invalid",
	"source_type_invalid",
	"state_port_restore_preflight_failed",
	"state_version_mismatch",
	"terminal_operation_journal_mismatch",
	"telemetry_end_recorded_invalid",
	"telemetry_entry_invalid",
	"telemetry_invalid",
	"transaction_journal_world_state_forbidden",
	"transaction_receipt_binding_invalid",
	"transaction_receipt_record_invalid",
	"transition_checkpoint_schema_unsupported",
	"victory_save_invalid",
	"victory_audit_remaining_invalid",
	"victory_audit_remaining_out_of_range",
	"victory_audit_roster_invalid",
	"victory_audit_roster_missing",
	"victory_audit_roster_not_stable_unique",
	"victory_audit_roster_player_invalid",
	"victory_audit_roster_state_mismatch",
	"victory_outcome_audit_roster_mismatch",
	"victory_outcome_ranking_cash_invalid",
	"victory_outcome_ranking_invalid",
	"victory_outcome_ranking_player_invalid",
	"victory_outcome_rankings_invalid",
	"victory_outcome_receipt_invalid",
	"victory_outcome_sequence_invalid",
	"victory_outcome_winner_invalid",
	"victory_qualification_elapsed_invalid",
	"victory_qualification_elapsed_out_of_range",
	"victory_qualification_invalid",
	"victory_qualification_player_invalid",
	"victory_resolved_receipt_missing",
	"victory_save_header_invalid",
	"victory_save_not_pure_data",
	"victory_save_payload_shape_invalid",
	"victory_save_shape_invalid",
	"victory_state_invalid",
	"weather_save_shape_invalid",
	"weather_damage_accounted_units_by_region_invalid",
	"weather_damage_applied_units_by_region_invalid",
	"weather_damage_last_accounted_world_us_invalid",
	"weather_save_fields_invalid",
	"weather_save_not_codec_data",
	"warehouse_inventory_record_invalid",
	"warehouse_or_one_shot_state_invalid",
	"waste_state_invalid",
	"world_effective_clock_invalid",
	"world_session_ai_state_forbidden",
	"world_session_city_intel_binding_invalid",
	"world_session_city_intel_invalid",
	"world_session_city_intel_key_invalid",
	"world_session_city_intel_key_mismatch",
	"world_session_city_intel_order_invalid",
	"world_session_city_intel_record_invalid",
	"world_session_city_intel_reveal_reason_invalid",
	"world_session_city_intel_value_invalid",
	"world_session_city_invalid",
	"world_session_city_owner_invalid",
	"world_session_collections_invalid",
	"world_session_district_field_missing",
	"world_session_district_field_type_invalid",
	"world_session_district_identity_invalid",
	"world_session_district_invalid",
	"world_session_district_neighbors_invalid",
	"world_session_district_not_data_only",
	"world_session_district_polygon_invalid",
	"world_session_duplicate_region_id",
	"world_session_duplicate_role_index",
	"world_session_geometry_invalid",
	"world_session_player_count_invalid",
	"world_session_player_field_missing",
	"world_session_player_field_type_invalid",
	"world_session_player_id_invalid",
	"world_session_player_invalid",
	"world_session_player_name_invalid",
	"world_session_player_not_data_only",
	"world_session_player_seat_invalid",
	"world_session_postcommit_cash_lineage_invalid",
	"world_session_postcommit_city_lineage_invalid",
	"world_session_postcommit_lineage_count_invalid",
	"world_session_postcommit_lineage_shape_invalid",
	"world_session_role_catalog_unavailable",
	"world_session_role_invalid",
	"world_session_schema_invalid",
	"world_session_preflight_failed",
	"facility_action_journal_shape_invalid",
	"facility_action_lifecycle_record_invalid",
	"sale_receipt_record_invalid",
	"sale_receipt_duplicate",
	"card_effect_batch_journal_invalid",
	"card_effect_batch_children_missing",
	"card_effect_batch_children_invalid",
	"card_effect_batch_child_ids_invalid",
	"card_effect_batch_pending_child_invalid",
	"card_effect_batch_child_binding_invalid",
	"card_effect_batch_terminal_child_still_pending",
	"card_effect_batch_settled_receipt_invalid",
	"card_effect_batch_rollback_receipt_missing",
	"card_effect_batch_rollback_receipt_invalid",
	"card_effect_batch_state_invalid",
	"orphan_pending_supply_batch",
	"orphan_pending_demand_batch",
	"commodity_postcommit_consumer_missing",
	"commodity_postcommit_save_section_invalid",
	"commodity_postcommit_save_section_missing",
	"commodity_postcommit_save_invalid",
	"commodity_postcommit_restore_failed",
	"asset_recovery_journal_invalid",
	"commodity_belt_visibility_item_ids_not_canonical",
	"terminal_operation_transaction_id_invalid",
	"terminal_operation_invalid",
	"market_listing_invalid",
	"ai_player_save_duplicate",
	"canonical_transition_checkpoint_unavailable",
	"finalized_transaction_has_next_intent",
	"completed_intents_out_of_order",
	"retryable_commitment_already_checked",
	"active_release_flag_inconsistent",
	"history_flag_inconsistent",
	"effect_flag_inconsistent",
	"counter_flag_inconsistent",
	"commitment_flag_inconsistent",
	"context_flag_inconsistent",
	"transition_checkpoint_cursor_invalid",
	"transition_checkpoint_lineage_invalid",
	"transition_checkpoint_lineage_too_large",
	"transition_checkpoint_entry_invalid",
	"transition_checkpoint_revision_regressed",
	"transition_checkpoint_order_not_contiguous",
	"transition_checkpoint_batch_not_zero_based",
	"transition_checkpoint_ahead_of_producer",
	"transition_checkpoint_cursor_mismatch",
	"transition_checkpoint_probe_unavailable",
	"card_resolution_queue_dependency_section_invalid",
	"card_resolution_queue_dependency_section_missing",
	"card_resolution_queue_dependency_facility_dependency_invalid",
	"card_resolution_queue_dependency_context_invalid",
	"card_resolution_queue_dependency_context_shape_invalid",
	"card_resolution_queue_dependency_slot_invalid",
	"card_resolution_queue_dependency_lineage_invalid",
	"card_resolution_queue_dependency_lineage_shape_invalid",
	"card_resolution_queue_dependency_execution_completed_ids_invalid",
	"card_resolution_queue_dependency_execution_inflight_ids_invalid",
	"card_resolution_queue_dependency_history_ids_invalid",
	"card_resolution_queue_dependency_execution_overlap",
	"card_resolution_queue_dependency_execution_record_invalid",
	"card_resolution_queue_dependency_execution_record_missing",
	"card_resolution_queue_dependency_history_record_invalid",
	"card_resolution_queue_dependency_history_record_missing",
	"card_resolution_queue_dependency_player_roster_invalid",
	"card_resolution_queue_dependency_settlement_record_invalid",
	"card_resolution_queue_dependency_player_missing",
	"card_resolution_queue_dependency_slot_missing",
	"card_resolution_queue_dependency_persistent_slot_missing",
	"card_resolution_queue_dependency_persistent_slot_mismatch",
	"card_resolution_queue_dependency_active_execution_mismatch",
	"card_resolution_queue_dependency_history_orphan",
	"card_resolution_queue_dependency_inflight_id_waiting",
	"card_resolution_queue_dependency_sequence_precedes_lineage",
	"card_resolution_queue_dependency_terminal_id_still_queued",
	"world_session_float_invalid",
	"world_session_vector_invalid",
	"world_session_color_invalid",
	"world_session_reserved_key_collision",
	"world_session_encoded_dictionary_invalid",
	"world_session_encoded_dictionary_key_invalid",
	"world_session_encoded_dictionary_duplicate",
	"world_session_dictionary_key_invalid",
	"world_session_variant_type_forbidden",
	"facility_card_escrow_request_id_invalid",
	"facility_card_escrow_actor_id_invalid",
	"facility_card_escrow_hand_slot_id_invalid",
	"facility_card_escrow_card_semantic_id_invalid",
	"facility_card_escrow_runtime_instance_id_invalid",
	"facility_card_escrow_escrow_id_invalid",
	"facility_card_escrow_intent_fingerprint_invalid",
	"facility_card_escrow_source_record_fingerprint_invalid",
	"facility_card_escrow_source_slot_fingerprint_invalid",
	"commodity_belt_visibility_card_inventory_missing",
	"commodity_belt_visibility_card_inventory_invalid",
	"commodity_belt_visibility_belt_missing",
	"commodity_belt_visibility_belt_invalid",
	"commodity_belt_visibility_card_inventory_mismatch",
	"commodity_belt_visibility_acl_invalid",
	"commodity_belt_visibility_item_invalid",
	"card_inventory_session_foundation_missing",
	"card_inventory_session_roster_missing",
	"card_inventory_district_purchase_invalid",
	"card_inventory_district_player_missing",
	"ai_restore_session_foundation_missing",
	"ai_restore_session_roster_missing",
	"ai_restore_session_roster_invalid",
	"ai_save_actor_roster_mismatch",
	"annotation_checkpoint_not_data_only",
	"annotation_history_fingerprint_invalid",
	"annotation_history_fingerprint_mismatch",
	"annotation_dependency_shape_invalid",
	"annotation_history_id_invalid",
	"card_annotation_public_history_missing",
	"military_dependency_bankruptcy_player_missing",
	"military_dependency_context_invalid",
	"military_dependency_context_shape_invalid",
	"military_dependency_district_roster_invalid",
	"military_dependency_journal_unit_invalid",
	"military_dependency_player_roster_invalid",
	"military_dependency_region_district_mismatch",
	"military_dependency_region_roster_invalid",
	"military_dependency_section_invalid",
	"military_dependency_section_missing",
	"military_dependency_session_world_invalid",
	"military_dependency_unit_invalid",
	"organization_session_roster_invalid",
	"organization_session_roster_mismatch",
	"organization_session_roster_missing",
	"route_dependency_facility_invalid",
	"route_dependency_manifest_mismatch",
	"route_dependency_region_district_mismatch",
	"route_dependency_region_invalid",
	"route_dependency_region_legacy_index_invalid",
	"route_dependency_rules_unavailable",
	"route_dependency_section_invalid",
	"route_dependency_section_missing",
	"route_dependency_session_district_invalid",
	"route_dependency_session_world_invalid",
	"route_dependency_topology_invalid",
	"route_dependency_topology_revision_mismatch",
	"route_dependency_topology_shape_invalid",
	"route_dependency_weather_history_reference_invalid",
	"route_dependency_weather_invalid",
	"route_dependency_weather_record_invalid",
	"route_dependency_weather_reference_invalid",
	"route_dependency_weather_shape_invalid",
	"commodity_postcommit_asset_binding_collision",
	"commodity_postcommit_asset_binding_invalid",
	"commodity_postcommit_asset_target_ahead",
	"commodity_postcommit_asset_target_behind",
	"commodity_postcommit_asset_target_unbound",
	"commodity_postcommit_bankruptcy_binding_collision",
	"commodity_postcommit_bankruptcy_binding_invalid",
	"commodity_postcommit_bankruptcy_target_ahead",
	"commodity_postcommit_bankruptcy_target_behind",
	"commodity_postcommit_bankruptcy_target_unbound",
	"commodity_postcommit_consumer_cursor_invalid",
	"commodity_postcommit_consumer_flow_cursor_mismatch",
	"commodity_postcommit_consumer_journal_missing",
	"commodity_postcommit_consumer_pending_cursor_invalid",
	"commodity_postcommit_consumer_pending_identity_invalid",
	"commodity_postcommit_consumer_record_invalid",
	"commodity_postcommit_consumer_terminal_cursor_invalid",
	"commodity_postcommit_dependency_shape_invalid",
	"commodity_postcommit_world_binding_invalid",
	"commodity_postcommit_world_lineage_missing",
	"commodity_postcommit_world_target_ahead",
	"commodity_postcommit_world_target_behind",
	"commodity_postcommit_world_target_unbound",
]
const NOT_PURE_REASON_CODES := [
	"ruleset_attestation_not_codec_data",
	"region_infrastructure_save_not_codec_data",
	"save_not_pure_data",
	"facility_action_lifecycle_not_pure_data",
	"region_supply_save_not_codec_data",
	"route_save_not_codec_data",
	"invalid_asset_save_payload",
	"organization_save_not_pure_data",
	"recent_flow_event_state_invalid",
	"warehouse_or_one_shot_state_invalid",
	"military_save_not_codec_data",
	"military_unit_not_codec_data",
	"weather_save_not_codec_data",
	"card_resolution_queue_save_not_codec_data",
	"card_resolution_queue_entry_not_codec_data",
	"history_state_not_data_only",
	"victory_save_not_pure_data",
	"world_session_player_not_data_only",
	"world_session_district_not_data_only",
	"facility_card_escrow_card_not_pure_data",
]
const HEADER_REASON_CODES := [
	"ruleset_attestation_header_invalid",
	"ruleset_attestation_schema_invalid",
	"region_infrastructure_save_header_invalid",
	"route_save_header_invalid",
	"asset_save_header_invalid",
	"organization_save_version_mismatch",
	"military_save_header_invalid",
	"card_resolution_queue_save_header_invalid",
	"ai_save_header_invalid",
	"bankruptcy_save_header_invalid",
	"victory_save_header_invalid",
]
const VERSION_REASON_CODES := [
	"region_supply_save_header_invalid",
	"facility_action_lifecycle_version_invalid",
	"monster_save_schema_attestation_invalid",
	"monster_save_atomic_schema_mismatch",
	"monster_save_battle_lifecycle_schema_invalid",
	"monster_battle_lifecycle_schema_invalid",
	"schema_version_invalid",
	"event_schema_version_invalid",
	"history_schema_invalid",
	"quote_schema_invalid",
	"execution_save_schema_unsupported",
	"transition_checkpoint_schema_unsupported",
	"state_version_mismatch",
	"schema_version_mismatch",
]
const RULESET_REASON_CODES := [
	"ruleset_attestation_mismatch",
	"ruleset_id_mismatch",
]
const MUTATION_REASON_CODES := [
	"commodity_flow_save_preflight_mutated_live_owner",
	"owner_capture_cross_owner_mutation",
	"owner_capture_mutated_runtime",
	"owner_capture_mutation_rollback_failed",
	"owner_preflight_mutated_runtime",
]


static func build(fields: Dictionary) -> Dictionary:
	var failure_class := _safe_upper_token(fields.get("failure_class", "REGISTRY_INTERNAL_ERROR"), "REGISTRY_INTERNAL_ERROR", 64)
	if failure_class not in FAILURE_CLASSES:
		failure_class = "REGISTRY_INTERNAL_ERROR"
	return {
		"schema_version": SCHEMA_VERSION,
		"registry_operation_id": _safe_identifier(fields.get("registry_operation_id", ""), 96),
		"capture_sequence": maxi(0, _strict_int(fields.get("capture_sequence"), 0)),
		"section_index": maxi(0, _strict_int(fields.get("section_index"), 0)),
		"section_id": _safe_identifier(fields.get("section_id", ""), 96),
		"owner_id": _safe_identifier(fields.get("owner_id", ""), 96),
		"owner_node_path": _safe_path(fields.get("owner_node_path", "")),
		"owner_script_path": _safe_path(fields.get("owner_script_path", "")),
		"capture_method": _safe_identifier(fields.get("capture_method", ""), 96),
		"failure_class": failure_class,
		"reason_code": sanitize_reason_code(fields.get("reason_code", "registry_internal_error")),
		"method_missing": _strict_bool(fields.get("method_missing")),
		"method_exception": _strict_bool(fields.get("method_exception")),
		"result_not_dictionary": _strict_bool(fields.get("result_not_dictionary")),
		"result_empty": _strict_bool(fields.get("result_empty")),
		"result_not_pure_data": _strict_bool(fields.get("result_not_pure_data")),
		"result_header_invalid": _strict_bool(fields.get("result_header_invalid")),
		"result_version_invalid": _strict_bool(fields.get("result_version_invalid")),
		"result_ruleset_invalid": _strict_bool(fields.get("result_ruleset_invalid")),
		"state_version_observed": _strict_int(fields.get("state_version_observed"), -1),
		"ruleset_id_observed": _safe_ruleset_id(fields.get("ruleset_id_observed", "")),
		"live_state_mutated_during_capture": _strict_bool(fields.get("live_state_mutated_during_capture")),
		"private_payload_redacted": true,
	}


static func is_failure_class(value: String) -> bool:
	return value in FAILURE_CLASSES


static func is_reason_code(value: String) -> bool:
	return value in REASON_CODES


static func sanitize_reason_code(value: Variant) -> String:
	var candidate := _safe_lower_token(value, "registry_internal_error", 128)
	return candidate if candidate in REASON_CODES else "registry_internal_error"


static func _strict_int(value: Variant, fallback: int) -> int:
	return int(value) if typeof(value) == TYPE_INT else fallback


static func _strict_bool(value: Variant) -> bool:
	return bool(value) if value is bool else false


static func _safe_lower_token(value: Variant, fallback: String, maximum_length: int) -> String:
	if not (value is String or value is StringName):
		return fallback
	var text := str(value)
	if text.is_empty() or text.length() > maximum_length:
		return fallback
	for index in range(text.length()):
		if not "abcdefghijklmnopqrstuvwxyz0123456789_".contains(text.substr(index, 1)):
			return fallback
	return text


static func _safe_upper_token(value: Variant, fallback: String, maximum_length: int) -> String:
	if not (value is String or value is StringName):
		return fallback
	var text := str(value)
	if text.is_empty() or text.length() > maximum_length:
		return fallback
	for index in range(text.length()):
		if not "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_".contains(text.substr(index, 1)):
			return fallback
	return text


static func _safe_identifier(value: Variant, maximum_length: int) -> String:
	if not (value is String or value is StringName):
		return ""
	var text := str(value)
	if text.length() > maximum_length:
		return ""
	for index in range(text.length()):
		if not "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_.:-".contains(text.substr(index, 1)):
			return ""
	return text


static func _safe_path(value: Variant) -> String:
	if not (value is String or value is StringName):
		return ""
	var text := str(value)
	if text.length() > 256:
		return ""
	for index in range(text.length()):
		if not "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_./:-".contains(text.substr(index, 1)):
			return ""
	return text


static func _safe_ruleset_id(value: Variant) -> String:
	var text := str(value) if value is String or value is StringName else ""
	return text if text in ["", "v0.6"] else ""
