extends SceneTree

const MAIN_SOURCE_PATH := "res://scripts/main.gd"
const MAP_SOURCE_PATH := "res://scripts/map_view.gd"

var _failures: Array[String] = []


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	var main_source := FileAccess.get_file_as_string(MAIN_SOURCE_PATH)
	var map_source := FileAccess.get_file_as_string(MAP_SOURCE_PATH)
	_expect(main_source != "", "main.gd can be read for visual layout contract checks")
	_expect(map_source != "", "map_view.gd can be read for planet projection contract checks")
	_expect(main_source.contains("太空辛迪加｜星球赌桌") and main_source.contains("星球赌桌｜中央星球"), "main table keeps the gambling-table planet theme")
	_expect(main_source.contains("MainMenuPlanetLobbyPanel") and main_source.contains("MainMenuPlanetLobbyBody") and main_source.contains("MainMenuPlanetMedallion") and main_source.contains("MainMenuLobbyKpiGrid") and main_source.contains("MainMenuLobbyActionGrid"), "main menu uses a board-game planet lobby before branch lists")
	_expect(main_source.contains("HeaderStatusChipRail") and main_source.contains("HeaderStatusChip") and main_source.contains("HeaderStatusMeterBar") and main_source.contains("◆ 空闲") and main_source.contains("⌛ 沙漏") and main_source.contains("♛ 目标") and main_source.contains("_set_header_status_meter") and not main_source.contains("◷ 00:00"), "top table status uses compact board-game chips and a sandglass meter instead of a numeric time chip")
	_expect(main_source.contains("MapControlBar") and main_source.contains("MapControlChipRail") and main_source.contains("MapControlChip") and main_source.contains("◎ 赌桌中央") and main_source.contains("双击看牌"), "map toolbar uses compact board-game control chips while keeping the planet central")
	_expect(main_source.contains("map_view.custom_minimum_size = Vector2(560, 430)"), "main map keeps a large central minimum footprint")
	_expect(main_source.contains("UI_LIVE_REFRESH_SECONDS") and main_source.contains("UI_MAP_REFRESH_SECONDS") and main_source.contains("UI_FULL_REFRESH_SECONDS") and main_source.contains("ui_map_refresh_timer") and main_source.contains("_update_process_ui_refresh") and main_source.contains("_refresh_live_ui") and main_source.contains("_refresh_board()") and main_source.contains("_refresh_player_panel()"), "main table splits realtime status, map, and heavy player-panel layout refreshes")
	_expect(main_source.contains("card_resolution_track_signature") and main_source.contains("_card_resolution_track_signature") and main_source.contains("_card_resolution_track_entry_signature") and main_source.contains("playtest_flow_compass_signature") and main_source.contains("_playtest_flow_compass_signature"), "static table rails cache content signatures instead of rebuilding unchanged cards and compass chips")
	_expect(main_source.contains("PlaytestFlowCompass") and main_source.contains("PlaytestFlowCompassStepRail") and main_source.contains("PlaytestFlowCompassStepChip") and main_source.contains("PlaytestFlowCompassNextLabel") and main_source.contains("试玩\\n罗盘") and main_source.contains("\"点区\"") and main_source.contains("\"首召\"") and main_source.contains("\"建城\"") and main_source.contains("\"买牌\"") and main_source.contains("\"出牌\"") and main_source.contains("_refresh_playtest_flow_compass"), "central planet board exposes a thin playtest flow compass for first-minute usability")
	_expect(main_source.contains("WeatherForecastBar") and main_source.contains("WeatherForecastChipRail") and main_source.contains("☄ 天气预报"), "weather forecast uses a compact board-game chip rail on the main table")
	_expect(main_source.contains("CardResolutionTableBanner") and main_source.contains("dock.anchor_left = 0.27") and main_source.contains("dock.anchor_right = 0.66"), "card resolution reveal uses a top-center table banner instead of fighting the right-side card drawer")
	_expect(main_source.contains("全桌结算横幅") and main_source.contains("不遮住右侧牌架或底部手牌") and main_source.contains("BottomCountdownOverlay") and main_source.contains("BottomCountdownPanel") and main_source.contains("CardResolutionRevealTimerBar") and main_source.contains("_refresh_bottom_countdown_bar"), "card resolution banner stays compact while the bottom table sandglass owns countdown timing")
	_expect(main_source.contains("牌轨") and main_source.contains("CardResolutionTtaMarketPanel") and main_source.contains("CardResolutionTtaOfferRailFrame") and main_source.contains("CardResolutionTtaMarketHeader") and main_source.contains("panel.custom_minimum_size = Vector2(0, 36)") and main_source.contains("公共牌槽") and main_source.contains("CardResolutionTtaSlotMarketMat") and main_source.contains("CardResolutionTtaAgeMarketRuler") and main_source.contains("CardResolutionTtaCostBandRail") and main_source.contains("CardResolutionTtaCostCell") and main_source.contains("CardResolutionTtaSlotGrooveRail") and main_source.contains("CardResolutionTtaScrollShell") and main_source.contains("CardResolutionTtaScrollCue") and main_source.contains("CARD_TRACK_VISIBLE_SLOT_COUNT := 12") and main_source.contains("CARD_TRACK_SLOT_HEIGHT := 22") and main_source.contains("CARD_TRACK_EMPTY_SLOT_HEIGHT := 15") and main_source.contains("_set_card_resolution_track_compact_empty") and main_source.contains("CardResolutionTtaGhostSlot") and main_source.contains("CardResolutionTtaMiniCard") and main_source.contains("CardResolutionTtaSlotIndex") and main_source.contains("CardResolutionCostPipRail") and main_source.contains("_set_card_resolution_track_slot_hover") and main_source.contains("_maybe_follow_card_resolution_track"), "anonymous card track uses a thin Through-the-Ages-like public card-slot rail with a compact empty state")
	_expect(main_source.contains("player_box = _add_panel(player_panel_scroll, \"玩家板｜桌边牌架\")"), "player hand area is framed as a scroll-safe table-edge player board")
	_expect(main_source.contains("player_panel_scroll.custom_minimum_size = Vector2(0, 300)") and main_source.contains("首屏先扫资源筹码、手牌和行动托盘"), "bottom table-edge board is compact enough to protect the planet while keeping core controls visible")
	_expect(main_source.contains("TerraformingMarsLikeResourceBoard") and main_source.contains("PlayerResourceCubeRail") and main_source.contains("PlayerResourceCube"), "bottom player area includes a Terraforming-Mars-like resource cube board")
	_expect(main_source.contains("dashboard_rail.name = \"PlayerDashboardTopRail\"") and main_source.contains("table_rail.name = \"PlayerTableRail\"") and main_source.contains("hand_column.name = \"PlayerHandColumn\"") and main_source.contains("tray_column.name = \"PlayerActionColumn\""), "bottom player board has a top dashboard plus hand/action side-by-side rail")
	_expect(main_source.contains("PlayerTableauBoard") and main_source.contains("PlayerIdentityMiniCard") and main_source.contains("PlayerTableauGoalMeter") and main_source.contains("PlayerTableauGoalProgressBar") and main_source.contains("PlayerTableauChipGrid") and main_source.contains("PlayerSeatSelectorRail"), "bottom player area uses a board-game player tableau with public identity, goal meter, and resource chips")
	_expect(main_source.contains("TableGoalPrompt") and main_source.contains("TableGoalPrimaryActionRail") and main_source.contains("TableGoalPrimaryActionButton") and main_source.contains("TableGoalPromptChipRail") and main_source.contains("目标提示｜下一步") and main_source.contains("固定行动条"), "bottom rail keeps next-action guidance as a fixed compact table-goal strip with one primary CTA")
	_expect(main_source.contains("SelectedDistrictBoard") and main_source.contains("SelectedDistrictTilePlate") and main_source.contains("SelectedDistrictChipRail") and main_source.contains("SelectedDistrictActionLampRail") and main_source.contains("SelectedDistrictActionLampLabel") and main_source.contains("SelectedDistrictActionGrid") and main_source.contains("地块板｜选区行动") and main_source.contains("OpeningGuideTimeline") and main_source.contains("OpeningGuideStepToken") and main_source.contains("OpeningGuidePrimaryActionButton"), "selected district and opening guide use compact board-game tile/timeline components")
	_expect(main_source.contains("FirstSummonCard") and main_source.contains("FirstSummonChipRail") and main_source.contains("FirstSummonPreviewStrip") and main_source.contains("FirstSummonPreviewIcon") and main_source.contains("FirstSummonDeployButton"), "first summon prompt is a compact table-side starter decision instead of a duplicate card face")
	_expect(main_source.contains("RoleCodexIdentityBoardPanel") and main_source.contains("RoleCodexIdentityHeader") and main_source.contains("RoleCodexIdentityChipRail") and main_source.contains("RoleCodexAbilityKpiGrid") and main_source.contains("RoleCodexRouteCard"), "role codex detail opens with a public identity board and route cards")
	_expect(main_source.contains("TutorialQuickStartPanel") and main_source.contains("TutorialQuickStartStepGrid") and main_source.contains("TutorialQuickStartTrapGrid") and main_source.contains("试玩速成板"), "tutorial menu uses a quick-start board with step and trap cards")
	_expect(main_source.contains("ActionTrayModuleChipRail") and main_source.contains("ActionTrayModuleChip") and main_source.contains("⌖选区") and main_source.contains("⇄合约"), "action tray exposes module chips before detailed controls")
	_expect(main_source.contains("MainActionDock") and main_source.contains("MainActionDockRow") and main_source.contains("MainActionDockButton") and main_source.contains("快捷\\n行动") and main_source.contains("\"建城\"") and main_source.contains("\"牌架\"") and main_source.contains("\"买牌\"") and main_source.contains("\"出牌\""), "action tray exposes a Terraforming-Mars-like four-button quick action dock for build, market, buy, and play")
	_expect(main_source.contains("TemporaryDecisionCard") and main_source.contains("TemporaryDecisionChipRail") and main_source.contains("桌边决策｜") and main_source.contains("ContractOfferTermsBoard") and main_source.contains("ContractOfferTermsHeader") and main_source.contains("ContractOfferDecisionTimerBar") and main_source.contains("ContractOfferTermRail") and main_source.contains("ContractOfferTermLamp") and main_source.contains("ContractOfferTermSignal") and main_source.contains("ContractOfferTermLabel"), "temporary decisions use a unified table-edge decision card with status chips and contract terms")
	_expect(main_source.contains("MonsterWagerChipRail") and main_source.contains("MonsterWagerSideChipRail") and main_source.contains("MonsterWagerPublicBetBoard") and main_source.contains("MonsterWagerPublicBetGrid") and main_source.contains("MonsterWagerPlayerToken") and main_source.contains("MonsterWagerBetLine") and main_source.contains("奖池¥"), "monster wagers expose pot, ante, timer, side chips, and public player bet slots")
	_expect(main_source.contains("card_minimum_size = Vector2(148, 148)") and main_source.contains("var art_height := 34 if compact_hand_card else") and main_source.contains("HAND_CARD_HOVER_SCALE") and main_source.contains("HAND_CARD_HOVER_LIFT_PIXELS") and main_source.contains("HandCardHoverLiftCard") and main_source.contains("_connect_hand_card_hover") and main_source.contains("_animate_hand_card_hover"), "compact hand cards stay small enough for the first-screen bottom rack while preserving UiCard-style hover lift detail")
	_expect(main_source.contains("CardFaceChipRail") and main_source.contains("card_face_chip_rail") and main_source.contains("_add_card_face_chip_rail") and main_source.contains("HandCardPlayLamp") and main_source.contains("HandCardPlayLampStatus") and main_source.contains("HandCardPlayStateRail") and main_source.contains("if not compact_hand_card") and main_source.contains("action_button.custom_minimum_size = Vector2(0, 22 if is_hand_card else 24)"), "card faces use mini-card chip rails and a status lamp while moving long rules into hover/detail")
	_expect(main_source.contains("CardCodexTcgDetailLayout") and main_source.contains("CardCodexTcgSummaryPanel") and main_source.contains("扫牌顺序") and main_source.contains("CardCodexUpgradeLadder") and main_source.contains("CardCodexUpgradeStepCard"), "card codex detail uses a TCG-style quick-read panel and upgrade ladder")
	_expect(main_source.contains("CardCodexCategoryRail") and main_source.contains("CardCodexCategoryChipRow") and main_source.contains("CardCodexCategoryChip") and main_source.contains("牌型筛选"), "card codex grid uses a compact top category chip rail")
	_expect(main_source.contains("ProductCodexMarketBoardPanel") and main_source.contains("ProductCodexMarketHeader") and main_source.contains("ProductCodexMarketChipRail") and main_source.contains("ProductCodexMarketKpiGrid") and main_source.contains("ProductCodexStrategyCard"), "product codex detail opens with a board-game commodity market board")
	_expect(main_source.contains("RegionCodexTileBoardPanel") and main_source.contains("RegionCodexTileHeader") and main_source.contains("RegionCodexTileChipRail") and main_source.contains("RegionCodexTileKpiGrid") and main_source.contains("RegionCodexClueCard"), "region codex detail opens with a board-game tile board and clue cards")
	_expect(main_source.contains("BestiaryMonsterBoardPanel") and main_source.contains("BestiaryMonsterHeader") and main_source.contains("BestiaryMonsterChipRail") and main_source.contains("BestiaryMonsterKpiGrid") and main_source.contains("BestiaryMonsterActionGrid") and main_source.contains("BestiaryMonsterActionCard"), "monster bestiary detail opens with a board-game monster unit board and action cards")
	_expect(main_source.contains("hand_scroll.custom_minimum_size = Vector2(0, 148)") and main_source.contains("PlayerHandRackPanel") and main_source.contains("PlayerHandRackBody") and main_source.contains("PlayerHandRackInfoRail") and main_source.contains("PlayerHandRackChipRail") and main_source.contains("PlayerHandEmptySlot") and main_source.contains("悬停抬起"), "hand rack uses a first-screen mini-card rack with a side info rail and hover-lift affordance")
	_expect(main_source.contains("DistrictSupplyShelfBoard") and main_source.contains("DistrictSupplyShelfChipRail") and main_source.contains("DistrictSupplyMarketStatusRail") and main_source.contains("DistrictSupplyMarketSummaryChip") and main_source.contains("牌架 %d") and main_source.contains("价格已锁") and main_source.contains("手牌 %d/%d") and main_source.contains("\"可买\"") and main_source.contains("\"弃牌\"") and main_source.contains("\"仅看\""), "district card rack exposes a shelf board with compact market status and hand-pressure chips")
	_expect(main_source.contains("DistrictSupplySideDrawer") and main_source.contains("margin.anchor_left = 0.60") and main_source.contains("DistrictSupplyDrawerStack") and main_source.contains("DistrictSupplyMarketGrid") and main_source.contains("DistrictSupplyPreviewPanel"), "district card rack opens as a right-side market drawer instead of a central modal")
	_expect(main_source.contains("市场牌架｜悬停看｜双击买") and main_source.contains("DistrictSupplyRuleStrip") and main_source.contains("市场格｜价格/状态/路线") and main_source.contains("DistrictSupplyMarketCardPanel") and main_source.contains("DistrictSupplyMarketCardChipRail") and main_source.contains("DistrictSupplyMarketCardStateBand") and main_source.contains("DistrictSupplyMarketCardStateSignal") and main_source.contains("DistrictSupplyMarketCardStateLabel") and main_source.contains("DistrictSupplyMarketCardColorTick") and main_source.contains("DistrictSupplyPurchaseVerdictRail") and main_source.contains("DistrictSupplyPurchaseVerdictLabel") and main_source.contains("牌面预览｜效果/购买结论"), "district side drawer explains browse-vs-buy with compact board-game market cards")
	_expect(main_source.contains("EconomyDashboardPanel") and main_source.contains("EconomyDashboardKpiGrid") and main_source.contains("EconomyDashboardListCard") and main_source.contains("经济仪表板") and main_source.contains("下方仪表板只显示可扫读信息"), "economy overview opens with a board-game dashboard instead of a long report")
	_expect(main_source.contains("StandingsScoreboardPanel") and main_source.contains("StandingsRaceKpiGrid") and main_source.contains("StandingsPlayerScoreGrid") and main_source.contains("StandingsPlayerScoreCard") and main_source.contains("局势记分板"), "standings page opens with a board-game scoreboard instead of prose rankings")
	_expect(main_source.contains("FinalSettlementBoardPanel") and main_source.contains("FinalSettlementKpiGrid") and main_source.contains("FinalSettlementRankTrack") and main_source.contains("FinalSettlementRankCard") and main_source.contains("FinalSettlementAfterActionGrid"), "final settlement opens with a board-game postgame scoreboard and after-action links")
	_expect(main_source.contains("IntelDossierBoardPanel") and main_source.contains("IntelDossierKpiGrid") and main_source.contains("IntelDossierClueGrid") and main_source.contains("IntelDossierClueCard") and main_source.contains("情报侦探板"), "intel dossier opens with a board-game detective board instead of a long evidence report")
	_expect(main_source.contains("setup_summary_chips") and main_source.contains("setup_seat_card") and main_source.contains("setup_seat_chips") and main_source.contains("NewGameSetupLobbyPanel") and main_source.contains("NewGameSetupFlowTrack") and main_source.contains("NewGameSetupFlowStepCard") and main_source.contains("NewGameSetupSeatIdentityBoard") and main_source.contains("NewGameSetupSeatInfoCard"), "new-game setup uses a board-game lobby flow with setup chips and public seat cards")
	_expect(main_source.contains("menu_continue_button.visible = can_continue and show_main_actions") and main_source.contains("_hide_global_menu_navigation_for_catalog()"), "subpage shell hides global buttons unless a root page explicitly asks for them")
	var hand_index := main_source.find("_add_player_hand_rack(hand_column")
	var resource_index := main_source.find("_add_player_resource_cube_rail(dashboard_rail")
	var goal_index := main_source.find("_add_table_goal_prompt(hand_column")
	var tray_function_index := main_source.find("func _add_player_action_tray")
	var action_goal_index := main_source.find("_add_table_goal_prompt(box, player_index")
	var tray_index := main_source.find("_add_player_action_tray(tray_column")
	var scroll_index := main_source.find("scroll.custom_minimum_size = Vector2(0, 94)")
	var first_summon_index := main_source.find("_add_first_summon_prompt(action_tray")
	var district_action_index := main_source.find("_add_selected_district_action_panel(action_tray")
	var bid_row_index := main_source.find("_add_bid_control_card(action_tray")
	var dashboard_index := main_source.find("dashboard_rail.name = \"PlayerDashboardTopRail\"")
	_expect(hand_index >= 0 and tray_index > hand_index, "hand rack appears before secondary action tray")
	_expect(dashboard_index >= 0 and dashboard_index < hand_index, "Terraforming-Mars-like player dashboard appears before the detailed hand rack")
	_expect(resource_index > dashboard_index and resource_index < hand_index, "thin resource cube rail stays in the top dashboard for scan-first play")
	_expect(goal_index < 0 and tray_function_index >= 0 and action_goal_index > tray_function_index and scroll_index > action_goal_index, "next-step goal prompt is fixed above the action-tray scroll area")
	_expect(first_summon_index < 0 and action_goal_index > tray_function_index, "starter summon now uses the single primary action slot instead of a duplicate action-tray card")
	_expect(district_action_index > tray_index and bid_row_index > tray_index, "district actions and bid controls are inside the action tray")
	_expect(main_source.contains("ActionTrayCurrentHeader") and main_source.contains("当前行动") and main_source.contains("筹码定位") and main_source.contains("不遮住星球和手牌"), "secondary actions are explicitly contained in a compact table-edge current-action tray")
	_expect(main_source.contains("BidControlCard") and main_source.contains("BidControlChipRail") and main_source.contains("公开报价"), "bid controls use a compact public-bid table card")
	_expect(main_source.contains("OwnerGuessCard") and main_source.contains("OwnerGuessChipRail") and main_source.contains("OwnerGuessAvatarRow"), "card-owner guessing uses a dedicated table-side wager card")
	_expect(main_source.contains("资料大厅") and main_source.contains("价格带") and not main_source.contains("价格梯度"), "player-facing menu text remains concise and non-developmental")
	_expect(map_source.contains("PLANET_PROJECTION_BLEND_NAME := \"PlanetProjectionBlend\"") and map_source.contains("func _planet_projection_blend") and map_source.contains("func _projection_smoothstep"), "map projection has an explicit smooth local-to-globe blend contract")
	_expect(map_source.contains("ANIMATED_REDRAW_INTERVAL_SECONDS") and map_source.contains("INTERACTION_DETAIL_SETTLE_SECONDS") and map_source.contains("INTERACTION_REDRAW_INTERVAL_SECONDS") and map_source.contains("ZOOM_SMOOTHING_SPEED") and map_source.contains("_target_view_zoom") and map_source.contains("_update_smooth_zoom") and map_source.contains("_map_detail_reduced") and map_source.contains("_draw_region_fill_fast") and map_source.contains("_draw_globe_region_fill_fast") and map_source.contains("_build_visual_payload_signature") and map_source.contains("_should_draw_dense_region_labels"), "map view throttles animated redraws, smooths wheel zoom, caches visual payloads, and switches to lightweight detail during drag/zoom")
	_expect(map_source.contains("PLANET_PROJECTION_VISIBILITY_FADE_START") and map_source.contains("_projection_visibility_alpha_for_district"), "map projection fades far-side labels and regions during the globe transition")
	_expect(map_source.contains("星球全景｜滚轮贴近") and map_source.contains("拉远中｜地表牌板正在卷成星球") and map_source.contains("局部地表｜滚轮拉远看星球"), "map projection hints use player-facing table language")
	_expect(map_source.contains("\"牌架 %d\"") and map_source.contains("双击区域看牌") and not map_source.contains("区域可提供卡片"), "selected map region shows a compact card-rack badge instead of a long card list over the planet")
	_expect(map_source.contains("projection_contract") and map_source.contains("local_xy_eases_into_center_globe"), "betting table map report exposes the planet projection policy")
	_finish()


func _expect(condition: bool, message: String) -> void:
	if condition:
		return
	_failures.append(message)
	push_error("Visual layout contract failure: %s" % message)


func _finish() -> void:
	if _failures.is_empty():
		print("Visual layout contract test passed.")
		quit(0)
	else:
		print("Visual layout contract test failed: %s" % " / ".join(_failures))
		quit(1)
