extends RefCounted
class_name RulesetV04ConformanceRegistry

const STATUS_ALIGNED := "aligned"
const STATUS_CUTOVER_COMPLETE := "cutover_complete"
const STATUS_MISMATCH := "mismatch"
const STATUS_MISSING := "missing"
const STATUS_BLOCKED := "blocked"

const RECORDS := [
	{
		"rule_id": "shared_card_window",
		"rulebook_section": "Card play / shared 30-second window",
		"expected_behavior": "All players organize for 25 seconds, then lock for 5 seconds within one 30-second group window.",
		"current_owner": "RulesetRuntimeBridge + CardResolutionRuntimeController",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Profile timing 30/25/5", "Runtime controller configured by main.gd through bridge"],
		"cutover_action": "Keep controller timing configured only from RulesetRuntimeBridge.",
		"deletion_candidates": ["main.gd duplicate 30/25/5 constants"],
		"risk": "medium",
		"next_sprint": "Card Resolution Queue Ownership (separate gate)",
	},
	{
		"rule_id": "card_group_limit",
		"rulebook_section": "Card play / group construction",
		"expected_behavior": "Each player submits 0-3 cards by default; explicit effects may extend the limit to 4.",
		"current_owner": "RulesetRuntimeBridge + SharedCardGroupWindow",
		"current_status": STATUS_ALIGNED,
		"runtime_evidence": ["Profile default limit 3", "Profile maximum limit 4"],
		"cutover_action": "Keep runtime submissions reading the profile default while SharedCardGroupWindow owns validation.",
		"deletion_candidates": ["main.gd duplicate default group limit"],
		"risk": "medium",
		"next_sprint": "Card group capability parity gate",
	},
	{
		"rule_id": "realtime_cashflow",
		"rulebook_section": "Economy / realtime income",
		"expected_behavior": "Urbanization shares and active trade generate realtime income.",
		"current_owner": "RulesetRuntimeBridge + EconomyCashflowRuntimeController + main.gd payout application adapter",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["realtime_income_enabled=true", "Controller owns 1-second cadence, 60-second basis, fractional remainder arithmetic, and payout planning", "EconomyCashflowRuntimeCutoverBench passes 20 cases including real main owner/project delegation"],
		"cutover_action": "Keep cadence and payout planning in the controller while existing GDP formulas and domain mutation remain unchanged behind the main compatibility adapter.",
		"deletion_candidates": ["main.gd economy_cashflow_timer authority", "duplicate cashflow cadence constants", "main.gd project payout floor and remainder loop"],
		"risk": "high",
		"next_sprint": "Scenario Runtime Glue or a separately gated GDP Formula Runtime extraction",
	},
	{
		"rule_id": "card_play_requirements",
		"rulebook_section": "Card play / requirements",
		"expected_behavior": "Cards are playable only when their declared requirements and target constraints are satisfied.",
		"current_owner": "CardPlayEligibilityRuntimeService + CardPlayEligibilityWorldBridge",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["CardPlayEligibilityRuntimeBench passes 46/46", "UI, AI, Coach, Queue, and Execution revalidation share one reason_code envelope", "Legacy main.gd legality and target-trait functions are absent"],
		"cutover_action": "Keep requirements and target readiness single-owned; keep Queue and Execution transaction ownership separate.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Monster Runtime Hard Cutover",
	},
	{
		"rule_id": "active_card_execution",
		"rulebook_section": "Card groups / resolution, counter, and target drift",
		"expected_behavior": "Submitted cards remain committed, targets are rechecked at resolution, and direct-player cards retain active state during a five-second counter window.",
		"current_owner": "CardResolutionExecutionRuntimeService + CardEconomyProductRouteEffectRuntimeService + CardEconomyProductRouteFormulaRuntimeService + existing Queue/Timing/Inventory/Hand Interaction and concrete world owners",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["CardResolutionExecutionRuntimeCharacterizationBench passes its active card-resolution evidence", "Execution Service orders active release before effect dispatch", "Economy/product/route handlers and deterministic formulas use separate narrow services", "Counter retains active during its own response window", "Public track and service debug strip hidden actor/private markers"],
		"cutover_action": "Execution cutover complete; keep concrete card families outside the orchestration service.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Market stabilization and regional economy formula characterization",
	},
	{
		"rule_id": "economy_product_route_card_effect_dispatch",
		"rulebook_section": "Economy cards / products / routes",
		"expected_behavior": "Economy, product, and route cards retain their existing formulas, target rules, durations, and privacy boundaries while using one modular dispatch owner.",
		"current_owner": "CardEconomyProductRouteEffectRuntimeService + CardEconomyProductRouteFormulaRuntimeService + stateless WorldBridge + existing concrete world-rule functions",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Focused dispatch test routes the active handlers exactly once", "Focused formula test preserves the current characterized formulas", "CardResolutionExecutionRuntimeCharacterizationBench carries 25 live characterization cases and 49 cutover cases", "main.gd execution adapter has no economy/product/route family branches or characterized pure arithmetic bodies"],
		"cutover_action": "Dispatch and two formula clusters are complete; continue one characterized formula cluster at a time.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Market stabilization and regional economy formula characterization",
	},
	{
		"rule_id": "economy_product_route_formula_ownership",
		"rulebook_section": "Product markets / contracts / city products and demands / futures / city GDP derivatives / trade routes",
		"expected_behavior": "Market and contract boons, city product/demand transformations, insurance, futures and GDP-derivative payouts, and route factors preserve exact caps, order, durations, units, direction and rounding while remaining independent of generic card execution.",
		"current_owner": "CardEconomyProductRouteFormulaRuntimeService; product price remains RuntimeBalanceModel; city GDP remains GdpFormulaRuntimeController",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Focused formula test covers the active characterized formulas", "Execution cutover Bench carries 74 active cases", "Automatic-order, city-product, demand, insurance, futures, derivative, and route arithmetic bodies are absent from main.gd", "Candidate RNG remains in main and Execution Service contains no formula names or dependencies"],
		"cutover_action": "Keep deterministic arithmetic pure and world mutation in existing adapters.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Characterize market stabilization and regional economy formulas",
	},
	{
		"rule_id": "city_development_product_binding",
		"rulebook_section": "City development / product project binding",
		"expected_behavior": "City development requires a product project rather than a free direct-build action.",
		"current_owner": "CityDevelopmentRuntimeController legality gate",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Controller validates district/product/direction/project identity", "Direct-build compatibility actions are rejected", "FirstMissionRuntimeMainBench resolves a real card-bound city-development request"],
		"cutover_action": "Keep v0.4 entry legality and direct-build rejection in CityDevelopmentRuntimeController.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Preserve this legality boundary after the Sprint 66 settlement cutover",
	},
	{
		"rule_id": "city_development_product_project_settlement",
		"rulebook_section": "City development / product contribution, urbanization share, and project GDP",
		"expected_behavior": "A real development card creates or strengthens one district/product/direction project, preserves private contribution shares, and exposes only anonymous public economic evidence.",
		"current_owner": "CityDevelopmentRuntimeController + non-owning CityDevelopmentWorldBridge + delegated Network/GDP/Market/project-share owners",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["CityDevelopmentSettlementRuntimeCharacterizationBench reports 64/64 observed and aligned", "Production, demand, and commerce share GameRuntimeCoordinator.execute_city_development", "WorldBridge protects post-claim stages with world/network/market/RNG rollback", "Public receipts omit contributor/controller/share data"],
		"cutover_action": "Keep the pure plan, fingerprint preflight, exact sequence claim, atomic commit, and exact-once event receipt as the only settlement route.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Select the next main.gd ownership family from the runtime replacement audit",
	},
	{
		"rule_id": "direct_city_build_legacy",
		"rulebook_section": "City development / prohibited direct build",
		"expected_behavior": "Direct city construction is not a legal v0.4 standalone action.",
		"current_owner": "CityDevelopmentRuntimeController compatibility gate",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["direct_city_build_allowed=false", "PlayerBoard no longer emits build actions", "keyboard/coach/legacy requests return the v0.4 disabled reason without settlement"],
		"cutover_action": "Keep the rejection shim for old action ids and saves; do not expose a player-executable direct-build surface.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Compatibility shim removal only with a future save-version migration",
	},
	{
		"rule_id": "district_purchase_12_second_window",
		"rulebook_section": "District purchase / 12-second qualification",
		"expected_behavior": "District purchase eligibility remains open for 12 seconds.",
		"current_owner": "RulesetRuntimeBridge + DistrictPurchaseRuntimeController + DistrictPurchaseSettlementRuntimeService + CardInventoryRuntimeService",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Profile declares 12 seconds, ordinary_hand_limit=5, and maximum_card_rank=4", "DistrictPurchaseRuntimeController remains the sole countdown, expiry, switch/close invalidation, locked access, private channel discount, pending-discard window, and legacy save authority", "CardInventoryRuntimeService owns family/rank, hand-limit, discardability, fingerprint, and slot mutation", "DistrictPurchaseSettlementRuntimeService delegates inventory while retaining atomic cash/counter/private-ledger commits", "DistrictSupplySnapshotService formats viewer-safe facts without timing or settlement authority", "DistrictPurchaseRuntimeCutoverBench passes 80/80 and CardInventoryRuntimeCharacterizationBench passes 40/40"],
		"cutover_action": "Keep qualification and locked context in the controller, slot mutation in CardInventoryRuntimeService, atomic purchase finance in the settlement service, and presentation in the snapshot/drawer owners.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Select the next characterized main.gd transaction boundary",
	},
	{
		"rule_id": "forced_decision_scheduler",
		"rulebook_section": "Forced decisions / priority order",
		"expected_behavior": "Forced decisions resolve in monster wager, counter response, contract response, then other-choice priority.",
		"current_owner": "GameRuntimeCoordinator / ForcedDecisionRuntimeScheduler",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Profile supplies ordered priority", "main.tscn owns the sceneized scheduler", "Overlay, countdown, player hints, and card progress read one arbitration result"],
		"cutover_action": "Keep rule effects in existing domain handlers while the scheduler remains the only priority and blocking authority.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Game Session State & Save Ownership",
	},
	{
		"rule_id": "ai_policy_runtime_ownership",
		"rulebook_section": "Automated opponents / privacy and action legality",
		"expected_behavior": "AI uses the same legal world actions as players while its private plan, targets, and ownership knowledge remain hidden.",
		"current_owner": "AiRuntimeController + AiRuntimeWorldBridge + AI Policy Resource",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["AI Policy Resource runtime cutover enabled", "AiPolicyResourceBench passes 44/44", "main.gd AI candidate and scoring algorithms absent", "FirstMission runtime remains 37/37 after balance and pacing instrumentation"],
		"cutover_action": "Keep Controller as the only AI decision owner and route world effects through existing mutation owners.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Card Presentation / ViewModel Hard Cutover",
	},
	{
		"rule_id": "private_plan_slot",
		"rulebook_section": "Private plan",
		"expected_behavior": "Each player has a private plan slot with strict owner-only visibility.",
		"current_owner": "Not implemented",
		"current_status": STATUS_MISSING,
		"runtime_evidence": ["private_plan_enabled=true", "No runtime private plan owner exists"],
		"cutover_action": "Add a privacy-first data owner and UI snapshot boundary.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Private Plan Runtime Sprint",
	},
	{
		"rule_id": "monster_runtime_lifecycle",
		"rulebook_section": "14. Monster rules",
		"expected_behavior": "Monsters summon with hidden binding, choose targets autonomously from public world pressure, move over real time, attack and damage, upgrade/refresh, and leave when lifetime expires.",
		"current_owner": "MonsterRuntimeController + narrow MonsterRuntimeWorldBridge",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["MonsterRuntimeCharacterizationBench passes 50/50", "Original 37 behavior cases remain aligned", "Shared RNG gateway sequence and legacy save keys are preserved", "main.gd monster state and algorithms are absent", "Public debug and map marker exclude unrevealed owner"],
		"cutover_action": "Keep roster, lifecycle, target/RNG, movement, combat, wager, and save ownership in the single scene controller.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Monster content and encounter tuning behind the 50-case gate",
	},
	{
		"rule_id": "military_runtime_lifecycle",
		"rulebook_section": "16. Military rules",
		"expected_behavior": "A player normally controls one commanded military unit; movement is realtime and non-destructive, while explicit commands may guard, strike districts/routes, pressure GDP, or attack monsters without revealing the controller.",
		"current_owner": "MilitaryRuntimeController + non-owning MilitaryRuntimeWorldBridge + AiRuntimeController intent selection + CardInventoryRuntimeService command slots + MonsterRuntimeController damage target",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["MilitaryRuntimeCharacterizationBench passes 50/50", "Seven real I-IV families exist", "Movement has no implicit damage", "Explicit strikes route through MilitaryRuntimeController and monster damage through MonsterRuntimeController", "Current and legacy save keys and public privacy are preserved", "Legacy main.gd military state and algorithms are absent"],
		"cutover_action": "Sprint 47 completed the single-owner cutover without widening AI, Inventory, Monster, Queue, or Execution owners.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Protect the 50-case gate and select the next large main.gd runtime family",
	},
	{
		"rule_id": "weather_runtime_lifecycle",
		"rulebook_section": "19. Weather and news / public forecast",
		"expected_behavior": "Weather is forecast publicly 1-3 minutes ahead, affects a small district set, continues with realtime planet simulation, and keeps a public warning when modified by a player.",
		"current_owner": "WeatherRuntimeController state/lifecycle/multipliers/save + WeatherRuntimeWorldBridge shared RNG/world routing + AiRuntimeController intent selection + sceneized public presentation",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["WeatherRuntimeCharacterizationBench passes 53/53", "Four production weather types and eight authored weather cards use one Controller route", "Shared RNG, neighbor-first zones, overlapping multipliers, monster-wager freeze, v1 save defaults, AI binding and main deletion are gated", "EnvironmentBalanceModel remains QA-only"],
		"cutover_action": "Keep WeatherRuntimeController authoritative; characterize optional monster-movement or financial-risk weather effects before adding them.",
		"deletion_candidates": [],
		"risk": "high",
		"next_sprint": "Protect the 53-case gate and select the next large main.gd runtime family",
	},
	{
		"rule_id": "monster_wager_timing",
		"rulebook_section": "Monster wager / decision timing",
		"expected_behavior": "Every wager uses one 15-second mandatory decision window; all ready players may close it early.",
		"current_owner": "MonsterRuntimeController + MonsterWagerSettlementPolicyV06",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Profile default and maximum are both 15", "MonsterRuntimeController owns one decision clock", "Settlement policy validates the 15-second contract", "Owner cutover verifies early close, no-damage refund, doubled pool, and multiplayer payout"],
		"cutover_action": "Keep the decision clock and settlement lifecycle controller-owned.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Monster wager playtest tuning",
	},
	{
		"rule_id": "final_countdown_timing",
		"rulebook_section": "Endgame / final countdown",
		"expected_behavior": "The final countdown lasts 75 seconds.",
		"current_owner": "RulesetRuntimeBridge + main.gd endgame flow",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Profile final countdown 75", "main.gd reads bridge timing"],
		"cutover_action": "Keep all countdown display and progress calculations bridge-backed.",
		"deletion_candidates": ["main.gd duplicate 60-second countdown constant"],
		"risk": "medium",
		"next_sprint": "Endgame runtime playtest",
	},
	{
		"rule_id": "end_turn_legacy_surface",
		"rulebook_section": "Realtime flow / no legacy turn-ending surface",
		"expected_behavior": "Realtime v0.4 flow must not depend on a legacy End Turn control.",
		"current_owner": "GameScreen/main.gd compatibility signal surface",
		"current_status": STATUS_MISMATCH,
		"runtime_evidence": ["End-turn signal and hidden compatibility surface remain"],
		"cutover_action": "Remove the complete legacy surface only after realtime progression owns all transitions.",
		"deletion_candidates": ["legacy end_turn_requested routing", "hidden EndTurn compatibility control"],
		"risk": "high",
		"next_sprint": "Realtime Flow Surface Cutover",
	},
	{
		"rule_id": "product_market_futures_runtime_lifecycle",
		"rulebook_section": "20. Financial, futures, and warehousing / realtime product market",
		"expected_behavior": "Product prices come from real supply, demand, transport, contracts, weather, monsters, and construction; positions lock the selected underlying, reference, duration, direction, multiplier, and private settlement owner.",
		"current_owner": "ProductMarketRuntimeController lifecycle + ProductMarketRuntimeWorldBridge facts/mutations + CardEconomyProductRouteFormulaRuntimeService arithmetic + EconomyCashflowRuntimeController cadence + GdpFormulaRuntimeController city formula",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Sprint 55 preserves the original Product Market 50/50 gate", "ProductMarketRuntimeController is the sole state/lifecycle/save owner", "The live terms gate is 76/76 aligned and the 24 historical records remain intact"],
		"cutover_action": "Keep ProductMarketRuntimeController authoritative and the Inspector catalog as the single financial terms source.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Financial Content Expansion",
	},
	{
		"rule_id": "city_gdp_derivative_margin_and_caps",
		"rulebook_section": "20. Financial, futures, and warehousing / city GDP derivatives",
		"expected_behavior": "City GDP longs, shorts, and disaster insurance declare margin, locked GDP reference, duration, direction, multiplier, maximum gain/loss, and destruction settlement while keeping owners private.",
		"current_owner": "CityGdpDerivativeTermsCatalogResource + CityGdpDerivativeRuntimeController + CardEconomyProductRouteFormulaRuntimeService",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Twelve Inspector Resources validate as one catalog", "Queue authorizes margin without locking it", "Effect open atomically locks margin and GDP reference", "expiry and city destruction settle two-way capped P&L exact-once", "legacy saves normalize without retroactive margin", "public snapshots contain no owner"],
		"cutover_action": "Keep Controller positions separate from city dictionaries and retain the catalog as the single terms source.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Financial Content Expansion",
	},
	{
		"rule_id": "product_futures_margin_and_caps",
		"rulebook_section": "20. Financial, futures, and warehousing / margin and gain-loss envelope",
		"expected_behavior": "Every financial card declares margin or action fee, reference value, duration, direction, multiplier, maximum gain, maximum loss, and special settlement.",
		"current_owner": "ProductFuturesTermsCatalogResource + ProductMarketRuntimeController + CardEconomyProductRouteFormulaRuntimeService",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Twelve Inspector Resources validate as one catalog", "action_fee_cash is zero while margin and caps are explicit", "Queue authorizes but does not lock margin", "Controller locks margin at open and settles capped gain/loss exactly once", "AI and Presentation read the same terms snapshot"],
		"cutover_action": "Keep all financial consumers on the catalog snapshot; do not reintroduce card-definition copies.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Financial Content Expansion",
	},
	{
		"rule_id": "warehouse_destruction_settlement",
		"rulebook_section": "20. Financial, futures, and warehousing / destroyed warehouse loss",
		"expected_behavior": "Destroyed warehouse exposure settles from authored card terms and an explicit remaining-HP snapshot without exposing the position owner.",
		"current_owner": "main.gd district damage adapter + ProductMarketRuntimeController warehouse-position lifecycle",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["main passes max_hp, pre_hit_hp, and post_hit_hp only after destruction", "Controller computes maximum_loss * (1 - post_hit_hp / max_hp)", "partial damage updates risk without early settlement", "destruction settlement and position removal are exact-once"],
		"cutover_action": "Preserve the pure HP receipt and keep owner/cash fields out of public snapshots.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Financial Content Expansion",
	},
	{
		"rule_id": "runtime_card_catalog_source_of_truth",
		"rulebook_section": "Cards / catalog identity, requirements, targets, duration, and upgrade gradient",
		"expected_behavior": "All gameplay card definitions, family/rank progression, common-pool order, and consumer snapshots come from one Inspector-editable runtime catalog while external financial terms retain their dedicated owners.",
		"current_owner": "CardRuntimeCatalogService + card_runtime_catalog_v04.tres",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Sprint 58 passes 80/80", "Sprint 59 authoring workflow passes 36/36", "232 active authored definitions match locked canonical hashes", "114 families and 70 upgradeable families", "118 ordered public-pool entries", "49 effect kinds validate", "custom Inspector validation and user:// change review are available", "Coordinator statically composes Catalog Service and DefinitionWorldBridge", "main.gd legacy constants and helpers are absent"],
		"cutover_action": "Keep the Resource catalog as the only static card-definition source; require the Inspector validator and change-review workflow for authored changes; retain dedicated Product Futures, City GDP, and Monster dynamic-definition owners.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Authored Card Content Expansion",
	},
	{
		"rule_id": "gameplay_balance_diagnostics_ownership",
		"rulebook_section": "Development routes / public balance evidence / developer diagnostics",
		"expected_behavior": "Development-route metadata and read-only balance reports use one Inspector-editable catalog and one pure-data diagnostics service without changing gameplay formulas or exposing private state.",
		"current_owner": "GameplayBalanceDiagnosticsRuntimeService + GameplayBalanceDiagnosticsWorldBridge + DevelopmentRouteCatalogResource",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["Seven v0.4 route Resources validate", "GameRuntimeCoordinator statically composes Service and WorldBridge", "RuntimeBalanceModel remains formula owner", "BalanceRuntimeBridgeBench covers at least 32 diagnostics cutover cases", "main.gd legacy diagnostics functions are absent"],
		"cutover_action": "Keep reports read-only and pure data; extend world facts through the bridge and formulas through RuntimeBalanceModel rather than main.gd.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "City / Trade Network Characterization",
	},
	{
		"rule_id": "city_trade_network_runtime_ownership",
		"rulebook_section": "City product projects / trade network / realtime GDP shares",
		"expected_behavior": "Concrete product projects create hidden shares and public GDP; real supply-demand routes refresh before project GDP allocation and realtime project-share payouts.",
		"current_owner": "CityTradeNetworkRuntimeController + non-owning CityTradeNetworkWorldBridge; delegated CityProductProjectState/Bridge, GdpFormulaRuntimeController, EconomyCashflowRuntimeController, and ProductMarketRuntimeController",
		"current_status": STATUS_CUTOVER_COMPLETE,
		"runtime_evidence": ["CityTradeNetworkRuntimeCharacterizationBench passes 68/68", "Project shares and player GDP preserve exact totals", "Refresh order remains competition, routes, GDP, project allocation, supply guarantee", "Public project/route snapshots hide controller and share tables", "main.gd route/path/refresh algorithms and project sequence are absent"],
		"cutover_action": "Keep CityTradeNetworkRuntimeController as the only derived network and payout-source orchestration owner; keep WorldBridge non-owning and preserve delegated formula/market/project owners.",
		"deletion_candidates": [],
		"risk": "medium",
		"next_sprint": "Next main.gd runtime ownership cutover",
	},
]


func statuses() -> Array[String]:
	return [STATUS_ALIGNED, STATUS_CUTOVER_COMPLETE, STATUS_MISMATCH, STATUS_MISSING, STATUS_BLOCKED]


func records() -> Array:
	return _duplicate_records(RECORDS)


func record_for_id(rule_id: String) -> Dictionary:
	for record_variant in RECORDS:
		var record: Dictionary = record_variant
		if str(record.get("rule_id", "")) == rule_id:
			return record.duplicate(true)
	return {}


func summary() -> Dictionary:
	var counts := {}
	for status in statuses():
		counts[status] = 0
	for record_variant in RECORDS:
		var record: Dictionary = record_variant
		var status := str(record.get("current_status", ""))
		counts[status] = int(counts.get(status, 0)) + 1
	return {
		"ruleset_id": "v0.4",
		"record_count": RECORDS.size(),
		"status_counts": counts,
		"records": records(),
	}


func _duplicate_records(source: Array) -> Array:
	var result: Array = []
	for record_variant in source:
		result.append((record_variant as Dictionary).duplicate(true))
	return result
