extends RefCounted
class_name SpaceSyndicateSceneizationAuditRegistry

const STATUS_FULL := "full"
const STATUS_PARTIAL := "partial"
const STATUS_LEGACY_RUNTIME := "legacy_runtime"
const STATUS_DRAW_SCRIPT := "draw_script"

const STATUS_ORDER := [
	STATUS_FULL,
	STATUS_PARTIAL,
	STATUS_LEGACY_RUNTIME,
	STATUS_DRAW_SCRIPT,
]

const RECORDS := [
	{
		"id": "main_runtime_composition_gate",
		"display_name": "Main Runtime Composition",
		"category": "Core Table",
		"current_scene_path": "res://scenes/main.tscn",
		"source_script_path": "res://scripts/main.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep GameScreen as a hard scene dependency and continue moving domain orchestration behind RuntimeServices.",
		"risk_notes": "Medium; main.gd still owns orchestration and rules, while scene ownership covers every player-facing runtime surface.",
		"mcp_notes": "Dump main.tscn before running it, then inspect _runtime_composition_snapshot for missing nodes, duplicate nodes, duplicate signals, or fallback use. LegacyRuntimeTable must remain absent.",
	},
	{
		"id": "game_screen_scene",
		"display_name": "GameScreen",
		"category": "Core Table",
		"current_scene_path": "res://scenes/ui/GameScreen.tscn",
		"source_script_path": "res://scripts/ui/game_screen.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep using GameScreen as the main editable table shell.",
		"risk_notes": "Low risk; this is already the split UI composition surface.",
		"mcp_notes": "Open this with MCP when checking top-level table regions.",
	},
	{
		"id": "top_bar_scene",
		"display_name": "TopBar",
		"category": "Core Table",
		"current_scene_path": "res://scenes/ui/TopBar.tscn",
		"source_script_path": "res://scripts/ui/top_bar.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep data-backed quick status chips and avoid rule reads.",
		"risk_notes": "Low risk.",
		"mcp_notes": "Use MCP scene_tree_dump for first-glance status layout.",
	},
	{
		"id": "planet_board_scene",
		"display_name": "PlanetBoard",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/ui/PlanetBoard.tscn",
		"source_script_path": "res://scripts/ui/planet_board.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Continue moving side-rail chips into smaller reusable row scenes.",
		"risk_notes": "Medium; it is the largest visible table surface.",
		"mcp_notes": "Open this to inspect the embedded PlanetMapView and rail composition.",
	},
	{
		"id": "planet_map_view_shell",
		"display_name": "PlanetMapView Shell",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/ui/PlanetMapView.tscn",
		"source_script_path": "res://scripts/ui/planet_map_view.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 2,
		"next_step": "Use this shell as the parent for editable map child components and projection-backed draw layers.",
		"risk_notes": "Low; the shell is stable, with markers moving into child scenes.",
		"mcp_notes": "MCP can open the editable layer hierarchy and child map components now.",
	},
	{
		"id": "player_board_scene",
		"display_name": "PlayerBoard",
		"category": "Player UI",
		"current_scene_path": "res://scenes/ui/PlayerBoard.tscn",
		"source_script_path": "res://scripts/ui/player_board.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep hand, bid, and action components routed through child scenes.",
		"risk_notes": "Medium because it owns the primary action surface.",
		"mcp_notes": "Use PlayerTurn previews before changing this scene.",
	},
	{
		"id": "hand_rack_scene",
		"display_name": "HandRack",
		"category": "Player UI",
		"current_scene_path": "res://scenes/ui/HandRack.tscn",
		"source_script_path": "res://scripts/ui/hand_rack.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep CardFace instances reusable and data-backed.",
		"risk_notes": "Medium because hover, selection, and drag states are central to feel.",
		"mcp_notes": "Use MCP runtime screenshots after card-feel changes.",
	},
	{
		"id": "card_face_scene",
		"display_name": "CardFace",
		"category": "Cards",
		"current_scene_path": "res://scenes/ui/CardFace.tscn",
		"source_script_path": "res://scripts/ui/card_face.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep presentation modes in data, not gameplay rules.",
		"risk_notes": "Low to medium; it is reused in many surfaces.",
		"mcp_notes": "Open this for card hierarchy and long-text QA.",
	},
	{
		"id": "right_inspector_scene",
		"display_name": "RightInspector",
		"category": "Inspector",
		"current_scene_path": "res://scenes/ui/RightInspector.tscn",
		"source_script_path": "res://scripts/ui/right_inspector.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Move repeated chip/card snippets into reusable sub-scenes when touched.",
		"risk_notes": "Medium; it must not leak private data.",
		"mcp_notes": "Use MCP to inspect public/private context after selection changes.",
	},
	{
		"id": "overlay_layer_scene",
		"display_name": "OverlayLayer",
		"category": "Overlay",
		"current_scene_path": "res://scenes/ui/OverlayLayer.tscn",
		"source_script_path": "res://scripts/ui/overlay_layer.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep fallback UI small while migrating any repeated modal rows.",
		"risk_notes": "Medium; modal routing must preserve action ids.",
		"mcp_notes": "Use temporary decision benches for overlay changes.",
	},
	{
		"id": "temporary_decision_panels",
		"display_name": "Temporary Decision Panels",
		"category": "Overlay",
		"current_scene_path": "res://scenes/ui/TemporaryChoiceDecisionPanel.tscn",
		"source_script_path": "res://scripts/ui/temporary_choice_decision_panel.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep using specialized or reusable decision scenes instead of main.gd widgets.",
		"risk_notes": "Low after capture and interaction benches.",
		"mcp_notes": "Open the preview/capture/interaction benches from the QA dock.",
	},
	{
		"id": "district_supply_drawer_scene",
		"display_name": "DistrictSupplyDrawer",
		"category": "Player UI",
		"current_scene_path": "res://scenes/ui/DistrictSupplyDrawer.tscn",
		"source_script_path": "res://scripts/ui/district_supply_drawer.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep Drawer rendering, repeated child scenes, focus, empty states, and aggregate UI actions scene-owned; do not restore main.gd child-node mirrors.",
		"risk_notes": "Medium; UI intents are scene-owned while purchase qualification and settlement remain separate authorities.",
		"mcp_notes": "Sprint 28 preserves the Sprint 27 formatting boundary and requires 45/45 ownership plus 17/17 settlement characterization observations.",
	},
	{
		"id": "district_supply_snapshot_service_gate",
		"display_name": "DistrictSupplySnapshotService",
		"category": "Runtime Services",
		"current_scene_path": "res://scenes/runtime/DistrictSupplySnapshotService.tscn",
		"source_script_path": "res://scripts/runtime/district_supply_snapshot_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep viewer-safe Drawer formatting here while eligibility, price, payment, inventory, upgrades, and private discard settlement remain in their existing rule owners.",
		"risk_notes": "Medium; source facts include current-viewer cash and counted hand size, so private hand names, owners, channel sources, and discard content must remain rejected.",
		"mcp_notes": "Require the 62-case DistrictPurchaseRuntimeCutoverBench, pure source/output, hexadecimal colors, no rule authority, real-main Coordinator routing, and nineteen retired main formatters.",
	},
	{
		"id": "planet_map_view_internal_draw",
		"display_name": "PlanetMapView Districts / Routes / Markers",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/ui/PlanetMapView.tscn",
		"source_script_path": "res://scripts/map_view.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Continue shrinking the remaining legacy region fill/label fallback after the sceneized render cutover proves stable.",
		"risk_notes": "High visual importance; set_map, focus_district, hit testing, and district signals are still owned by map_view.gd for compatibility.",
		"mcp_notes": "Backdrop, orbit guide, focus range, scale hint, district polygons, district labels, route segments, movement trails, event effects, action callouts, city markers, monster tokens, route chips, and selection rings are now sceneized child nodes. Remaining legacy draw-backed surfaces are region fill/label fallback.",
	},
	{
		"id": "planet_map_marker_components",
		"display_name": "PlanetMapView Marker Components",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/ui/map/PlanetDistrictNode.tscn",
		"source_script_path": "res://scripts/ui/map/planet_district_node.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Tune individual district, city, monster, route, and selection scenes in Godot while keeping projection math in MapView.",
		"risk_notes": "Medium; these components are visual wrappers around live map data and must not duplicate map rules.",
		"mcp_notes": "Open the child scenes directly from the Design QA dock or MCP registry when tuning marker hierarchy.",
	},
	{
		"id": "planet_map_geometry_components",
		"display_name": "PlanetMapView Geometry Components",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/ui/map/PlanetDistrictPolygon.tscn",
		"source_script_path": "res://scripts/ui/map/planet_district_polygon.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Tune PlanetDistrictPolygon and PlanetRouteSegment as the editable geometry layer before replacing the last legacy underlay drawing.",
		"risk_notes": "Medium; geometry still receives projected points from MapView and must not duplicate projection or rule logic.",
		"mcp_notes": "Open PlanetDistrictPolygon.tscn and PlanetRouteSegment.tscn to tune polygon fill and route-line styling from the editor.",
	},
	{
		"id": "planet_map_feedback_components",
		"display_name": "PlanetMapView Feedback Components",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/ui/map/PlanetMovementTrail.tscn",
		"source_script_path": "res://scripts/ui/map/planet_movement_trail.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Use PlanetMovementTrail, PlanetMapEventEffect, and PlanetActionCallout as the editable transient-feedback layer before removing more legacy draw helpers.",
		"risk_notes": "Medium; feedback nodes mirror live visual cue data and must not mutate gameplay state.",
		"mcp_notes": "Open the feedback child scenes directly from the Design QA dock or switch PlanetMapMcpPreview to Event Effects.",
	},
	{
		"id": "planet_map_underlay_components",
		"display_name": "PlanetMapView Underlay Components",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/ui/map/PlanetGlobeBackdrop.tscn",
		"source_script_path": "res://scripts/ui/map/planet_map_render_model.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Use PlanetGlobeBackdrop, PlanetOrbitGuide, and PlanetFocusRangeOverlay as the editable underlay before retiring more legacy _draw fallback.",
		"risk_notes": "Medium; these components mirror projection payloads and must not own district hit testing or gameplay rules.",
		"mcp_notes": "Open the underlay child scenes directly from the Design QA dock or switch PlanetMapMcpPreview to Underlay Guides.",
	},
	{
		"id": "planet_map_render_cutover_gate",
		"display_name": "PlanetMapView Render Cutover Gate",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/tools/PlanetMapRenderCutoverBench.tscn",
		"source_script_path": "res://scripts/ui/planet_map_view.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run the cutover bench after map surface edits and keep legacy _draw fallback explicit instead of default.",
		"risk_notes": "Medium; the cutover changes which layer is authoritative for visuals while preserving map hit testing and signals.",
		"mcp_notes": "Use PlanetMapRenderCutoverBench to verify sceneized_visual_cutover_enabled=true, legacy_draw_fallback_used=false, and scale_hint_sceneized=true.",
	},
	{
		"id": "planet_map_interaction_ownership_gate",
		"display_name": "Planet Map Interaction and Toolbar Ownership Gate",
		"category": "Main Surface",
		"current_scene_path": "res://scenes/tools/PlanetMapInteractionBench.tscn",
		"source_script_path": "res://scripts/ui/planet_map_view.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run the 15-case interaction bench after map surface or toolbar edits to prove district input, layer focus, trade selection, and contract endpoints remain scene-owned.",
		"risk_notes": "Medium; regressions can leave visuals correct while clicks target stale projections or toolbar actions bypass the pure-data bridge.",
		"mcp_notes": "Require 15/15: district signals, focus/projection sync, inactive legacy fallback, static toolbar composition, pure payloads, real-main routing, disabled endpoint guards, and retired builders/Node arrays.",
	},
	{
		"id": "card_resolution_track_sceneization_gate",
		"display_name": "Card Resolution Track Sceneization Gate",
		"category": "Cards",
		"current_scene_path": "res://scenes/ui/CardResolutionTrack.tscn",
		"source_script_path": "res://scripts/ui/card_resolution_track.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep CardResolutionTrack as the sole renderer and extend it only through scene-owned slots and snapshot data.",
		"risk_notes": "Medium; public track signals, anonymous ownership hints, and bid/action ids must remain compatible after the legacy renderer deletion.",
		"mcp_notes": "Use CardResolutionTrackMcpPreview and LegacyRuntimeSurfaceRetirementBench to check queue, active reveal, auction/response, history, overflow, privacy, and sole-renderer ownership.",
	},
	{
		"id": "card_resolution_track_interaction_ownership_gate",
		"display_name": "Card Resolution Track Interaction Ownership Gate",
		"category": "Cards",
		"current_scene_path": "res://scenes/tools/CardResolutionTrackInteractionBench.tscn",
		"source_script_path": "res://scripts/ui/card_resolution_track.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run this bench after changing card-resolution slots, response actions, public track compact mode, or card-resolution UI payloads.",
		"risk_notes": "Medium; this preserves slot selection, open, response action, disabled action, history, overflow, and privacy behavior while sceneizing the track.",
		"mcp_notes": "Use CardResolutionTrackInteractionBench to verify track_entry_selected, track_entry_opened, track_action_requested, disabled actions, and privacy sanitization.",
	},
	{
		"id": "runtime_card_resolution_track_flow_gate",
		"display_name": "Runtime Card Resolution Track Flow Gate",
		"category": "Cards",
		"current_scene_path": "res://scenes/tools/RuntimeCardResolutionTrackFlowBench.tscn",
		"source_script_path": "res://scripts/ui/game_screen.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run this bench after changing GameScreen, PublicTrack, CardResolutionTrack, or card-resolution UI payloads to prove the sceneized track is live in the real table.",
		"risk_notes": "Medium; this gate protects action ids, disabled actions, response windows, history read-only behavior, and privacy boundaries in the real GameScreen.",
		"mcp_notes": "Use RuntimeCardResolutionTrackFlowBench to verify CardResolutionTrack through GameScreen action_requested and RightInspector feedback.",
	},
	{
		"id": "card_resolution_runtime_controller_gate",
		"display_name": "Card Resolution Runtime Controller",
		"category": "Cards",
		"current_scene_path": "res://scenes/runtime/CardResolutionRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/card_resolution_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Timing and phase now have one authority in runtime and script-level tests; queue ownership remains the next separately gated sprint.",
		"risk_notes": "Medium; queue entries, cash, bid-chain settlement, card effects, and history mutation intentionally remain in main.gd and were not moved by consolidation.",
		"mcp_notes": "Query this node under RuntimeControllerHost and require controller_missing=false, controller_authoritative=true, and legacy_state_fallback_used=false.",
	},
	{
		"id": "compendium_codex_sceneization_gate",
		"display_name": "Compendium Codex Sceneization Gate",
		"category": "Cards",
		"current_scene_path": "res://scenes/tools/CompendiumCodexInteractionBench.tscn",
		"source_script_path": "res://scripts/ui/card_codex_browser.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Keep moving codex thumbnail, filter, fact, market, KPI, strategy, and monster action units into editable child scenes.",
		"risk_notes": "Medium; codex UI must carry long public reference material without leaking hidden owner, private target, or private discard data.",
		"mcp_notes": "Use CompendiumCodexMcpPreview and CompendiumCodexInteractionBench after changing CardCodex, ProductCodex, Bestiary, or CompendiumHub surfaces.",
	},
	{
		"id": "compendium_content_resourceization_gate",
		"display_name": "Compendium Content Resourceization Gate",
		"category": "Cards",
		"current_scene_path": "res://scenes/tools/CompendiumContentRegistryBench.tscn",
		"source_script_path": "res://scripts/content/compendium_content_registry.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Keep expanding batch Resource packs for real card, product, and monster reference content while gameplay rules stay on their existing data path.",
		"risk_notes": "Medium; content assets must stay public-safe, pure-data, and separate from action ids, rule callbacks, and settlement logic.",
		"mcp_notes": "Use CompendiumContentRegistryMcpPreview and CompendiumContentRegistryBench after editing resources/compendium .tres files or Resource schema scripts.",
	},
	{
		"id": "first_round_runtime_playable_loop_gate",
		"display_name": "First Round Runtime Playable Loop Gate",
		"category": "Main",
		"current_scene_path": "res://scenes/tools/FirstRoundRuntimePlayableLoopBench.tscn",
		"source_script_path": "res://scripts/ui/game_screen.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run this bench after touching GameScreen, PlayerBoard, CardResolutionTrack, PlanetMapView, OverlayLayer, or first-round UI payloads.",
		"risk_notes": "High; this gate protects the first playable round across hand selection, card actions, public track, planet map, temporary decision overlay, turn advance, and privacy.",
		"mcp_notes": "Use FirstRoundRuntimePlayableLoopBench to verify the first-round playable loop through the real GameScreen surface.",
	},
	{
		"id": "first_mission_runtime_productization_gate",
		"display_name": "First Mission Runtime Productization Gate",
		"category": "Main",
		"current_scene_path": "res://scenes/tools/FirstMissionRuntimeMainBench.tscn",
		"source_script_path": "res://scripts/main.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run this bench after touching main menu, first_table, FirstRunCoach, ScenarioCoach, GameScreen, or first-mission action routing.",
		"risk_notes": "High; this gate proves the first mission launches from the real main scene and survives the first guided action loop.",
		"mcp_notes": "Use FirstMissionRuntimeMainBench to verify main.tscn -> first_table -> GameScreen through the project-internal Godot MCP addon.",
	},
	{
		"id": "system_resourceization_audit_gate",
		"display_name": "System Resourceization Audit Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/SystemResourceizationAuditBench.tscn",
		"source_script_path": "res://scripts/tools/system_resourceization_audit_registry.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run this audit before extracting menu controllers, balance parameters, or AI policies into Godot Resources.",
		"risk_notes": "Medium; it is an audit-only tool and should not mutate gameplay state.",
		"mcp_notes": "Use SystemResourceizationAuditMcpPreview and SystemResourceizationAuditBench to inspect menu, Balance/Gradient, AI, and runtime fallback ownership.",
	},
	{
		"id": "balance_parameter_resourceization_candidate",
		"display_name": "Balance Parameter Resourceization Candidate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/SystemResourceizationAuditMcpPreview.tscn",
		"source_script_path": "res://scripts/balance/runtime_balance_model.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Use the controlled Balance Runtime Bridge before any Resource-backed cutover, while leaving formulas intact.",
		"risk_notes": "High; balance formulas affect economy, payouts, combat pressure, and first-mission pacing.",
		"mcp_notes": "Treat existing scripts and data/balance JSON as source inputs; Resourceization should first wrap tunable parameters.",
	},
	{
		"id": "balance_parameter_resourceization_gate",
		"display_name": "Balance Parameter Resourceization Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/BalanceParameterResourceBench.tscn",
		"source_script_path": "res://scripts/balance/balance_parameter_resource_registry.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run this bench after editing resources/balance .tres profiles, then run BalanceRuntimeBridgeBench before changing runtime source modes.",
		"risk_notes": "High; parameter changes can affect economy, card prices, combat pressure, movement pacing, and first-mission progression once wired into runtime.",
		"mcp_notes": "Use BalanceParameterResourceMcpPreview and BalanceParameterResourceBench to keep Inspector Resources aligned with current JSON and formula-script ownership.",
	},
	{
		"id": "balance_model_resource_sandbox_gate",
		"display_name": "Balance Model Resource Sandbox Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/BalanceModelResourceSandboxBench.tscn",
		"source_script_path": "res://scripts/balance/balance_parameter_model_adapter.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Run this sandbox before any runtime bridge starts reading Inspector Resource payloads for balance models.",
		"risk_notes": "High; this gate compares existing script-owned formulas, Resource payloads, and JSON anchors without changing settlement behavior.",
		"mcp_notes": "Use BalanceModelResourceSandboxBench through the project-internal Godot MCP addon after balance Resource or JSON edits.",
	},
	{
		"id": "balance_runtime_bridge_gate",
		"display_name": "Balance Runtime Bridge Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/BalanceRuntimeBridgeBench.tscn",
		"source_script_path": "res://scripts/balance/balance_runtime_parameter_bridge.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Keep json_current as the default runtime source until this gate and first-mission runtime QA are green under any proposed Resource cutover.",
		"risk_notes": "High; this bridge is the controlled boundary before Resource-backed balance parameters can affect real gameplay.",
		"mcp_notes": "Use BalanceRuntimeBridgeMcpPreview and the extended Gameplay Balance Diagnostics Bench through the project-internal Godot MCP addon.",
	},
	{
		"id": "gameplay_balance_diagnostics_gate",
		"display_name": "Gameplay Balance Diagnostics Ownership Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/GameplayBalanceDiagnosticsRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/gameplay_balance_diagnostics_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep RuntimeBalanceModel as formula owner and use this read-only service for route metadata, budgets, ecosystem audits, and developer snapshots.",
		"risk_notes": "Medium; reports are pure data and read-only, but their world-fact parity and privacy boundary must stay covered by BalanceRuntimeBridgeBench.",
		"mcp_notes": "Open the Service, WorldBridge, and seven route Resources in Godot; run the existing BalanceRuntimeBridgeBench after any diagnostics change.",
	},
	{
		"id": "ruleset_v04_runtime_source_gate",
		"display_name": "Ruleset v0.4 Runtime Source Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/RulesetV04ConformanceBench.tscn",
		"source_script_path": "res://scripts/runtime/ruleset_runtime_bridge.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "City development and forced-decision priority are cut over; continue replacing main.gd state ownership without reintroducing duplicate rule sources.",
		"risk_notes": "High; stable v0.4 parameters now have one runtime source, while rule algorithms and known mismatches remain deliberately untouched.",
		"mcp_notes": "Open RulesetRuntimeBridge in main.tscn and run RulesetV04ConformanceBench after any ruleset profile change.",
	},
	{
		"id": "ruleset_v05_foundation_gate",
		"display_name": "Ruleset v0.5 Foundation Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/RulesetV05FoundationBench.tscn",
		"source_script_path": "res://scripts/tools/ruleset_v05_foundation_bench.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Keep the 56-case foundation gate green while SS05-03 consumes the completed project-identity owner for structured GDP rows.",
		"risk_notes": "High; the v0.5 data layer is ready but deliberately runtime-inactive, and production must remain v0.4 during this sprint.",
		"mcp_notes": "Open the v0.5 Profile, product industry catalog, passive save handshake, and Foundation Bench. A runtime selector or fallback is a failure.",
	},
	{
		"id": "player_text_v05_foundation_gate",
		"display_name": "Player-Facing Text v0.5 Foundation Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/PlayerTextV05FoundationBench.tscn",
		"source_script_path": "res://scripts/tools/player_text_v05_foundation_bench.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Keep shared locale resolution runtime-inactive; migrate each domain's player-visible copy only from authorized receipts with stable visibility scopes.",
		"risk_notes": "High; localization must never become an authorization layer, and the 239 legacy card texts remain blocked until their v0.5 semantics are reviewed.",
		"mcp_notes": "Open the PlayerText schema, unit catalog, migration registry, zh_Hans PO, and 48-case bench. Production v0.4 UI must not consume this foundation yet.",
	},
	{
		"id": "city_development_runtime_cutover_gate",
		"display_name": "City Development Runtime Cutover Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CityDevelopmentRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/city_development_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep direct-build compatibility requests rejected and prove all new city surfaces through real development cards and product projects.",
		"risk_notes": "High; legality moved to a scene-owned controller while GDP, cashflow, prices, shares, and settlement remain in existing rule functions.",
		"mcp_notes": "Inspect the controller under main.tscn/RuntimeServices/RuntimeControllerHost and run RulesetV04ConformanceBench plus FirstMissionRuntimeMainBench.",
	},
	{
		"id": "main_runtime_replacement_foundation_gate",
		"display_name": "Main Runtime Replacement Foundation",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/GameRuntimeCoordinator.tscn",
		"source_script_path": "res://scripts/runtime/game_runtime_coordinator.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Keep main.gd frozen and next extract either economy runtime ownership or scenario runtime glue after district purchase ownership remains green.",
		"risk_notes": "High; the coordinator must stay thin and must never become a second monolithic main script.",
		"mcp_notes": "Inspect GameRuntimeCoordinator under main.tscn/RuntimeServices/RuntimeControllerHost and verify its snapshot remains pure data.",
	},
	{
		"id": "game_session_runtime_ownership_gate",
		"display_name": "Game Session Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/GameSessionRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/game_session_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep session identity and lifecycle here while domain state moves one owner at a time out of main.gd.",
		"risk_notes": "Medium; the controller owns lifecycle metadata only and must never retain a duplicate players/districts/economy payload.",
		"mcp_notes": "Run GameSessionSaveOwnershipBench after changes to new game, pause/resume, save state, or coordinator composition.",
	},
	{
		"id": "game_save_runtime_ownership_gate",
		"display_name": "Game Save Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/GameSaveRuntimeCoordinator.tscn",
		"source_script_path": "res://scripts/runtime/game_save_runtime_coordinator.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Preserve v1 Variant-binary compatibility while replacing each main.gd domain save adapter with controller-owned sections.",
		"risk_notes": "High; version, default path, normalization, and file I/O now have one owner, while main retains temporary domain collect/apply adapters.",
		"mcp_notes": "Use only QA paths under user://space_syndicate_design_qa/game_session_save_ownership/ during validation.",
	},
	{
		"id": "district_purchase_runtime_ownership_gate",
		"display_name": "District Purchase Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/DistrictPurchaseRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/district_purchase_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep qualification in DistrictPurchaseRuntimeController, atomic settlement in DistrictPurchaseSettlementRuntimeService, formatting in DistrictSupplySnapshotService, and presentation in DistrictSupplyDrawer.",
		"risk_notes": "High; monster source identity and bound-channel pricing are private, while supply inventory is never reserved by the window.",
		"mcp_notes": "Require the full 80/80 gate: 45 ownership, 17 observed/aligned characterization, and 18 settlement-service cutover cases.",
	},
	{
		"id": "district_purchase_settlement_characterization_gate",
		"display_name": "District Purchase Settlement Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/DistrictPurchaseSettlementRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/district_purchase_settlement_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Preserve the single service transaction path while moving future world-fact and post-commit hook owners out of main.gd in closed, characterized slices.",
		"risk_notes": "High; cash, hand slots, upgrades, private discard, ledgers, scenario hooks, role bonuses, and bankruptcy checks must commit atomically.",
		"mcp_notes": "Sprint 29 requires 45/45 ownership, 17/17 observed, 17/17 aligned, 18/18 service cutover, pure manifests, and zero private identifiers.",
	},
	{
		"id": "card_inventory_runtime_characterization_gate",
		"display_name": "Card Inventory Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CardInventoryRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/card_inventory_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep inventory slot mutation single-owned here; move future card-effect sequencing only after characterization without returning mutation formulas to main.gd.",
		"risk_notes": "High; steal failure intentionally converts to removal plus compensation, while fixed skills bypass the ordinary count and purchase settlement must remain atomic.",
		"mcp_notes": "Sprint 31 requires 20/20 observed, 20/20 aligned, 20/20 cutover, anonymous pure-data fingerprints, and no inventory formula in Settlement Service or main.gd.",
	},
	{
		"id": "player_hand_interaction_characterization_gate",
		"display_name": "Player Hand Interaction Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/PlayerHandInteractionRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/player_hand_interaction_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep higher-level interaction ordering, penalties, compensation, and event intents single-owned here while CardInventoryRuntimeService remains the only slot-mutation owner.",
		"risk_notes": "High; remove/transfer order, partial success, one-time compensation, exact private ledgers, public anonymity, queue dispatch, and AI parity must move together.",
		"mcp_notes": "Sprint 33 passes 20/20 observed, 20/20 aligned, and 20/20 cutover. main.gd retains only real facts, seeded RNG selection, and event forwarding.",
	},
	{
		"id": "card_resolution_queue_characterization_gate",
		"display_name": "Card Resolution Queue Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CardResolutionQueueRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/card_resolution_queue_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep queue lifecycle single-owned in CardResolutionQueueRuntimeService while timing stays in CardResolutionRuntimeController and card effects stay outside the queue owner.",
		"risk_notes": "High; enqueue commitment, hand/cash ordering, bid-chain settlement, active pop, next-batch promotion, save compatibility, and public privacy must not split across two authorities.",
		"mcp_notes": "Sprint 35 passes a 56-case gate: 28/28 preserved characterization plus 28/28 service cutover. main.gd retains stateless compatibility access and world/event adapters only.",
	},
	{
		"id": "card_resolution_execution_characterization_gate",
		"display_name": "Card Resolution Execution Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CardResolutionExecutionRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/card_resolution_execution_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep lifecycle orchestration single-owned here while concrete effect families are modularized independently behind the existing world-adapter boundary.",
		"risk_notes": "Very high; active clear, target drift, effect dispatch, counter/contract continuation, ledgers, public/private events, scenario hooks, history, and next-start ordering must remain atomic and privacy-safe.",
		"mcp_notes": "The gate is 80/80 in Sprint 40. Execution Service stays family- and formula-agnostic while sibling services own effect dispatch and nineteen pure operations.",
	},
	{
		"id": "card_economy_product_route_effect_family_gate",
		"display_name": "Economy / Product / Route Card Effect Family",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CardEconomyProductRouteEffectRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/card_economy_product_route_effect_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep seventeen handler plans here while future pure arithmetic moves through the sibling Formula Service; do not add lifecycle or queue state.",
		"risk_notes": "High; cash, market pressure, futures, GDP derivatives, contracts, product lines, and route pressure must retain exact mutation, duration, privacy, and continuation semantics.",
		"mcp_notes": "Sprint 40 preserves seventeen handler plans and result envelopes. The adjacent WorldBridge commits world state, while nineteen deterministic operations live in the separate pure Formula Service.",
	},
	{
		"id": "card_economy_product_route_formula_gate",
		"display_name": "Economy / Product / Route Pure Formula Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CardEconomyProductRouteFormulaRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/card_economy_product_route_formula_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Characterize market stabilization, regional economy shifts, and route sabotage before moving another formula cluster; keep established price/GDP owners and Execution Service formula-agnostic.",
		"risk_notes": "High; seconds/legacy-turn mirrors, payout units, rounding, product-slot order, RNG candidate order, multiplier caps, source labels, and public/private event ordering must remain exact.",
		"mcp_notes": "Sprint 40 expands the service to nineteen deterministic formulas, including contract boons, city product upgrade/shift, demand shift, route insurance, and shared city adjustment. The real-main gate passes 80/80.",
	},
	{
		"id": "economy_cashflow_runtime_ownership_gate",
		"display_name": "Economy Cashflow Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/EconomyCashflowRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/economy_cashflow_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep formula arithmetic in GdpFormulaRuntimeController and project-share, cash, and ledger mutation in their current owners while all realtime cadence and payout planning use this controller.",
		"risk_notes": "High; the controller plans pure payout events, while the main compatibility adapter remains the sole domain-state mutator.",
		"mcp_notes": "Run EconomyCashflowRuntimeCutoverBench after changing cadence, pause/block behavior, fractional remainders, city/project payout application, save compatibility, or coordinator composition.",
	},
	{
		"id": "gdp_formula_runtime_ownership_gate",
		"display_name": "GDP Formula Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/GdpFormulaRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/gdp_formula_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the 40-case structured GDP gate green while SS05-04 consumes the same project/player/neutral receipts for qualification and victory control.",
		"risk_notes": "High; exact rounding, pressure allocation, project/player/neutral conservation, stable receipt identity, and zero-GDP semantics affect realtime payout and future victory consumers.",
		"mcp_notes": "SS05-03 is cutover complete. Run GdpFormulaRuntimeCutoverBench after changing the v0.5 Profile, product-industry catalog, row schema, pressure allocation, attribution, privacy, or Coordinator composition.",
	},
	{
		"id": "scenario_runtime_glue_ownership_gate",
		"display_name": "Scenario Runtime Glue Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/ScenarioRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/scenario_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep Campaign reward execution and concrete gameplay actions in their existing owners while scenario progress uses this controller and first_table content interpretation uses FirstTableAuthoredRuntimeService.",
		"risk_notes": "High; signal ordering, log privacy, replay keys, and the deliberate v1 non-persistence boundary must remain stable.",
		"mcp_notes": "Run ScenarioRuntimeGlueCutoverBench after changing scenario catalog, progress, coach, replay, action-log, Campaign completion, or coordinator composition.",
	},
	{
		"id": "first_table_authored_runtime_ownership_gate",
		"display_name": "First Table Authored Runtime Ownership",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/FirstTableAuthoredRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/first_table_authored_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Move concrete first_table card-supply and AI-action orchestration only when their domain runtime controllers can own mutation; keep this service pure and authored-content only.",
		"risk_notes": "Medium; content ids, coach context, public clue privacy, and recommendation weights are centralized, while rule eligibility and world mutation remain authoritative elsewhere.",
		"mcp_notes": "Run FirstTableAuthoredRuntimeCutoverBench and FirstMissionRuntimeMainBench after changing first_table.json, runtime catalogs, authored copy, district recommendations, or coordinator composition.",
	},
	{
		"id": "forced_decision_runtime_scheduler_gate",
		"display_name": "Forced Decision Runtime Scheduler",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/ForcedDecisionRuntimeSchedulerBench.tscn",
		"source_script_path": "res://scripts/runtime/forced_decision_runtime_scheduler.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep wager, counter, contract, target, and discard effects in their domain handlers while all priority and blocking reads use this scheduler.",
		"risk_notes": "Medium; ordering and privacy are centralized, but underlying decision state remains with existing systems by design.",
		"mcp_notes": "Run ForcedDecisionRuntimeSchedulerBench after changing priority, blocking flags, Overlay routing, or card-response timing.",
	},
	{
		"id": "ai_policy_resourceization_candidate",
		"display_name": "AI Runtime Controller",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/AiRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/ai_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep AI decision ownership here and split internal strategy families only after the hard-cutover gate remains green.",
		"risk_notes": "High; AI action choice touches action ids, privacy, temporary decisions, shared RNG order, and monster flow.",
		"mcp_notes": "Open AiRuntimeController and its Policy Resource through the project-internal Godot MCP addon; main.gd must not regain candidate or scoring functions.",
	},
	{
		"id": "ai_policy_resourceization_gate",
		"display_name": "AI Policy Resourceization Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/AiPolicyResourceBench.tscn",
		"source_script_path": "res://scripts/ai/ai_policy_resource_registry.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the 44-case runtime cutover gate green after AI Policy, Controller, WorldBridge, or world adapter changes.",
		"risk_notes": "High; this gate guards action choice, auction behavior, shared RNG, privacy, first-mission pacing, and legacy-owner deletion.",
		"mcp_notes": "Run AiPolicyResourceBench through the project-internal Godot MCP addon after any AI .tres, Controller, WorldBridge, or main AI adapter change.",
	},
	{
		"id": "main_menu_controller_resourceization_candidate",
		"display_name": "Main Menu Controller Resourceization Candidate",
		"category": "Systems",
		"current_scene_path": "res://scenes/ui/MenuRootLobby.tscn",
		"source_script_path": "res://scripts/main.gd::_show_menu",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 2,
		"next_step": "Move menu routing and snapshots into an editor-visible controller only after runtime first-mission entry stays green.",
		"risk_notes": "Medium; menu routing owns the first playable entry path.",
		"mcp_notes": "Open MenuRootLobby and run FirstMissionRuntimeMainBench after any menu controller change.",
	},
	{
		"id": "public_card_track_slots",
		"display_name": "PublicTrack / CardTrack Slots",
		"category": "Cards",
		"current_scene_path": "res://scenes/ui/CardTrack.tscn",
		"source_script_path": "res://scripts/ui/card_track.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Move the repeated public track slot tree into CardTrackSlot.tscn.",
		"risk_notes": "Medium; preserve track_entry signals and public anonymity hints.",
		"mcp_notes": "This sprint converts the slot-level UI into an editable scene.",
	},
	{
		"id": "visual_event_layer_draw",
		"display_name": "VisualEventLayer Effects",
		"category": "Effects",
		"current_scene_path": "res://scenes/ui/VisualEventLayer.tscn",
		"source_script_path": "res://scripts/ui/visual_event_layer.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 3,
		"next_step": "Move repeated event callout shapes into reusable effect nodes.",
		"risk_notes": "Low gameplay risk, medium visual QA risk.",
		"mcp_notes": "Open with MCP after visual event changes to catch overlap.",
	},
	{
		"id": "targeting_overlay_draw",
		"display_name": "TargetingOverlay Hints",
		"category": "Effects",
		"current_scene_path": "res://scenes/ui/TargetingOverlay.tscn",
		"source_script_path": "res://scripts/ui/targeting_overlay.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 3,
		"next_step": "Promote target rings and invalid-drop hints into editable child nodes.",
		"risk_notes": "Medium; target feedback must stay synced with input.",
		"mcp_notes": "Use MCP screenshots during drag/drop QA.",
	},
	{
		"id": "card_art_view_draw",
		"display_name": "CardArtView Program Art",
		"category": "Cards",
		"current_scene_path": "",
		"source_script_path": "res://scripts/card_art_view.gd",
		"sceneization_status": STATUS_DRAW_SCRIPT,
		"priority": 4,
		"next_step": "Decide whether to keep as procedural art or wrap it in editable art scenes.",
		"risk_notes": "Low rule risk; affects perceived polish.",
		"mcp_notes": "Audit before replacing art anchors.",
	},
	{
		"id": "monster_art_view_draw",
		"display_name": "MonsterArtView Program Art",
		"category": "Cards",
		"current_scene_path": "",
		"source_script_path": "res://scripts/monster_art_view.gd",
		"sceneization_status": STATUS_DRAW_SCRIPT,
		"priority": 4,
		"next_step": "Wrap recurring monster motifs in editable scenes if they need designer tuning.",
		"risk_notes": "Low rule risk; medium theme risk.",
		"mcp_notes": "Use when moving from procedural motifs to asset-based monster art.",
	},
	{
		"id": "main_card_resolution_track_legacy",
		"display_name": "Card Resolution Track Cutover",
		"category": "Legacy Main UI",
		"current_scene_path": "res://scenes/ui/CardResolutionTrack.tscn",
		"source_script_path": "res://scripts/ui/card_resolution_track.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep PublicTrack/CardResolutionTrack as the only renderer and route state through its snapshot bridge.",
		"risk_notes": "Low; the legacy generated renderer, scroll state, drag state, and refresh path have been removed.",
		"mcp_notes": "Inspect PublicTrack in GameScreen and run LegacyRuntimeSurfaceRetirementBench after track composition changes.",
	},
	{
		"id": "main_playtest_flow_compass_legacy",
		"display_name": "main.gd Playtest Flow Compass",
		"category": "Legacy Main UI",
		"current_scene_path": "res://scenes/ui/PlanetBoard.tscn",
		"source_script_path": "res://scripts/ui/planet_board.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 2,
		"next_step": "Keep first-glance map flow feedback in PlanetBoard snapshots and scene nodes.",
		"risk_notes": "Low; the duplicate generated compass has been removed.",
		"mcp_notes": "Inspect PlanetBoard and PlayerBoard first-glance rails when onboarding copy changes.",
	},
	{
		"id": "main_weather_forecast_strip_legacy",
		"display_name": "main.gd Weather Forecast Strip",
		"category": "Legacy Main UI",
		"current_scene_path": "res://scenes/ui/GameScreen.tscn",
		"source_script_path": "res://scripts/ui/game_screen.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 2,
		"next_step": "Keep weather and pressure context in sceneized TopBar, PlanetBoard, and snapshot data.",
		"risk_notes": "Low; the duplicate generated forecast strip has been removed.",
		"mcp_notes": "Inspect GameScreen and TopBar with runtime weather fixtures.",
	},
	{
		"id": "main_legacy_table_shell",
		"display_name": "Legacy Table Shell Retirement",
		"category": "Legacy Main UI",
		"current_scene_path": "res://scenes/ui/GameScreen.tscn",
		"source_script_path": "res://scripts/ui/game_screen.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 2,
		"next_step": "Keep RuntimeGameScreen mandatory and reject missing scene composition instead of rebuilding a generated table.",
		"risk_notes": "Low; the rollback shell and runtime build switch are deleted and covered by a dedicated gate.",
		"mcp_notes": "LegacyRuntimeTable must not appear in main.tscn or the live scene tree.",
	},
	{
		"id": "legacy_runtime_surface_retirement_gate",
		"display_name": "Legacy Runtime Surface Retirement Gate",
		"category": "Core Table",
		"current_scene_path": "res://scenes/tools/LegacyRuntimeSurfaceRetirementBench.tscn",
		"source_script_path": "res://scripts/tools/legacy_runtime_surface_retirement_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Run this gate whenever main composition, PublicTrack, PlayerBoard, or Overlay ownership changes.",
		"risk_notes": "Medium; regressions could silently reintroduce duplicate player-facing runtime surfaces.",
		"mcp_notes": "Require 14/14, no LegacyRuntimeTable, no old card-track builder, pure runtime snapshot data, and zero fallback duplicates.",
	},
	{
		"id": "legacy_player_surface_retirement_gate",
		"display_name": "Legacy Player Surface Retirement Gate",
		"category": "Core Table",
		"current_scene_path": "res://scenes/tools/LegacyPlayerSurfaceRetirementBench.tscn",
		"source_script_path": "res://scripts/tools/legacy_player_surface_retirement_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep player rendering in scenes and keep card/table presentation in the two Sprint 42 services while main.gd shrinks to domain-fact and action adapters.",
		"risk_notes": "Medium; reintroducing generated player controls would create duplicate input and privacy ownership.",
		"mcp_notes": "Require FirstMission 37/37 after Sprint 61 pacing instrumentation and all 164 call-graph-closed player/card-surface, presentation, resolution-cinematic, hand/track snapshot, resolution-overlay badge, RightInspector, and TableSnapshot helpers absent from main.gd.",
	},
	{
		"id": "card_presentation_runtime_service_gate",
		"display_name": "Card Presentation Runtime Service Gate",
		"category": "Core Table",
		"current_scene_path": "res://scenes/runtime/CardPresentationRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/card_presentation_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep colors, icons, routes, use-case copy, rules copy, chips, tooltips, and hand-card ViewModels in this scene service.",
		"risk_notes": "Medium; duplicate presentation rules in main.gd would drift between CardFace, Card Codex, hand, and track surfaces.",
		"mcp_notes": "The service receives price and legality as facts. It must remain free of world mutation, card-effect execution, and Node reads.",
	},
	{
		"id": "card_play_eligibility_runtime_gate",
		"display_name": "Card Play Eligibility Runtime Gate",
		"category": "Core Table",
		"current_scene_path": "res://scenes/tools/CardPlayEligibilityRuntimeBench.tscn",
		"source_script_path": "res://scripts/runtime/card_play_eligibility_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep one legality owner and move next to Monster Runtime Hard Cutover without widening Queue or Execution.",
		"risk_notes": "High; a parallel legality branch would desynchronize UI, AI, Coach, Queue, or settlement revalidation.",
		"mcp_notes": "Require 46/46, stable reason_code, pure facts/results, all legacy legality functions absent, and main.gd at or below the Sprint 43 deletion ceiling.",
	},
	{
		"id": "monster_runtime_characterization_gate",
		"display_name": "Monster Runtime Hard Cutover Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/MonsterRuntimeCharacterizationBench.tscn",
		"source_script_path": "res://scripts/runtime/monster_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep MonsterRuntimeController as the sole owner; split only internal families behind the 50-case gate if future complexity requires it.",
		"risk_notes": "High; shared RNG order, hidden binding, linear movement, damage cash clues, forced wager freeze, and save compatibility must migrate together without parallel owners.",
		"mcp_notes": "Sprint 45 requires 50/50, one controller and one non-owning bridge, legacy main functions/state absent, pure public debug, and save compatibility.",
	},
	{
		"id": "military_runtime_characterization_gate",
		"display_name": "Military Runtime Hard Cutover Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/MilitaryRuntimeCharacterizationBench.tscn",
		"source_script_path": "res://scripts/runtime/military_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep MilitaryRuntimeController as the sole owner; split only internal command families behind the 50-case gate if future complexity requires it.",
		"risk_notes": "High; cap replacement, linear arrival, command cooldown, GDP/route damage, Inventory invalidation, Monster HP routing, and save compatibility must stay synchronized.",
		"mcp_notes": "Sprint 47 requires 50/50, one controller and one non-owning bridge, legacy main functions/state absent, pure public debug, and save compatibility.",
	},
	{
		"id": "weather_runtime_characterization_gate",
		"display_name": "Weather Runtime Hard Cutover Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/WeatherRuntimeCharacterizationBench.tscn",
		"source_script_path": "res://scripts/runtime/weather_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Protect the 53-case Weather Runtime gate and keep optional future weather effects behind explicit characterization.",
		"risk_notes": "High; preserve the public 1-3 minute warning, shared RNG order, overlapping multipliers, monster-wager freeze, world refresh order, and v1 save keys.",
		"mcp_notes": "Sprint 49 reports 53/53. WeatherRuntimeController is authoritative; WeatherRuntimeWorldBridge is non-owning and EnvironmentBalanceModel remains QA-only.",
	},
	{
		"id": "contract_runtime_characterization_gate",
		"display_name": "Contract Runtime Hard Cutover Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/ContractRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/contract_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Protect the 62-case Contract Runtime gate and characterize any new contract card family before extending the authoritative Controller.",
		"risk_notes": "High; responder authority, self-sign permission, preempted timer suspension, non-blocking continuation, exact-once settlement, and privacy must be resolved together.",
		"mcp_notes": "Sprint 51 reports 62/62. ContractRuntimeController is authoritative, ContractRuntimeWorldBridge is non-owning, and the 37 legacy main.gd functions are absent.",
	},
	{
		"id": "game_table_viewmodel_runtime_service_gate",
		"display_name": "Game Table ViewModel Runtime Service Gate",
		"category": "Core Table",
		"current_scene_path": "res://scenes/runtime/GameTableViewModelRuntimeService.tscn",
		"source_script_path": "res://scripts/runtime/game_table_viewmodel_runtime_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep TableSnapshot normalization, hand/track composition, and RightInspector precedence in this service.",
		"risk_notes": "High; a parallel main.gd snapshot owner can leak private track facts or produce contradictory selection state.",
		"mcp_notes": "Require pure-data input/output, public track privacy, existing action ids, and no play-legality or runtime-mutation ownership.",
	},
	{
		"id": "menu_shell_runtime_cutover_gate",
		"display_name": "Menu Shell Runtime Cutover Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/MenuShellRuntimeCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/menu_shell_runtime_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep menu shell, presentation settings, and scenario pause commands scene-owned while moving the next closed active menu surface out of main.gd.",
		"risk_notes": "Medium; a fallback builder, generated settings Button, or generated pause row would restore duplicate menu ownership.",
		"mcp_notes": "Require 24/24, seven quick-navigation buttons, twelve settings buttons, five pause buttons, pure descriptors, and no retired menu builders in main.gd.",
	},
	{
		"id": "global_ui_navigation_characterization_gate",
		"display_name": "Global UI Navigation Characterization Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/MenuShellRuntimeCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/global_ui_navigation_characterization_registry.gd",
		"sceneization_status": STATUS_PARTIAL,
		"priority": 1,
		"next_step": "Sprint 68 should add one pure-data global surface-stack owner and hard-cut the Esc, Back, modal precedence, and focus-restore branches without absorbing Codex-local state.",
		"risk_notes": "High; forced decisions, confirmation dialogs, drawers, controller input, and focus restoration currently lack one precedence authority.",
		"mcp_notes": "Run MenuShellRuntimeCutoverBench and require 24/24 plus 32/32 observed. Keep aligned separate until the Sprint 68 hard cutover; Sprint 67 baseline is 19/32 aligned.",
	},
	{
		"id": "codex_scene_hard_cutover_gate",
		"display_name": "Codex Scene Hard Cutover Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/CodexSceneHardCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/codex_scene_hard_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the card browser and Card, Monster, Product, Region, and Role detail renderers scene-owned; Monster/Product atlases are now covered by the following gate, so next extract shared catalog navigation state and pure source adapters.",
		"risk_notes": "Medium; restoring fallback renderers would recreate a second Codex presentation authority inside main.gd.",
		"mcp_notes": "Require 20/20, six editable scene contracts, pure snapshots, and all 24 generated fallback renderer functions absent.",
	},
	{
		"id": "codex_atlas_scene_cutover_gate",
		"display_name": "Codex Atlas Scene Cutover Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/CodexAtlasSceneCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/codex_atlas_scene_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep monster and product atlas navigation, thumbnail cards, summaries, previews, and input scene-owned; next extract catalog state and source snapshots from main.gd.",
		"risk_notes": "Medium; rebuilding either atlas in main.gd would restore raw-Control ownership and duplicate input routing.",
		"mcp_notes": "Require 20/20, scene-instanced thumbnails and summaries, stable preview/detail signals, pure snapshots, and all 14 atlas helpers absent.",
	},
	{
		"id": "codex_navigation_runtime_ownership_gate",
		"display_name": "Codex Navigation Runtime Ownership Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/CodexNavigationRuntimeCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/codex_navigation_runtime_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep five-domain navigation and v1 persistence in CodexNavigationRuntimeController; next separate pure catalog source adapters from gameplay catalog owners before extracting page routing.",
		"risk_notes": "Medium; restoring navigation mirrors in main.gd would split page, detail, filter, and return-route authority.",
		"mcp_notes": "Require 20/20, exact legacy-save parity, pure snapshots, 17 retired state variables, nine retired pagination helpers, and real-main route delegation.",
	},
	{
		"id": "codex_public_snapshot_ownership_gate",
		"display_name": "Codex Public Snapshot Ownership Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/CodexPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/codex_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep Role/Region public presentation in CodexPublicSnapshotService; Monster and Product public presentation now have separate bounded services.",
		"risk_notes": "Medium; restoring any of the 23 formatters in main.gd would split privacy and presentation authority.",
		"mcp_notes": "Require 20/20, pure source and output snapshots, real-main routing, privacy sanitization, 23 retired formatters, and shrinking main.gd metrics.",
	},
	{
		"id": "monster_codex_public_snapshot_ownership_gate",
		"display_name": "Monster Codex Public Snapshot Ownership Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/MonsterCodexPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/monster_codex_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep monster presentation in MonsterCodexPublicSnapshotService; probability algorithms remain domain-owned while Product presentation now has its own service.",
		"risk_notes": "Medium; moving action-weight calculations into presentation would create a second probability authority.",
		"mcp_notes": "Require 20/20, pure source/output, real atlas/detail routing, exact supplied probability display, 14 retired formatters, and no probability calculation in the service.",
	},
	{
		"id": "product_codex_public_snapshot_ownership_gate",
		"display_name": "Product Codex Public Snapshot Ownership Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/ProductCodexPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/product_codex_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep Product presentation in ProductCodexPublicSnapshotService; Card presentation now has an equally bounded service.",
		"risk_notes": "Medium; moving market-price or strategy-score calculations into presentation would create a second economy authority.",
		"mcp_notes": "Require 20/20, pure source/output, real atlas/detail routing, supplied price/strategy parity, 20 retired formatters, and no market calculation in the service.",
	},
	{
		"id": "card_codex_public_snapshot_ownership_gate",
		"display_name": "Card Codex Public Snapshot Ownership Gate",
		"category": "Menu / Codex",
		"current_scene_path": "res://scenes/tools/CardCodexPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/card_codex_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep Card presentation in CardCodexPublicSnapshotService; Economy Dashboard presentation now has its own bounded service.",
		"risk_notes": "Medium; moving price, effect, target, upgrade, or play-requirement calculation into presentation would create a second card-rule authority.",
		"mcp_notes": "Require 20/20, both existing ViewModels, pure source/output, real browser/detail routing, 19 retired formatters, and no card-rule calculation in the service.",
	},
	{
		"id": "economy_dashboard_public_snapshot_ownership_gate",
		"display_name": "Economy Dashboard Public Snapshot Ownership Gate",
		"category": "Menu / Economy",
		"current_scene_path": "res://scenes/tools/EconomyDashboardPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/economy_dashboard_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep public economy presentation in EconomyDashboardPublicSnapshotService; Standings now has its own bounded service, so audit Intel next.",
		"risk_notes": "High; moving price, GDP, income, cashflow, or private-truth calculation into presentation would create a second economy authority.",
		"mcp_notes": "Require 20/20, pure bounded source/output, real menu render below five seconds, 16 retired formatters, and no economy calculation in the service.",
	},
	{
		"id": "standings_public_snapshot_ownership_gate",
		"display_name": "Standings Public Snapshot Ownership Gate",
		"category": "Menu / Standings",
		"current_scene_path": "res://scenes/tools/StandingsPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/standings_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep standings presentation in StandingsPublicSnapshotService; Final Settlement is now service-owned, then migrate Intel Dossier as one action-id closure.",
		"risk_notes": "High; moving cash, GDP, settlement score, final ordering, or private-truth calculation into presentation would create a second scoring authority.",
		"mcp_notes": "Require 20/20, pure bounded source/output, real menu render below five seconds, four retired formatters, and explicit opponent redaction.",
	},
	{
		"id": "final_settlement_public_snapshot_ownership_gate",
		"display_name": "Final Settlement Public Snapshot Ownership Gate",
		"category": "Menu / Postgame",
		"current_scene_path": "res://scenes/tools/FinalSettlementPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/final_settlement_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep postgame presentation in FinalSettlementPublicSnapshotService; migrate Intel Dossier display and action-id controls together.",
		"risk_notes": "High; moving final score, rank ordering, city clearance, intel cash, or private histories into presentation would create a second settlement authority.",
		"mcp_notes": "Require 20/20, pure bounded source/output, real menu render below five seconds, four retired formatters, stable action ids, and private-input rejection.",
	},
	{
		"id": "intel_dossier_public_snapshot_ownership_gate",
		"display_name": "Intel Dossier Public Snapshot Ownership Gate",
		"category": "Menu / Intel",
		"current_scene_path": "res://scenes/tools/IntelDossierPublicSnapshotCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/intel_dossier_public_snapshot_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep dossier presentation and action intents in IntelDossierPublicSnapshotService; next audit the remaining MenuOverlay route orchestration or another closed main.gd presentation domain.",
		"risk_notes": "High; moving hidden truth or settlement into presentation would violate privacy, while restoring Callable-built controls in main.gd would split UI ownership.",
		"mcp_notes": "Require 20/20, viewer-safe pure source/output, real menu render below five seconds, 22 retired formatters/builders, stable track action ids, and private-input rejection.",
	},
	{
		"id": "new_game_setup_page_ownership_gate",
		"display_name": "New Game Setup Page Ownership Gate",
		"category": "Menu / New Game",
		"current_scene_path": "res://scenes/tools/NewGameSetupPageCutoverBench.tscn",
		"source_script_path": "res://scripts/tools/new_game_setup_page_cutover_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep setup composition and action intents in NewGameSetupPage; move another closed menu/runtime ownership boundary without reintroducing generated Controls.",
		"risk_notes": "Medium; setup rendering is scene-owned, while role assignment, monster selection, recommended configuration, run creation, and navigation must remain existing domain actions.",
		"mcp_notes": "Require 20/20, one pure page snapshot, real child-scene composition, stable setup_* ids, real-main route below five seconds, seven retired builders/wrappers, and private-input rejection.",
	},
	{
		"id": "product_market_runtime_characterization_gate",
		"display_name": "Product Market Runtime Hard Cutover Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/ProductMarketRuntimeCharacterizationBench.tscn",
		"source_script_path": "res://scripts/runtime/product_market_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the 76-case live gate green while the next finance family enters authored v0.4 alignment.",
		"risk_notes": "High; shared RNG order, market tick ordering, futures exact-once payout, warehouse destruction, v1 saves, and cross-controller refresh requests must move together.",
		"mcp_notes": "Sprint 55 reports 100/100 records: 50 market lifecycle, 24 historical integrity, and 26 live terms cutover cases. ProductMarketRuntimeController remains authoritative.",
	},
	{
		"id": "product_futures_v04_terms_gate",
		"display_name": "Product Futures v0.4 Terms Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/ProductMarketRuntimeCharacterizationBench.tscn",
		"source_script_path": "res://scripts/tools/product_market_runtime_characterization_bench.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Use the Inspector catalog as the only futures terms source and keep Queue, AI, Presentation, save, and settlement parity green.",
		"risk_notes": "High; margin timing, gain/loss caps, warehouse HP snapshots, Queue authorization, AI scoring, save defaults, and privacy must align atomically.",
		"mcp_notes": "Sprint 55 authors twelve .tres terms, removes the positive-only fallback, and passes 76/76 live alignment with zero design decisions.",
	},
	{
		"id": "city_gdp_derivative_v04_terms_gate",
		"display_name": "City GDP Derivative v0.4 Terms Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/CityGdpDerivativeRuntimeBench.tscn",
		"source_script_path": "res://scripts/runtime/city_gdp_derivative_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the 40-case terms, margin, exact-once, save, and privacy gate green while authoring further finance content.",
		"risk_notes": "High; Queue authorization, effect-open margin, expiry/destruction, two-way caps, legacy saves, AI scoring, and public privacy share one terms source.",
		"mcp_notes": "CityGdpDerivativeRuntimeController and its WorldBridge are static coordinator scenes; twelve .tres terms replace all main.gd gdp_bet fields and payout functions.",
	},
	{
		"id": "runtime_card_catalog_resource_gate",
		"display_name": "Runtime Card Catalog Resource Gate",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CardRuntimeCatalogService.tscn",
		"source_script_path": "res://scripts/runtime/card_runtime_catalog_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the Sprint 58 runtime integrity gate and Sprint 59 authoring workflow green whenever a card family, authored rank, pack order, or public-pool membership changes.",
		"risk_notes": "Medium; all 239 authored hashes and deterministic orders are now gated, while external financial terms and dynamic Monster definitions retain their dedicated owners.",
		"mcp_notes": "Sprint 58 is cutover_complete: CardRuntimeCatalogService and DefinitionWorldBridge are static Coordinator scenes, the Resource graph is Inspector editable, and the 80/80 gate proves no main.gd fallback remains. Sprint 59 adds the custom Inspector authoring panel, Workspace, validator, baseline and change-review package.",
	},
	{
		"id": "runtime_card_authoring_workflow_gate",
		"display_name": "Runtime Card Authoring Workflow Gate",
		"category": "Tools",
		"current_scene_path": "res://scenes/tools/RuntimeCardAuthoringWorkspace.tscn",
		"source_script_path": "res://scripts/cards/card_runtime_authoring_service.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Use the Inspector panel and 36-case QA gate for every authored card change; keep review artifacts under user://.",
		"risk_notes": "Low runtime risk because the workflow is editor-only; content risk is blocked by kind schemas, identity checks, deterministic order review, and downstream consumer prompts.",
		"mcp_notes": "Open RuntimeCardAuthoringWorkspace, edit a real family .tres in Inspector, validate the target, capture a working baseline, then build and review the JSON/Markdown change package before running RuntimeCardAuthoringWorkflowBench.",
	},
	{
		"id": "city_trade_network_characterization_gate",
		"display_name": "City / Trade Network Runtime Hard Cutover",
		"category": "Systems",
		"current_scene_path": "res://scenes/runtime/CityTradeNetworkRuntimeController.tscn",
		"source_script_path": "res://scripts/runtime/city_trade_network_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the 108-case SS05-03 gate green while SS05-04 adds qualification and victory as a consumer of the existing receipts, never as a second GDP owner.",
		"risk_notes": "Medium; five-slot identity, routes, structured GDP rows, project/player/neutral attribution, cashflow source IDs, and save normalization are now one verified chain.",
		"mcp_notes": "SS05-03 is fully sceneized. The gate proves five canonical slots, stable generations, exact-tie no-control, zero GDP, conservation, neutral remainder, privacy, and 108/108 alignment.",
	},
	{
		"id": "city_development_settlement_characterization_gate",
		"display_name": "City Development Settlement Hard Cutover",
		"category": "Systems",
		"current_scene_path": "res://scenes/tools/CityDevelopmentSettlementRuntimeCharacterizationBench.tscn",
		"source_script_path": "res://scripts/runtime/city_development_runtime_controller.gd",
		"sceneization_status": STATUS_FULL,
		"priority": 1,
		"next_step": "Keep the 64-case gate green and select the next main.gd runtime ownership family.",
		"risk_notes": "Medium; settlement ownership is cut over, while Network, Market, GDP, and project-share arithmetic remain deliberately separate owners.",
		"mcp_notes": "Sprint 66 is fully sceneized. GameRuntimeCoordinator composes one authoritative Controller and one non-owning WorldBridge with an explicit rollback envelope.",
	},
]


func categories() -> Array[String]:
	return status_ids()


func status_ids() -> Array[String]:
	var result: Array[String] = []
	for id in STATUS_ORDER:
		result.append(str(id))
	return result


func records() -> Array:
	return _duplicate_records(RECORDS)


func records_for_status(status: String) -> Array:
	var result: Array = []
	for record_variant in RECORDS:
		var record: Dictionary = record_variant if record_variant is Dictionary else {}
		if str(record.get("sceneization_status", "")) == status:
			result.append(record.duplicate(true))
	return result


func record_for_id(id: String) -> Dictionary:
	for record_variant in RECORDS:
		var record: Dictionary = record_variant if record_variant is Dictionary else {}
		if str(record.get("id", "")) == id:
			return record.duplicate(true)
	return {}


func summary() -> Dictionary:
	var counts := {}
	for status in STATUS_ORDER:
		counts[status] = records_for_status(status).size()
	return {
		"total": RECORDS.size(),
		"counts": counts,
		"highest_priority": priority_records(5),
	}


func priority_records(limit: int = 8) -> Array:
	var sorted_records := _duplicate_records(RECORDS)
	sorted_records.sort_custom(func(a: Dictionary, b: Dictionary) -> bool:
		return int(a.get("priority", 99)) < int(b.get("priority", 99))
	)
	return sorted_records.slice(0, maxi(0, limit))


func _duplicate_records(source: Array) -> Array:
	var result: Array = []
	for record_variant in source:
		var record: Dictionary = record_variant if record_variant is Dictionary else {}
		result.append(record.duplicate(true))
	return result
