extends RefCounted
class_name SpaceSyndicateSystemResourceizationAuditRegistry

const CATEGORY_MAIN_MENU := "Main Menu"
const CATEGORY_BALANCE := "Balance / Gradient"
const CATEGORY_AI := "AI / Monster AI"
const CATEGORY_RUNTIME_FALLBACKS := "Runtime Fallbacks"

const CATEGORY_ORDER := [
	CATEGORY_MAIN_MENU,
	CATEGORY_BALANCE,
	CATEGORY_AI,
	CATEGORY_RUNTIME_FALLBACKS,
]

const STATUS_SCENEIZED := "sceneized"
const STATUS_SCRIPT_MODULE := "script_module"
const STATUS_JSON_DATA := "json_data"
const STATUS_MAIN_GD_RUNTIME := "main_gd_runtime"
const STATUS_CANDIDATE_RESOURCE := "candidate_resource"
const STATUS_RESOURCE_ASSET := "resource_asset"

const RECORDS := [
	{
		"id": "main_menu_lobby_sceneized_shell",
		"display_name": "Main Menu / Lobby Scenes",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/ui/MenuRootLobby.tscn",
		"related_paths": [
			"res://scenes/ui/MenuOverlay.tscn",
			"res://scenes/ui/MenuQuickNavigation.tscn",
			"res://scenes/ui/MenuRootLobby.tscn",
			"res://scenes/ui/NewGameSetupPage.tscn",
			"res://scenes/ui/PresentationSettingsPanel.tscn",
			"res://scenes/ui/ScenarioPauseActionsPanel.tscn",
			"res://scenes/ui/NewGameSetupLobby.tscn",
			"res://scenes/ui/NewGameSetupOptionBoard.tscn",
			"res://scenes/ui/NewGameSetupSeatCard.tscn",
			"res://scenes/ui/NewGameSetupSeatIdentityBoard.tscn",
			"res://scenes/ui/CampaignMenu.tscn",
		],
		"function_count": 0,
		"key_functions": [],
		"editor_visibility": "scene_tree",
		"risk_level": "medium",
		"recommended_next_step": "Keep MenuOverlay, MenuRootLobby, NewGameSetupPage, PresentationSettingsPanel, and ScenarioPauseActionsPanel as the editable shell; route future changes through pure snapshots and string action ids.",
		"mcp_notes": "Menu shell layout, quick navigation, complete setup, PresentationSettingsPanel, and ScenarioPauseActionsPanel are scene-owned. Open these scenes through MCP before changing menu flows.",
	},
	{
		"id": "main_gd_menu_controller_runtime",
		"display_name": "main.gd Menu / Codex Routing",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_MAIN_GD_RUNTIME,
		"current_path": "res://scripts/main.gd",
		"related_paths": ["res://scripts/main.gd", "res://scenes/ui/MenuOverlay.tscn", "res://scenes/ui/MenuQuickNavigation.tscn", "res://scenes/ui/PresentationSettingsPanel.tscn", "res://scenes/ui/ScenarioPauseActionsPanel.tscn"],
		"function_count": 8,
		"key_functions": [
			"_bind_menu_overlay_scene",
			"_show_menu",
			"_open_main_menu",
			"_open_new_game_setup_menu",
			"_main_menu_root_lobby_snapshot",
			"_campaign_menu_snapshot",
			"_update_card_codex_menu",
			"_update_product_codex_menu",
			"_update_bestiary_menu",
		],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "medium",
		"recommended_next_step": "Use the Sprint 67 navigation contract to hard-cut global Back, surface-stack, modal precedence, and focus restoration into one bounded runtime owner; keep Codex-local state in CodexNavigationRuntimeController.",
		"mcp_notes": "Sprint 67 observes 32/32 global navigation cases with 19/32 aligned. main.gd remains the global Back owner until Sprint 68; no parallel navigation controller exists yet.",
	},
	{
		"id": "global_ui_navigation_characterization",
		"display_name": "Global Back / Focus Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_MAIN_GD_RUNTIME,
		"current_path": "res://scripts/main.gd::_unhandled_input",
		"related_paths": ["res://scripts/main.gd", "res://scripts/ui/menu_overlay.gd", "res://scripts/ui/overlay_layer.gd", "res://scripts/tools/global_ui_navigation_characterization_registry.gd", "res://docs/global_ui_navigation_runtime_contract.md"],
		"function_count": 5,
		"key_functions": ["_unhandled_input", "_show_menu", "_close_menu", "_back_from_catalog_menu", "_catalog_back_button_text"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "high",
		"recommended_next_step": "Create one pure-data GlobalUiNavigationRuntimeController in Sprint 68, then delete the characterized main.gd routing branches in the same change.",
		"mcp_notes": "Current priority is fullscreen map, menu, then pause. Confirmation, forced decisions, drawers, exact parent focus, and ui_cancel are not globally owned.",
	},
	{
		"id": "codex_scene_hard_cutover",
		"display_name": "Codex Browser / Detail Scene Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/ui/CardCodexBrowser.tscn",
		"related_paths": [
			"res://scenes/ui/CardCodexBrowser.tscn",
			"res://scenes/ui/CardCodexDetail.tscn",
			"res://scenes/ui/BestiaryDetail.tscn",
			"res://scenes/ui/ProductCodexDetail.tscn",
			"res://scenes/ui/RegionCodexDetail.tscn",
			"res://scenes/ui/RoleCodexIdentityBoard.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["set_browser", "set_detail", "set_monster", "set_product", "set_region", "set_role"],
		"editor_visibility": "scene_tree",
		"risk_level": "low",
		"recommended_next_step": "Keep all browser/detail rendering scene-owned, then extract catalog routing state and source snapshot composition from main.gd.",
		"mcp_notes": "All six scene contracts are hard dependencies. Sprint 11 retired 24 generated browser/detail renderers; Sprint 12 also sceneized Monster/Product atlases and retired 14 raw-Control helpers.",
	},
	{
		"id": "codex_atlas_scene_cutover",
		"display_name": "Monster / Product Atlas Scene Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/ui/BestiaryCodexBrowser.tscn",
		"related_paths": [
			"res://scenes/ui/BestiaryCodexBrowser.tscn",
			"res://scenes/ui/ProductCodexBrowser.tscn",
			"res://scenes/ui/codex/BestiaryCodexThumbnailCard.tscn",
			"res://scenes/ui/codex/ProductCodexThumbnailCard.tscn",
			"res://scenes/ui/codex/CodexBrowserSummaryCard.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["set_browser", "set_entry", "debug_snapshot"],
		"editor_visibility": "scene_tree",
		"risk_level": "low",
		"recommended_next_step": "Move catalog selection/page state and pure source snapshot composition into a scene-owned Codex runtime controller.",
		"mcp_notes": "Both atlases use scene instances for summaries, thumbnails, badges, and detail previews. Fourteen generated main.gd helpers are retired; gate is 20/20.",
	},
	{
		"id": "codex_navigation_runtime_cutover",
		"display_name": "Codex Navigation Runtime Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CodexNavigationRuntimeController.tscn",
		"related_paths": [
			"res://scenes/runtime/CodexNavigationRuntimeController.tscn",
			"res://scripts/runtime/codex_navigation_runtime_controller.gd",
			"res://scenes/runtime/GameRuntimeCoordinator.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["domain_state", "update_domain", "navigation_snapshot", "to_legacy_save_snapshot", "apply_legacy_save_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Extract public catalog source snapshots through pure-data adapters, then move page routing without moving gameplay catalog algorithms.",
		"mcp_notes": "Five-domain navigation and exact v1 save compatibility are controller-owned. Seventeen main.gd state variables and nine pagination helpers are retired; gate is 20/20.",
	},
	{
		"id": "codex_public_snapshot_cutover",
		"display_name": "Codex Public Snapshot Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CodexPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/CodexPublicSnapshotService.tscn",
			"res://scripts/runtime/codex_public_snapshot_service.gd",
			"res://scenes/tools/CodexPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose_role", "compose_region", "role_route_label", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Characterize Monster/Product public snapshots before separating their probability and market fact adapters from presentation.",
		"mcp_notes": "Role and Region summaries, boards, chips, KPIs, clues, and card-face formatting are service-owned. Twenty-three main.gd formatters are retired; gate is 20/20.",
	},
	{
		"id": "monster_codex_public_snapshot_cutover",
		"display_name": "Monster Codex Public Snapshot Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/MonsterCodexPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/MonsterCodexPublicSnapshotService.tscn",
			"res://scripts/runtime/monster_codex_public_snapshot_service.gd",
			"res://scenes/tools/MonsterCodexPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Keep monster presentation isolated; Product presentation now has its own bounded service and market authority remains outside both.",
		"mcp_notes": "Monster summaries, thumbnails, details, chips, KPIs, action cards, and tooltips are service-owned. Fourteen main.gd formatters are retired; action weights remain domain-owned; gate is 20/20.",
	},
	{
		"id": "product_codex_public_snapshot_cutover",
		"display_name": "Product Codex Public Snapshot Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/ProductCodexPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/ProductCodexPublicSnapshotService.tscn",
			"res://scripts/runtime/product_codex_public_snapshot_service.gd",
			"res://scenes/tools/ProductCodexPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Keep the bounded Product service stable while the next main.gd ownership closure is selected.",
		"mcp_notes": "Product summaries, thumbnails, market details, chips, KPIs, strategy cards, and tooltips are service-owned. Twenty main.gd formatters are retired; price and strategy algorithms remain domain-owned; gate is 20/20.",
	},
	{
		"id": "card_codex_public_snapshot_cutover",
		"display_name": "Card Codex Public Snapshot Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardCodexPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/CardCodexPublicSnapshotService.tscn",
			"res://scripts/runtime/card_codex_public_snapshot_service.gd",
			"res://scripts/viewmodels/card_codex_browser_snapshot.gd",
			"res://scripts/viewmodels/card_codex_detail_snapshot.gd",
			"res://scenes/tools/CardCodexPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose_browser", "compose_detail", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Keep card-rule facts domain-owned; Economy Dashboard presentation now has a separate bounded service.",
		"mcp_notes": "Card browser/detail presentation is service-owned through the two existing ViewModels. Nineteen main.gd formatters are retired; prices, effects, targets, upgrades, and legality remain domain-owned; gate is 20/20.",
	},
	{
		"id": "economy_dashboard_public_snapshot_cutover",
		"display_name": "Economy Dashboard Public Snapshot Ownership",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/EconomyDashboardPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/EconomyDashboardPublicSnapshotService.tscn",
			"res://scripts/runtime/economy_dashboard_public_snapshot_service.gd",
			"res://scenes/ui/EconomyDashboard.tscn",
			"res://scripts/ui/economy_dashboard.gd",
			"res://scenes/tools/EconomyDashboardPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Keep economy algorithms domain-owned; Standings presentation now has its own bounded service.",
		"mcp_notes": "Economy summary, overview cards, chips, KPIs, decisions, and six lanes are service-owned. Sixteen main.gd formatters are retired; real menu open is performance-gated; price/GDP/income/cashflow remain domain-owned; gate is 20/20.",
	},
	{
		"id": "standings_public_snapshot_cutover",
		"display_name": "Standings Public Snapshot Ownership",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/StandingsPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/StandingsPublicSnapshotService.tscn",
			"res://scripts/runtime/standings_public_snapshot_service.gd",
			"res://scenes/ui/StandingsScoreboard.tscn",
			"res://scripts/ui/standings_scoreboard.gd",
			"res://scenes/tools/StandingsPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Keep score and economy algorithms domain-owned; Final Settlement now has its own bounded service.",
		"mcp_notes": "Standings summary, overview cards, chips, KPIs, and viewer-safe seat cards are service-owned. Four main.gd formatters are retired; score/GDP/cash/final order remain domain-owned; gate is 20/20.",
	},
	{
		"id": "final_settlement_public_snapshot_cutover",
		"display_name": "Final Settlement Public Snapshot Ownership",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/FinalSettlementPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/FinalSettlementPublicSnapshotService.tscn",
			"res://scripts/runtime/final_settlement_public_snapshot_service.gd",
			"res://scenes/ui/FinalSettlementBoard.tscn",
			"res://scripts/ui/final_settlement_board.gd",
			"res://scenes/tools/FinalSettlementPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Keep settlement algorithms domain-owned and migrate Intel Dossier display plus action-id controls as one closure.",
		"mcp_notes": "Postgame summary, chips, KPIs, money cards, public events, rank track, and after-actions are service-owned. Four main.gd formatters are retired; score/order/clearance/intel remain domain-owned; gate is 20/20.",
	},
	{
		"id": "intel_dossier_public_snapshot_cutover",
		"display_name": "Intel Dossier Public Snapshot Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/IntelDossierPublicSnapshotService.tscn",
		"related_paths": [
			"res://scenes/runtime/IntelDossierPublicSnapshotService.tscn",
			"res://scripts/runtime/intel_dossier_public_snapshot_service.gd",
			"res://scenes/ui/IntelDossierBoard.tscn",
			"res://scripts/ui/intel_dossier_board.gd",
			"res://scenes/tools/IntelDossierPublicSnapshotCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["compose", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "medium",
		"recommended_next_step": "Keep hidden truth and mutation domain-owned; audit the next closed MenuOverlay presentation or runtime orchestration boundary.",
		"mcp_notes": "Intel summary, evidence cards, action controls, public links, and action ids are service-owned. Twenty-two main.gd formatters/builders are retired; city guess mutation, wagers, settlement, and navigation remain domain-owned; gate is 20/20.",
	},
	{
		"id": "new_game_setup_page_cutover",
		"display_name": "New Game Setup Page Ownership",
		"category": CATEGORY_MAIN_MENU,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/ui/NewGameSetupPage.tscn",
		"related_paths": [
			"res://scenes/ui/NewGameSetupPage.tscn",
			"res://scripts/ui/new_game_setup_page.gd",
			"res://scenes/ui/NewGameSetupLobby.tscn",
			"res://scenes/ui/NewGameSetupOptionBoard.tscn",
			"res://scenes/ui/NewGameSetupSeatCard.tscn",
			"res://scenes/tools/NewGameSetupPageCutoverBench.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": ["set_page"],
		"editor_visibility": "scene_tree_and_script",
		"risk_level": "low",
		"recommended_next_step": "Keep setup configuration and run creation domain-owned; select the next closed main.gd UI composition boundary.",
		"mcp_notes": "Summary, lobby, options, seats, hints, commands, and setup_* intents are page-owned. Seven obsolete builders/wrappers and three child preloads are retired; gate is 20/20.",
	},
	{
		"id": "runtime_balance_model_scripts",
		"display_name": "Runtime Balance Model Scripts",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_SCRIPT_MODULE,
		"current_path": "res://scripts/balance/runtime_balance_model.gd",
		"related_paths": [
			"res://scripts/balance/runtime_balance_model.gd",
			"res://scripts/balance/movement_balance_model.gd",
			"res://scripts/balance/combat_balance_model.gd",
			"res://scripts/balance/environment_balance_model.gd",
			"res://scripts/balance/card_price_curve.gd",
		],
		"function_count": 0,
		"key_functions": [],
		"editor_visibility": "script_only",
		"risk_level": "high",
		"recommended_next_step": "Create .tres parameter Resources around model inputs before touching formulas.",
		"mcp_notes": "The logic is modularized as scripts, but designers cannot tune parameters in the Inspector yet.",
	},
	{
		"id": "balance_json_targets",
		"display_name": "Balance / Price JSON Data",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_JSON_DATA,
		"current_path": "res://data/balance/runtime_balance_targets.json",
		"related_paths": [
			"res://data/balance/runtime_balance_targets.json",
			"res://data/balance/price_curve_v1.json",
			"res://data/balance/vertical_slice_card_set.json",
		],
		"function_count": 0,
		"key_functions": [],
		"editor_visibility": "external_data",
		"risk_level": "medium",
		"recommended_next_step": "Wrap price and target JSON with Resource-backed profiles so Godot Inspector editing and QA manifests share one source.",
		"mcp_notes": "Treat JSON as current source data; the audit should not rewrite it.",
	},
	{
		"id": "main_gd_balance_wrappers",
		"display_name": "Gameplay Balance Diagnostics / Runtime Formula Boundary",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/GameplayBalanceDiagnosticsRuntimeService.tscn",
		"related_paths": [
			"res://scenes/runtime/GameplayBalanceDiagnosticsRuntimeService.tscn",
			"res://scripts/runtime/gameplay_balance_diagnostics_runtime_service.gd",
			"res://scenes/runtime/GameplayBalanceDiagnosticsWorldBridge.tscn",
			"res://scripts/runtime/gameplay_balance_diagnostics_world_bridge.gd",
			"res://resources/balance/development_route_catalog_v04.tres",
			"res://scripts/balance/runtime_balance_model.gd",
		],
		"function_count": 0,
		"key_functions": [
			"development_routes",
			"card_budget_report",
			"build_balance_report",
			"build_developer_panel_snapshot",
			"build_world_snapshot",
		],
		"editor_visibility": "scene_and_inspector_resource",
		"risk_level": "medium",
		"recommended_next_step": "Keep RuntimeBalanceModel as formula owner; add future diagnostics through the read-only Service and pure-data WorldBridge instead of main.gd.",
		"mcp_notes": "Sprint 62 retired main.gd route/report ownership. Open the two runtime scenes and seven Development Route Resources through Godot MCP.",
	},
	{
		"id": "balance_parameter_resource_profile",
		"display_name": "Balance Parameter Resource Profile",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_RESOURCE_ASSET,
		"current_path": "res://resources/balance/balance_parameter_profile_v1.tres",
		"related_paths": [
			"res://resources/balance/balance_parameter_profile_v1.tres",
			"res://resources/balance/runtime_balance_parameters_v1.tres",
			"res://resources/balance/card_price_curve_parameters_v1.tres",
			"res://scripts/balance/balance_parameter_profile_resource.gd",
			"res://scripts/balance/runtime_balance_parameters_resource.gd",
			"res://scripts/balance/card_price_curve_parameters_resource.gd",
			"res://scripts/balance/balance_parameter_resource_registry.gd",
			"res://scripts/balance/balance_parameter_model_adapter.gd",
			"res://scripts/balance/balance_runtime_parameter_bridge.gd",
			"res://scenes/tools/BalanceParameterResourceMcpPreview.tscn",
			"res://scenes/tools/BalanceParameterResourceBench.tscn",
			"res://scenes/tools/BalanceModelResourceSandbox.tscn",
			"res://scenes/tools/BalanceModelResourceSandboxBench.tscn",
			"res://scenes/tools/BalanceRuntimeBridgeMcpPreview.tscn",
			"res://scenes/tools/BalanceRuntimeBridgeBench.tscn",
			"res://resources/balance/development_route_catalog_v04.tres",
			"res://scenes/runtime/GameplayBalanceDiagnosticsRuntimeService.tscn",
		],
		"function_count": 0,
		"key_functions": [
			"to_runtime_targets_dictionary",
			"to_price_curve_dictionary",
			"validate_profile",
		],
		"editor_visibility": "inspector_resource",
		"risk_level": "high",
		"recommended_next_step": "Use BalanceModelResourceSandboxBench as the dry-run parity gate before routing runtime balance formulas to profile data.",
		"mcp_notes": "Open BalanceParameterResourceMcpPreview for Inspector payloads, then run BalanceModelResourceSandboxBench before editing resources/balance .tres files.",
	},
	{
		"id": "balance_runtime_bridge_controlled_candidate",
		"display_name": "Balance Runtime Bridge Controlled Candidate",
		"category": CATEGORY_BALANCE,
		"current_status": STATUS_CANDIDATE_RESOURCE,
		"current_path": "res://scripts/balance/balance_runtime_parameter_bridge.gd",
		"related_paths": [
			"res://scripts/balance/balance_runtime_parameter_bridge.gd",
			"res://scenes/tools/BalanceRuntimeBridgeMcpPreview.tscn",
			"res://scenes/tools/BalanceRuntimeBridgeBench.tscn",
			"res://scripts/balance/balance_parameter_resource_registry.gd",
			"res://resources/balance/balance_parameter_profile_v1.tres",
			"res://data/balance/runtime_balance_targets.json",
			"res://data/balance/price_curve_v1.json",
		],
		"function_count": 0,
		"key_functions": [
			"runtime_targets",
			"price_curve",
			"compare_sources",
			"default_source_mode",
		],
		"editor_visibility": "controlled_runtime_bridge",
		"risk_level": "high",
		"recommended_next_step": "Keep default source_mode=json_current; use the extended BalanceRuntimeBridgeBench for both source parity and read-only diagnostics ownership.",
		"mcp_notes": "The parameter bridge remains controlled. Sprint 62 adds scene-owned diagnostics without changing the gameplay source mode or RuntimeBalanceModel formulas.",
	},
	{
		"id": "main_gd_ai_policy_runtime",
		"display_name": "AI Runtime Policy / Scoring",
		"category": CATEGORY_AI,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/AiRuntimeController.tscn",
		"related_paths": ["res://scenes/runtime/AiRuntimeController.tscn", "res://scripts/runtime/ai_runtime_controller.gd", "res://scenes/runtime/AiRuntimeWorldBridge.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": [
			"_ai_",
			"_auto_ai_",
			"_weighted_",
			"score",
			"weight",
		],
		"editor_visibility": "scene_tree_inspector_and_script",
		"risk_level": "high",
		"recommended_next_step": "Keep AiRuntimeController as the single decision owner and split internal policy families only behind the 44-case gate.",
		"mcp_notes": "Decision state, candidates, scores, responses, learning, and Policy Resource consumption are Controller-owned; main keeps a narrow world adapter.",
	},
	{
		"id": "main_gd_monster_ai_runtime",
		"display_name": "Monster Runtime Controller",
		"category": CATEGORY_AI,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/MonsterRuntimeController.tscn",
		"related_paths": ["res://scenes/runtime/MonsterRuntimeController.tscn", "res://scenes/runtime/MonsterRuntimeWorldBridge.tscn", "res://scenes/tools/MonsterRuntimeCharacterizationBench.tscn", "res://docs/monster_runtime_ownership_contract.md"],
		"function_count": 0,
		"key_functions": [
			"_auto_monster_",
			"_monster_action",
			"_monster_target",
			"_monster_wager",
		],
		"editor_visibility": "scene_tree_inspector_and_script",
		"risk_level": "high",
		"recommended_next_step": "Keep the controller single-owned and use its 50-case gate before any internal decomposition.",
		"mcp_notes": "Sprint 45 moved roster, lifecycle, target/RNG, movement, combat, wagers and save state out of main.gd without a parallel fallback.",
	},
	{
		"id": "monster_runtime_characterization_gate",
		"display_name": "Monster Runtime Hard Cutover Gate",
		"category": CATEGORY_AI,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/tools/MonsterRuntimeCharacterizationBench.tscn",
		"related_paths": ["res://scenes/runtime/MonsterRuntimeController.tscn", "res://scenes/runtime/MonsterRuntimeWorldBridge.tscn", "res://scripts/tools/monster_runtime_characterization_bench.gd", "res://docs/monster_runtime_ownership_contract.md", "res://scenes/ui/map/PlanetMonsterToken.tscn", "res://scenes/ui/MonsterWagerDecisionPanel.tscn"],
		"function_count": 0,
		"key_functions": ["_summon_monster_from_card", "_weighted_auto_monster_target", "_auto_monster_movement_tick", "_auto_monster_take_damage", "_open_monster_wager_for_pair"],
		"editor_visibility": "runtime_scenes_and_cutover_bench",
		"risk_level": "high",
		"recommended_next_step": "Protect the single-owner boundary and keep public Codex/Token/Wager UI in their existing scene owners.",
		"mcp_notes": "The gate now reports 50/50 and verifies state, algorithms, AI routing, save ownership, privacy, and main deletion.",
	},
	{
		"id": "military_runtime_characterization_gate",
		"display_name": "Military Runtime Hard Cutover",
		"category": CATEGORY_AI,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/MilitaryRuntimeController.tscn",
		"related_paths": ["res://scenes/runtime/MilitaryRuntimeController.tscn", "res://scenes/runtime/MilitaryRuntimeWorldBridge.tscn", "res://scenes/tools/MilitaryRuntimeCharacterizationBench.tscn", "res://scripts/tools/military_runtime_characterization_bench.gd", "res://docs/military_runtime_ownership_contract.md", "res://scenes/runtime/AiRuntimeController.tscn", "res://scenes/runtime/MonsterRuntimeController.tscn", "res://scenes/runtime/CardInventoryRuntimeService.tscn"],
		"function_count": 0,
		"key_functions": ["summon_from_card", "tick", "trigger_command", "apply_gdp_pressure", "grant_bound_commands", "to_save_data", "apply_save_data"],
		"editor_visibility": "runtime_scenes_and_cutover_bench",
		"risk_level": "high",
		"recommended_next_step": "Protect the single-owner boundary and move to the next large main.gd runtime family.",
		"mcp_notes": "The gate now reports 50/50. MilitaryRuntimeController owns state and algorithms; AI selects intents, Inventory mutates command slots, and MonsterRuntimeController owns monster damage state.",
	},
	{
		"id": "weather_runtime_characterization_gate",
		"display_name": "Weather Runtime Controller",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/WeatherRuntimeController.tscn",
		"related_paths": ["res://scenes/runtime/WeatherRuntimeController.tscn", "res://scenes/runtime/WeatherRuntimeWorldBridge.tscn", "res://scenes/tools/WeatherRuntimeCharacterizationBench.tscn", "res://docs/weather_runtime_ownership_contract.md", "res://scenes/runtime/AiRuntimeController.tscn", "res://scripts/balance/environment_balance_model.gd"],
		"function_count": 0,
		"key_functions": ["schedule_next_forecast", "activate_forecast", "tick", "district_multiplier", "apply_weather_control", "to_save_data", "apply_save_data"],
		"editor_visibility": "controller_bridge_bench_and_sceneized_public_ui",
		"risk_level": "high",
		"recommended_next_step": "Protect the 53-case hard-cutover gate; characterize any new weather effect before extending the authoritative Controller.",
		"mcp_notes": "Sprint 49 reports 53/53. main.gd legacy weather state/functions are absent; EnvironmentBalanceModel remains QA-only.",
	},
	{
		"id": "contract_runtime_characterization_gate",
		"display_name": "Contract Runtime Controller",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/ContractRuntimeController.tscn",
		"runtime_owner": "res://scripts/runtime/contract_runtime_controller.gd",
		"related_paths": ["res://scenes/runtime/ContractRuntimeController.tscn", "res://scenes/runtime/ContractRuntimeWorldBridge.tscn", "res://scenes/tools/ContractRuntimeCharacterizationBench.tscn", "res://docs/contract_runtime_ownership_contract.md", "res://scenes/runtime/CardResolutionExecutionRuntimeService.tscn", "res://scenes/runtime/CardEconomyProductRouteFormulaRuntimeService.tscn", "res://scenes/runtime/CardPlayEligibilityRuntimeService.tscn", "res://scenes/runtime/AiRuntimeController.tscn", "res://scenes/ui/ContractResponseDecisionPanel.tscn"],
		"function_count": 0,
		"key_functions": ["open_offer", "respond_to_offer", "tick_visible_offer", "forced_candidates", "to_save_data", "apply_save_data"],
		"editor_visibility": "controller_bridge_bench_and_sceneized_response_panel",
		"risk_level": "high",
		"recommended_next_step": "Protect the single-owner boundary and characterize any future contract behavior before changing the Controller.",
		"mcp_notes": "Sprint 51 reports 62/62. Formula, AI choice, Eligibility, Presentation, Execution lifecycle, Forced Decision priority, and Overlay remain independent owners; ContractRuntimeController owns only the contract lifecycle.",
	},
	{
		"id": "ai_policy_resource_candidate",
		"display_name": "AI Policy Runtime Cutover",
		"category": CATEGORY_AI,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/AiRuntimeController.tscn",
		"related_paths": ["res://scenes/runtime/AiRuntimeController.tscn", "res://resources/ai/ai_policy_profile_v1.tres", "res://scenes/tools/AiPolicyResourceBench.tscn"],
		"function_count": 0,
		"key_functions": [
			"route_preference",
			"product_focus",
			"target_score",
			"card_play_candidate",
		],
		"editor_visibility": "runtime_resource_and_scene",
		"risk_level": "high",
		"recommended_next_step": "Use AiPolicyResourceBench before every runtime policy change; never restore a main.gd policy fallback.",
		"mcp_notes": "Runtime cutover is enabled and AiRuntimeController is the only decision owner.",
	},
	{
		"id": "ai_policy_resource_profile",
		"display_name": "AI Policy Resource Profile",
		"category": CATEGORY_AI,
		"current_status": STATUS_RESOURCE_ASSET,
		"current_path": "res://resources/ai/ai_policy_profile_v1.tres",
		"related_paths": [
			"res://resources/ai/ai_policy_profile_v1.tres",
			"res://resources/ai/personalities/pioneer_ai_policy.tres",
			"res://resources/ai/personalities/arbitrage_ai_policy.tres",
			"res://resources/ai/personalities/disruptor_ai_policy.tres",
			"res://resources/ai/personalities/monster_tamer_ai_policy.tres",
			"res://resources/ai/personalities/contract_ai_policy.tres",
			"res://resources/ai/personalities/intelligence_ai_policy.tres",
			"res://scripts/ai/ai_personality_policy_resource.gd",
			"res://scripts/ai/ai_policy_profile_resource.gd",
			"res://scripts/ai/ai_policy_resource_registry.gd",
			"res://scenes/runtime/AiRuntimeController.tscn",
			"res://scripts/runtime/ai_runtime_controller.gd",
			"res://scenes/runtime/AiRuntimeWorldBridge.tscn",
			"res://scenes/tools/AiPolicyResourceMcpPreview.tscn",
			"res://scenes/tools/AiPolicyResourceBench.tscn",
		],
		"function_count": 0,
		"key_functions": [
			"parameter_groups",
			"to_policy_dictionary",
			"to_main_source_dictionary",
			"validation_records",
		],
		"editor_visibility": "inspector_resource",
		"risk_level": "high",
		"recommended_next_step": "Keep runtime cutover enabled and preserve Resource/Controller parity through the 44-case gate.",
		"mcp_notes": "The Resource is the runtime source for 32 player-AI tunables and six personalities; main.gd has no parameter fallback.",
	},
	{
		"id": "main_runtime_composition_sceneized",
		"display_name": "Main Runtime Composition Sceneized",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/main.tscn",
		"related_paths": [
			"res://scenes/main.tscn",
			"res://scenes/ui/GameScreen.tscn",
			"res://scenes/ui/OverlayLayer.tscn",
			"res://scripts/main.gd",
		],
		"function_count": 0,
		"key_functions": [
			"_bind_sceneized_runtime_composition",
			"_bind_runtime_game_screen",
			"_bind_runtime_overlay_surfaces",
			"_runtime_composition_snapshot",
		],
		"editor_visibility": "scene_tree",
		"risk_level": "medium",
		"recommended_next_step": "Keep fallback creation inactive and move only clearly authored content or controller boundaries out of main.gd in later sprints.",
		"mcp_notes": "Open main.tscn to inspect composition ownership; runtime snapshot must report legacy_fallback_used=false and zero duplicates.",
	},
	{
		"id": "runtime_fallbacks_main_gd",
		"display_name": "Player-Facing Runtime Surface Cutover",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/ui/GameScreen.tscn",
		"related_paths": ["res://scenes/main.tscn", "res://scenes/ui/GameScreen.tscn", "res://scenes/ui/CardResolutionTrack.tscn", "res://scenes/ui/PlayerBoard.tscn", "res://scenes/ui/HandRack.tscn", "res://scenes/ui/CardFace.tscn", "res://scenes/ui/DistrictSupplyDrawer.tscn", "res://scenes/runtime/CardPresentationRuntimeService.tscn", "res://scenes/runtime/GameTableViewModelRuntimeService.tscn", "res://scenes/ui/OverlayLayer.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": [
			"_build_runtime_game_screen",
			"_bind_runtime_overlay_surfaces",
			"_runtime_composition_snapshot",
		],
		"editor_visibility": "scene_tree",
		"risk_level": "low",
		"recommended_next_step": "Keep GameScreen scenes plus CardPresentationRuntimeService and GameTableViewModelRuntimeService as hard dependencies; main.gd should only supply domain facts and route stable actions.",
		"mcp_notes": "LegacyRuntimeTable and 164 player/card-surface, presentation, resolution-cinematic, hand/track snapshot, resolution-overlay badge, RightInspector, and TableSnapshot helpers are retired. CardPresentationRuntimeService and GameTableViewModelRuntimeService now own the UI data contract.",
	},
	{
		"id": "card_presentation_runtime_service_owned",
		"display_name": "Card Presentation Runtime Service Ownership",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardPresentationRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/card_presentation_runtime_service.gd", "res://scenes/runtime/GameRuntimeCoordinator.tscn", "res://scenes/ui/CardFace.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": ["compose_card", "compose_hand_card", "icon_legend_text", "category_icon", "debug_snapshot"],
		"editor_visibility": "scene_tree",
		"risk_level": "medium",
		"recommended_next_step": "Keep price, target legality, and effects in their domain owners; feed those values to this presentation-only service as facts.",
		"mcp_notes": "Sprint 42 removes the parallel color/icon/route/use-case/rules/chip/tooltip helpers from main.gd.",
	},
	{
		"id": "card_play_eligibility_runtime_service_owned",
		"display_name": "Card Play Eligibility Runtime Ownership",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardPlayEligibilityRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/card_play_eligibility_runtime_service.gd", "res://scenes/runtime/CardPlayEligibilityWorldBridge.tscn", "res://scenes/runtime/GameRuntimeCoordinator.tscn", "res://scenes/tools/CardPlayEligibilityRuntimeBench.tscn", "res://docs/card_play_eligibility_runtime_contract.md", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": ["evaluate_play", "evaluate_hand", "requirement_status", "target_status", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_qa_scene",
		"risk_level": "high",
		"recommended_next_step": "Keep eligibility single-owned and begin Monster Runtime Hard Cutover as a separately characterized domain.",
		"mcp_notes": "Sprint 43 passes 46/46. main.gd retains only narrow fact/action adapters; Queue, Execution, Presentation, and effects remain bounded sibling owners.",
	},
	{
		"id": "game_table_viewmodel_runtime_service_owned",
		"display_name": "Game Table ViewModel Runtime Service Ownership",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/GameTableViewModelRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/game_table_viewmodel_runtime_service.gd", "res://scripts/viewmodels/table_snapshot.gd", "res://scenes/runtime/GameRuntimeCoordinator.tscn", "res://scenes/ui/GameScreen.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": ["compose_table_source", "compose_table", "compose_card_surfaces", "debug_snapshot"],
		"editor_visibility": "scene_tree",
		"risk_level": "high",
		"recommended_next_step": "Keep hand, public track, CardResolutionTrack, and RightInspector precedence in one pure-data service.",
		"mcp_notes": "Sprint 42 removes TableSnapshot, hand/track snapshot, and RightInspector assembly ownership from main.gd while preserving action ids and privacy.",
	},
	{
		"id": "district_supply_drawer_scene_owned",
		"display_name": "District Supply Drawer Scene Ownership",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/ui/DistrictSupplyDrawer.tscn",
		"related_paths": ["res://scenes/ui/DistrictSupplyDrawer.tscn", "res://scripts/ui/district_supply_drawer.gd", "res://scenes/runtime/DistrictSupplySnapshotService.tscn", "res://scripts/runtime/district_supply_snapshot_service.gd", "res://scenes/ui/DistrictSupplyMarketCard.tscn", "res://scenes/ui/DistrictSupplyPreviewCard.tscn", "res://scenes/ui/DistrictPurchaseWindowStatus.tscn", "res://scenes/tools/DistrictPurchaseRuntimeCutoverBench.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": ["set_supply", "clear_supply", "debug_snapshot", "supply_action_requested"],
		"editor_visibility": "scene_tree",
		"risk_level": "medium",
		"recommended_next_step": "Keep purchase qualification in DistrictPurchaseRuntimeController, formatting in DistrictSupplySnapshotService, and Drawer presentation scene-owned; use the completed Sprint 28 contract for settlement cutover.",
		"mcp_notes": "Sprint 28 preserves the nineteen retired formatters and expands the existing gate to 45 ownership plus 17 characterization cases.",
	},
	{
		"id": "district_supply_snapshot_service_owned",
		"display_name": "District Supply Snapshot Service Ownership",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/DistrictSupplySnapshotService.tscn",
		"related_paths": ["res://scripts/runtime/district_supply_snapshot_service.gd", "res://scenes/runtime/GameRuntimeCoordinator.tscn", "res://scripts/runtime/game_runtime_coordinator.gd", "res://scenes/ui/DistrictSupplyDrawer.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": ["compose", "validate_source", "debug_snapshot", "compose_district_supply_snapshot"],
		"editor_visibility": "scene_tree",
		"risk_level": "medium",
		"recommended_next_step": "Keep source facts bounded and pure; do not move eligibility, price, cash, inventory, upgrade, or private discard rules into this formatting service.",
		"mcp_notes": "Drawer presentation formatting has left main.gd. The service rejects runtime objects and private owner, hand-card, channel-source, plan, target, and discard fields.",
	},
	{
		"id": "district_purchase_settlement_characterized",
		"display_name": "District Purchase Settlement Runtime Service",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/DistrictPurchaseSettlementRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/district_purchase_settlement_runtime_service.gd", "res://scenes/runtime/GameRuntimeCoordinator.tscn", "res://scripts/runtime/game_runtime_coordinator.gd", "res://docs/district_purchase_settlement_contract.md", "res://scenes/tools/DistrictPurchaseRuntimeCutoverBench.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": ["plan_purchase", "commit_purchase", "validate_discard", "set_inventory_service", "debug_snapshot"],
		"editor_visibility": "scene_tree",
		"risk_level": "high",
		"recommended_next_step": "Keep purchase mutation single-owned here; main.gd may retain only world-fact collection, Controller authorization, Overlay orchestration, and post-commit event forwarding.",
		"mcp_notes": "Sprint 29 cutover passes 80/80. Player, AI, Coach, and resumed discard share the same plan/commit path; no legacy settlement formula remains in main.gd.",
	},
	{
		"id": "shared_card_inventory_mutation_characterized",
		"display_name": "Card Inventory Runtime Service",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardInventoryRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/card_inventory_runtime_service.gd", "res://scenes/runtime/GameRuntimeCoordinator.tscn", "res://scripts/runtime/district_purchase_settlement_runtime_service.gd", "res://scripts/main.gd", "res://scenes/tools/CardInventoryRuntimeCharacterizationBench.tscn", "res://docs/card_inventory_runtime_contract.md"],
		"function_count": 0,
		"key_functions": ["plan_receive", "commit_receive", "discardable_slots", "plan_remove", "commit_remove", "plan_lock", "commit_lock", "plan_transfer", "commit_transfer", "inventory_fingerprint", "debug_snapshot"],
		"editor_visibility": "scene_tree",
		"risk_level": "high",
		"recommended_next_step": "Keep all slot mutation in CardInventoryRuntimeService; characterize card-effect orchestration or AI ownership before moving any higher-level sequencing out of main.gd.",
		"mcp_notes": "Sprint 31 passes the 40/40 gate. Purchase settlement delegates inventory but retains cash/ledger/counter atomicity; main retains choice, compensation, and event forwarding only.",
	},
	{
		"id": "player_hand_interaction_orchestration_characterized",
		"display_name": "Player Hand Interaction Orchestration",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/PlayerHandInteractionRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/player_hand_interaction_runtime_service.gd", "res://scenes/runtime/GameRuntimeCoordinator.tscn", "res://scenes/tools/PlayerHandInteractionRuntimeCharacterizationBench.tscn", "res://scenes/runtime/CardInventoryRuntimeService.tscn", "res://docs/player_hand_interaction_runtime_contract.md"],
		"function_count": 0,
		"key_functions": ["plan_interaction", "commit_interaction", "debug_snapshot"],
		"editor_visibility": "scene_tree",
		"risk_level": "high",
		"recommended_next_step": "Keep interaction orchestration single-owned in the scene service and move to the next characterized main.gd ownership boundary.",
		"mcp_notes": "Sprint 33 passes the 40/40 gate. CardInventoryRuntimeService owns slot mutation; main.gd is limited to world facts, seeded slot choices, and private/public presentation forwarding.",
	},
	{
		"id": "card_resolution_queue_lifecycle_characterized",
		"display_name": "Card Resolution Queue Lifecycle",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardResolutionQueueRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/card_resolution_queue_runtime_service.gd", "res://scenes/runtime/CardResolutionRuntimeController.tscn", "res://scenes/runtime/CardInventoryRuntimeService.tscn", "res://scripts/cards/shared_card_group_window.gd", "res://scenes/tools/CardResolutionQueueRuntimeCharacterizationBench.tscn", "res://docs/card_resolution_queue_ownership_boundary.md"],
		"function_count": 0,
		"key_functions": ["plan_submission", "commit_submission", "lock_batch", "start_next", "complete_active", "promote_next_batch", "to_legacy_save_snapshot", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_qa_scene",
		"risk_level": "high",
		"recommended_next_step": "Keep queue lifecycle single-owned in the service; characterize the next main.gd domain without moving timing, card effects, inventory, or cash into this owner.",
		"mcp_notes": "Sprint 35 passes 28/28 characterization plus 28/28 cutover. CardResolutionRuntimeController owns timing, CardInventoryRuntimeService owns slots, and main.gd forwards real-world facts and existing events.",
	},
	{
		"id": "card_resolution_execution_orchestration_characterized",
		"display_name": "Card Resolution Execution Orchestration",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardResolutionExecutionRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/card_resolution_execution_runtime_service.gd", "res://scenes/tools/CardResolutionExecutionRuntimeCharacterizationBench.tscn", "res://scripts/tools/card_resolution_execution_runtime_characterization_bench.gd", "res://docs/card_resolution_execution_runtime_contract.md", "res://scenes/runtime/CardResolutionQueueRuntimeService.tscn", "res://scenes/runtime/CardResolutionRuntimeController.tscn"],
		"function_count": 0,
		"key_functions": ["plan_execution", "advance_execution", "finalize_execution", "recover_from_active", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_qa_scene",
		"risk_level": "high",
		"recommended_next_step": "Keep lifecycle stable and formula-agnostic while sibling effect and formula services evolve independently.",
		"mcp_notes": "Sprint 40 leaves this service unchanged. It owns generic intent order only and contains no product, contract, city, demand, insurance, futures, GDP, or route arithmetic.",
	},
	{
		"id": "card_economy_product_route_effect_family_sceneized",
		"display_name": "Economy / Product / Route Card Effect Family",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardEconomyProductRouteEffectRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/card_economy_product_route_effect_runtime_service.gd", "res://scenes/runtime/CardEconomyProductRouteEffectWorldBridge.tscn", "res://scripts/runtime/card_economy_product_route_effect_world_bridge.gd", "res://scenes/tools/CardResolutionExecutionRuntimeCharacterizationBench.tscn", "res://docs/card_economy_product_route_effect_runtime_contract.md"],
		"function_count": 0,
		"key_functions": ["supports_handler", "family_for_handler", "plan_effect", "finalize_effect", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_execution_qa",
		"risk_level": "high",
		"recommended_next_step": "Keep handler registration and result envelopes here; route additional characterized arithmetic to the sibling Formula Service without widening this boundary.",
		"mcp_notes": "Sprint 40 keeps all seventeen handlers here while the sibling service grows to nineteen deterministic formulas. Execution Service remains unaware of card families and formulas.",
	},
	{
		"id": "card_economy_product_route_formula_sceneized",
		"display_name": "Economy / Product / Route Pure Formulas",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CardEconomyProductRouteFormulaRuntimeService.tscn",
		"related_paths": ["res://scripts/runtime/card_economy_product_route_formula_runtime_service.gd", "res://tests/card_economy_product_route_formula_runtime_service_test.gd", "res://scenes/tools/CardResolutionExecutionRuntimeCharacterizationBench.tscn", "res://docs/card_economy_product_route_formula_runtime_contract.md", "res://scripts/balance/runtime_balance_model.gd", "res://scenes/runtime/GdpFormulaRuntimeController.tscn"],
		"function_count": 0,
		"key_functions": ["supported_formulas", "supports_formula", "calculate", "formula_ownership_snapshot", "debug_snapshot"],
		"editor_visibility": "scene_tree_and_execution_qa",
		"risk_level": "high",
		"recommended_next_step": "Characterize market stabilization, regional economy shifts, and route sabotage next; retain product price, city GDP, RNG selection, and world mutation in their current owners.",
		"mcp_notes": "Sprint 40 owns nineteen deterministic formula operations. Contract/city-product/demand/insurance arithmetic is pure, while candidate RNG and world mutation remain outside the service.",
	},
	{
		"id": "planet_map_control_toolbar_sceneized",
		"display_name": "Planet Map Control Toolbar Sceneized",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/ui/map/PlanetMapControlToolbar.tscn",
		"related_paths": ["res://scenes/ui/map/PlanetMapControlToolbar.tscn", "res://scenes/ui/FullscreenMapOverlay.tscn", "res://scenes/tools/PlanetMapInteractionBench.tscn", "res://scripts/main.gd"],
		"function_count": 0,
		"key_functions": ["set_controls", "debug_snapshot", "control_action_requested"],
		"editor_visibility": "scene_tree",
		"risk_level": "low",
		"recommended_next_step": "Keep fullscreen map controls in the toolbar scene and route future map commands through pure action payloads; do not restore main.gd Button or OptionButton builders.",
		"mcp_notes": "Sprint 25 retires three map-control builders, thirteen mirrored Node arrays, and their refresh loops. PlanetMapInteractionBench must remain 15/15.",
	},
	{
		"id": "product_market_runtime_characterization_gate",
		"display_name": "Product Market & Futures Runtime",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/ProductMarketRuntimeController.tscn",
		"runtime_owner": "res://scripts/runtime/product_market_runtime_controller.gd",
		"related_paths": ["res://scenes/runtime/ProductMarketRuntimeController.tscn", "res://scenes/runtime/ProductMarketRuntimeWorldBridge.tscn", "res://scenes/tools/ProductMarketRuntimeCharacterizationBench.tscn", "res://scripts/tools/product_market_runtime_characterization_bench.gd", "res://scripts/finance/product_futures_terms_resource.gd", "res://scripts/finance/product_futures_terms_catalog_resource.gd", "res://resources/finance/product_futures/product_futures_terms_v04_catalog.tres", "res://docs/product_market_runtime_ownership_contract.md", "res://docs/product_futures_v04_terms_contract.md", "res://docs/product_futures_v04_design_decisions.md", "res://scenes/runtime/CardEconomyProductRouteFormulaRuntimeService.tscn", "res://scenes/runtime/EconomyCashflowRuntimeController.tscn", "res://scenes/runtime/GdpFormulaRuntimeController.tscn", "res://scenes/runtime/AiRuntimeController.tscn", "res://scenes/runtime/ProductCodexPublicSnapshotService.tscn"],
		"function_count": 23,
		"key_functions": ["generate_product_market", "refresh_prices", "age_economic_boons", "apply_futures", "update_futures_timers", "market_tick"],
		"editor_visibility": "scene_tree_and_real_main_cutover_bench",
		"risk_level": "medium",
		"recommended_next_step": "Proceed to City GDP Derivative v0.4 Terms Alignment while preserving this Resource-backed market owner.",
		"mcp_notes": "Sprint 55 reports 100/100 records and 76/76 live aligned. The twelve Inspector Resources are the single terms source; no legacy financial fallback remains.",
	},
	{
		"id": "city_gdp_derivative_v04_terms_gate",
		"display_name": "City GDP Derivative v0.4 Runtime",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CityGdpDerivativeRuntimeController.tscn",
		"runtime_owner": "res://scripts/runtime/city_gdp_derivative_runtime_controller.gd",
		"related_paths": ["res://scenes/runtime/CityGdpDerivativeRuntimeController.tscn", "res://scenes/runtime/CityGdpDerivativeRuntimeWorldBridge.tscn", "res://scenes/tools/CityGdpDerivativeRuntimeBench.tscn", "res://scripts/finance/city_gdp_derivative_terms_resource.gd", "res://scripts/finance/city_gdp_derivative_terms_catalog_resource.gd", "res://resources/finance/city_gdp_derivatives/city_gdp_derivative_terms_v04_catalog.tres", "res://docs/city_gdp_derivative_v04_terms_contract.md"],
		"function_count": 0,
		"key_functions": ["open_position", "settle_district", "settle_destroyed_city", "apply_save_data"],
		"editor_visibility": "scene_tree_resource_catalog_and_runtime_bench",
		"risk_level": "medium",
		"recommended_next_step": "Keep the terms catalog and 40-case exact-once gate as the only runtime financial source; do not restore city-embedded gdp_derivatives.",
		"mcp_notes": "Queue authorizes funds, Effect open locks margin, the Controller owns positions and settlement, and main.gd only supplies world facts/mutations.",
	},
	{
		"id": "runtime_card_catalog_source_of_truth",
		"display_name": "Runtime Card Catalog Source of Truth",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_RESOURCE_ASSET,
		"current_path": "res://resources/cards/runtime/card_runtime_catalog_v04.tres",
		"runtime_owner": "res://scripts/runtime/card_runtime_catalog_service.gd",
		"related_paths": ["res://scenes/runtime/CardRuntimeCatalogService.tscn", "res://scenes/runtime/CardRuntimeDefinitionWorldBridge.tscn", "res://resources/cards/runtime/families", "res://resources/cards/runtime/packs", "res://scenes/tools/RuntimeCardCatalogResourceBench.tscn", "res://scenes/tools/RuntimeCardAuthoringWorkspace.tscn", "res://scenes/tools/RuntimeCardAuthoringWorkflowBench.tscn", "res://scripts/cards/card_runtime_authoring_validator.gd", "res://scripts/cards/card_runtime_change_review_service.gd", "res://docs/runtime_card_catalog_ownership_contract.md", "res://docs/runtime_card_catalog_resource_schema.md", "res://docs/runtime_card_authoring_workflow.md"],
		"function_count": 0,
		"key_functions": ["CardRuntimeCatalogResource.definition", "CardRuntimeCatalogResource.derived_definition", "CardRuntimeDefinitionWorldBridge.resolve_definition"],
		"editor_visibility": "custom_inspector_resource_graph_authoring_workspace_change_review_80_case_runtime_gate_and_36_case_authoring_gate",
		"risk_level": "medium",
		"recommended_next_step": "Author new ranks and families through the Sprint 59 Inspector workflow, then run both the 36-case authoring gate and 80-case runtime catalog gate before content review.",
		"mcp_notes": "The authoritative catalog is Resource-backed and runtime_cutover_enabled. Sprint 59 is editor-only and writes baseline/review artifacts to user://; it does not introduce a second runtime source. Compendium remains presentation-only; Product Futures, City GDP, and Monster dynamic definitions remain external owners rather than fallbacks.",
	},
	{
		"id": "ruleset_v05_data_foundation",
		"display_name": "Ruleset v0.5 Data Foundation",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_RESOURCE_ASSET,
		"current_path": "res://resources/rules/space_syndicate_ruleset_v05.tres",
		"runtime_owner": "inactive_until_v05_hard_cutover",
		"related_paths": ["res://resources/content/product_industry_catalog_v05.tres", "res://resources/cards/runtime/card_runtime_catalog_v05.tres", "res://resources/rules/clock_domain_registry_v05.tres", "res://scenes/runtime/RulesetSaveHandshakeService.tscn", "res://scenes/tools/RulesetV05FoundationBench.tscn"],
		"function_count": 0,
		"key_functions": ["validation_snapshot", "validate_catalog", "validate_payload", "inspect_envelope"],
		"editor_visibility": "inspector_resources_passive_service_and_56_case_foundation_gate",
		"risk_level": "high",
		"recommended_next_step": "Keep the global v0.5 profile and card catalog inactive while SS05-03 consumes the completed project-slot contract for structured GDP.",
		"mcp_notes": "Data layer ready, runtime inactive. Production RulesetRuntimeBridge and CardRuntimeCatalogService still point exclusively to v0.4 assets.",
	},
	{
		"id": "player_text_v05_foundation",
		"display_name": "Player-Facing Text v0.5 Foundation",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_RESOURCE_ASSET,
		"current_path": "res://resources/localization/player_text_schema_v05.tres",
		"runtime_owner": "inactive_until_v05_domain_text_cutovers",
		"related_paths": ["res://scripts/presentation/player_text_spec_v05.gd", "res://scripts/presentation/player_text_visibility_contract_v05.gd", "res://scripts/presentation/player_text_locale_resolver_v05.gd", "res://resources/localization/unit_display_catalog_v05.tres", "res://localization/v05/player_text_zh_Hans.po", "res://resources/migrations/card_text_v04_to_v05_registry.tres", "res://scenes/tools/PlayerTextV05FoundationBench.tscn"],
		"function_count": 0,
		"key_functions": ["validate_spec", "authorize", "resolve", "sanitize", "format_numeric_value"],
		"editor_visibility": "inspector_resources_po_catalog_and_48_case_foundation_gate",
		"risk_level": "high",
		"recommended_next_step": "Keep locale resolution inactive; consume the project summary keys only after the domain visibility owner has authorized their arguments.",
		"mcp_notes": "Foundation ready, runtime inactive. No production text selector or fallback exists, and all 239 legacy card rules_text records remain explicitly inventoried rather than silently rewritten.",
	},
	{
		"id": "city_trade_network_characterization_gate",
		"display_name": "City / Trade Network Runtime Ownership",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCRIPT_MODULE,
		"current_path": "res://scripts/runtime/city_trade_network_runtime_controller.gd",
		"runtime_owner": "res://scripts/runtime/city_trade_network_runtime_controller.gd",
		"related_paths": ["res://scenes/runtime/CityTradeNetworkRuntimeController.tscn", "res://scenes/runtime/CityTradeNetworkWorldBridge.tscn", "res://scenes/tools/CityTradeNetworkRuntimeCharacterizationBench.tscn", "res://docs/city_trade_network_runtime_ownership_contract.md", "res://scripts/economy/city_product_project_state.gd", "res://scripts/economy/city_product_project_bridge.gd", "res://scripts/economy/city_project_state_migration_v04_to_v05.gd", "res://scenes/runtime/GdpFormulaRuntimeController.tscn", "res://scenes/runtime/EconomyCashflowRuntimeController.tscn"],
		"function_count": 31,
		"key_functions": ["refresh_networks", "shortest_trade_path", "trade_path_cost", "settle_cashflow_seconds", "apply_save_data"],
		"editor_visibility": "static_runtime_scenes_88_case_ss05_02_real_main_gate_and_contract",
		"risk_level": "medium",
		"recommended_next_step": "Use the stable five-slot identity and generation contract as the input boundary for SS05-03 structured GDP rows.",
		"mcp_notes": "SS05-02 is cutover complete at 88/88. The Controller uniquely owns five-slot identity, rank IV, generation/tombstones, project shares, route derivation, and its save envelope; GDP formulas and cashflow arithmetic remain external owners.",
	},
	{
		"id": "city_development_settlement_characterization_gate",
		"display_name": "City Development Settlement Runtime Ownership",
		"category": CATEGORY_RUNTIME_FALLBACKS,
		"current_status": STATUS_SCENEIZED,
		"current_path": "res://scenes/runtime/CityDevelopmentRuntimeController.tscn",
		"runtime_owner": "res://scripts/runtime/city_development_runtime_controller.gd",
		"related_paths": ["res://scenes/runtime/CityDevelopmentWorldBridge.tscn", "res://scenes/tools/CityDevelopmentSettlementRuntimeCharacterizationBench.tscn", "res://docs/city_development_settlement_runtime_contract.md", "res://scripts/economy/city_product_project_state.gd", "res://scripts/economy/city_product_project_bridge.gd", "res://scenes/runtime/CityTradeNetworkRuntimeController.tscn"],
		"function_count": 0,
		"key_functions": ["plan_settlement", "validate_settlement_plan", "finalize_settlement", "apply_settlement_plan"],
		"editor_visibility": "controller_world_bridge_64_case_real_main_gate_and_contract",
		"risk_level": "medium",
		"recommended_next_step": "Keep the authoritative settlement boundary stable and continue the next main.gd ownership cutover.",
		"mcp_notes": "Sprint 66 reports 64/64 observed and aligned. main.gd has no parallel city-development settlement body or reflected test wrapper.",
	},
]


func categories() -> Array[String]:
	var result: Array[String] = []
	for category in CATEGORY_ORDER:
		result.append(str(category))
	return result


func records() -> Array:
	return _duplicate_records(RECORDS)


func records_for_category(category: String) -> Array:
	var result: Array = []
	for record_variant in RECORDS:
		var record: Dictionary = record_variant if record_variant is Dictionary else {}
		if str(record.get("category", "")) == category:
			result.append(record.duplicate(true))
	return result


func record_for_id(id: String) -> Dictionary:
	for record_variant in RECORDS:
		var record: Dictionary = record_variant if record_variant is Dictionary else {}
		if str(record.get("id", "")) == id:
			return record.duplicate(true)
	return {}


func summary() -> Dictionary:
	var category_counts := {}
	var status_counts := {}
	for category in CATEGORY_ORDER:
		category_counts[category] = records_for_category(category).size()
	for record_variant in RECORDS:
		var record: Dictionary = record_variant if record_variant is Dictionary else {}
		var status := str(record.get("current_status", ""))
		status_counts[status] = int(status_counts.get(status, 0)) + 1
	return {
		"total": RECORDS.size(),
		"categories": category_counts,
		"statuses": status_counts,
	}


func _duplicate_records(source: Array) -> Array:
	var result: Array = []
	for record_variant in source:
		var record: Dictionary = record_variant if record_variant is Dictionary else {}
		result.append(record.duplicate(true))
	return result
