extends Node
class_name WeatherBalanceReportV1Bench

const TELEMETRY_SERVICE := preload("res://scripts/runtime/weather_telemetry_runtime_service.gd")
const WEATHER_CATALOG := preload("res://resources/weather/weather_definition_catalog_v1.tres")
const REPORT_PATH := "res://docs/weather_v1_balance_report.md"
const SAMPLE_INTERVENTIONS := [
	{"weather_resistance": 0.0, "weather_exploitation_multiplier": 1.0},
	{"weather_resistance": 0.25, "weather_exploitation_multiplier": 1.0},
	{"weather_resistance": 0.0, "weather_exploitation_multiplier": 1.25},
]

@export var auto_run := true

@onready var telemetry: WeatherTelemetryRuntimeService = $WeatherTelemetryRuntimeService

var _last_result := {}


func _ready() -> void:
	if auto_run and not Engine.is_editor_hint():
		call_deferred("_run_automatically")


func run_bench(write_report: bool = true) -> Dictionary:
	telemetry.clear()
	var accepted := _record_simulation_samples()
	var aggregates := telemetry.aggregate_snapshot()
	var report := build_report_markdown(aggregates)
	var report_written := not write_report or _write_report(report)
	var definition_rows: Array = aggregates.get("definitions", []) as Array
	var passed := accepted == 54 \
		and int(aggregates.get("completed_event_count", 0)) == 18 \
		and definition_rows.size() == 6 \
		and report_written
	_last_result = {
		"bench_complete": true,
		"status": "PASS" if passed else "FAIL",
		"accepted_lifecycle_events": accepted,
		"completed_samples": int(aggregates.get("completed_event_count", 0)),
		"definition_count": definition_rows.size(),
		"report_path": REPORT_PATH,
		"report_written": report_written,
		"report_markdown": report,
		"aggregates": aggregates,
		"telemetry_debug": telemetry.debug_snapshot(),
	}
	return _last_result.duplicate(true)


func build_report_markdown(aggregates: Dictionary) -> String:
	var lines: Array[String] = [
		"# Weather v1 Balance Report",
		"",
		"> Evidence class: deterministic, resolver-backed acceptance samples generated by `WeatherBalanceReportV1Bench`. This is not a live-player telemetry export.",
		"",
		"## Scope and method",
		"",
		"- The bench records 18 completed samples: three for each of the six canonical Weather v1 definitions.",
		"- Every sample uses the production `WeatherEffectResolver`, authored durations, one deterministic region, and one of three public intervention profiles: baseline, 25% resistance, or 1.25x exploitation.",
		"- `Price growth` is the scoped weather contribution before the existing market cap; it is not final product price. `Route efficiency` is effective capacity, not route revenue.",
		"- `Monster target scoring influenced` means the selected region can receive a tag-matched weather preference bonus. It does not expose or claim a counterfactual target identity.",
		"- Realized currency remains `N/A` in this deterministic acceptance sample because it does not fabricate commodity sales. Production telemetry can derive an anonymous conservative estimate from committed public commodity-flow receipts, but never stores player identity/index, owner, exact cash, hand/discard, hidden target/weights, AI plan, save state, or camera state.",
		"",
		"## Definition results",
		"",
		"| Definition | Samples | Hit regions | Avg forecast / active / fade (s) | Avg price-growth contribution | Avg route-efficiency contribution | Responses (route / buy / build / play) | Monster target scoring influenced | Total applied region damage units | Realized currency delta |",
		"|---|---:|---|---:|---:|---:|---:|---:|---:|---:|",
	]
	var definitions: Array = aggregates.get("definitions", []) as Array
	for definition_variant in definitions:
		var row := definition_variant as Dictionary
		var responses: Dictionary = row.get("player_response_counts", {}) as Dictionary
		lines.append("| %s (`%s`) | %d | %s | %.2f / %.2f / %.2f | %s | %s | %d / %d / %d / %d | %d/%d (%.2f%%) | %.2f | N/A |" % [
			str(row.get("display_name", "")),
			str(row.get("definition_id", "")),
			int(row.get("event_count", 0)),
			_hit_regions(row),
			float(row.get("average_forecast_duration_seconds", 0.0)),
			float(row.get("average_active_duration_seconds", 0.0)),
			float(row.get("average_fade_duration_seconds", 0.0)),
			_signed_percent(float(row.get("average_product_price_growth_delta_percent", 0.0))),
			_signed_percent(float(row.get("average_route_efficiency_delta_percent", 0.0))),
			int(responses.get("route_after_forecast", 0)),
			int(responses.get("buy_after_forecast", 0)),
			int(responses.get("build_after_forecast", 0)),
			int(responses.get("play_after_forecast", 0)),
			int(row.get("monster_target_weather_influenced_count", 0)),
			int(row.get("event_count", 0)),
			float(row.get("monster_target_weather_influenced_rate", 0.0)) * 100.0,
			float(row.get("region_damage_total", 0.0)),
		])
	lines.append_array([
		"",
		"## Per-region evidence",
		"",
		"| Definition | Region | Samples | Avg forecast / active / fade (s) | Avg price-growth contribution | Avg route-efficiency contribution | Monster target scoring influenced | Total applied region damage units | Realized currency delta |",
		"|---|---:|---:|---:|---:|---:|---:|---:|---:|",
	])
	for definition_variant in definitions:
		var definition_row := definition_variant as Dictionary
		for region_variant in definition_row.get("regions", []):
			var region := region_variant as Dictionary
			lines.append("| `%s` | R%02d | %d | %.2f / %.2f / %.2f | %s | %s | %d/%d (%.2f%%) | %.2f | N/A |" % [
				str(region.get("definition_id", "")),
				int(region.get("region_index", -1)),
				int(region.get("event_count", 0)),
				float(region.get("average_forecast_duration_seconds", 0.0)),
				float(region.get("average_active_duration_seconds", 0.0)),
				float(region.get("average_fade_duration_seconds", 0.0)),
				_signed_percent(float(region.get("average_product_price_growth_delta_percent", 0.0))),
				_signed_percent(float(region.get("average_route_efficiency_delta_percent", 0.0))),
				int(region.get("monster_target_weather_influenced_count", 0)),
				int(region.get("event_count", 0)),
				float(region.get("monster_target_weather_influenced_rate", 0.0)) * 100.0,
				float(region.get("region_damage_total", 0.0)),
			])
	lines.append_array([
		"",
		"## Reading the sample",
		"",
		"Positive and negative percentages are scoped resolver contributions, not realized currency. Crystal-dust damage is the total nonlethal integer amount expected from the production active-plus-linear-fade integral. Anonymous realized-flow estimates are covered by the production telemetry integration gate rather than invented in this fixture. The report is deterministic, so changes between runs represent authored definitions or resolver behavior rather than random sampling noise.",
		"",
	])
	return "\n".join(lines)


func debug_snapshot() -> Dictionary:
	return _last_result.duplicate(true)


func _run_automatically() -> void:
	var result := run_bench(true)
	print("WEATHER_BALANCE_REPORT_V1_BENCH|status=%s|samples=%d|definitions=%d|report=%s" % [
		str(result.get("status", "FAIL")),
		int(result.get("completed_samples", 0)),
		int(result.get("definition_count", 0)),
		REPORT_PATH,
	])
	if DisplayServer.get_name() == "headless":
		get_tree().quit(0 if str(result.get("status", "")) == "PASS" else 1)


func _record_simulation_samples() -> int:
	var accepted := 0
	var resolver := WeatherEffectResolver.new()
	var event_id := 1
	for definition_id_variant in TELEMETRY_SERVICE.DEFINITION_IDS:
		var definition_id := str(definition_id_variant)
		var definition: WeatherDefinition = WEATHER_CATALOG.definition(definition_id)
		for sample_index in range(3):
			var region_index := (TELEMETRY_SERVICE.DEFINITION_IDS.find(definition_id) + sample_index) % 6
			var intervention := SAMPLE_INTERVENTIONS[sample_index] as Dictionary
			var route_mode := _representative_route_mode(definition_id)
			var effect := resolver.resolve(definition, WeatherRuntimeState.PHASE_ACTIVE, 1.0, {
				"product_tags": Array(definition.product_tags),
				"monster_tags": Array(definition.monster_preference_tags),
				"route_mode": route_mode,
				"movement_domain": route_mode,
				"context_tags": ["city", "maintenance", "intel"],
				"intel_domain": definition.intel_effect_domain,
				"weather_resistance": float(intervention.get("weather_resistance", 0.0)),
				"weather_exploitation_multiplier": float(intervention.get("weather_exploitation_multiplier", 1.0)),
			})
			accepted += int(telemetry.begin_weather_session(event_id, definition_id, [region_index], definition.forecast_duration, definition.active_duration, definition.fade_duration))
			accepted += int(telemetry.activate_weather_session(event_id))
			telemetry.observe_public_metric(event_id, "product_price_growth_delta_percent", _product_price_growth_delta(effect))
			telemetry.observe_public_metric(event_id, "route_efficiency_delta_percent", _route_efficiency_delta(effect, route_mode))
			telemetry.observe_public_metric(event_id, "region_damage", _expected_applied_region_damage(effect, definition))
			if float((effect.get("monster", {}) as Dictionary).get("preference_multiplier", 1.0)) > 1.0:
				telemetry.mark_monster_target_weather_influenced(event_id)
			accepted += int(telemetry.finish_weather_session(event_id))
			event_id += 1
	return accepted


func _product_price_growth_delta(effect: Dictionary) -> float:
	var multiplier := clampf(float((effect.get("economy", {}) as Dictionary).get("price_growth_multiplier", 1.0)), 0.70, 1.30)
	return (multiplier - 1.0) * 100.0


func _route_efficiency_delta(effect: Dictionary, route_mode: String) -> float:
	var route := effect.get("route", {}) as Dictionary
	var multiplier := float(route.get("generic_multiplier", 1.0))
	if ["land", "ocean", "air"].has(route_mode):
		multiplier *= float(route.get("%s_multiplier" % route_mode, 1.0))
	return (maxf(0.40, multiplier) - 1.0) * 100.0


func _expected_applied_region_damage(effect: Dictionary, definition: WeatherDefinition) -> float:
	var damage_per_second := maxf(0.0, float((effect.get("damage", {}) as Dictionary).get("per_second", 0.0)))
	return float(floori(damage_per_second * (definition.active_duration + definition.fade_duration * 0.5) + 0.000001))


func _representative_route_mode(definition_id: String) -> String:
	match definition_id:
		"ion_storm": return "air"
		"gravity_tide": return "ocean"
		"deep_freeze": return "land"
	return "generic"


func _hit_regions(row: Dictionary) -> String:
	var labels: Array[String] = []
	for region_variant in row.get("regions", []):
		labels.append("R%02d" % int((region_variant as Dictionary).get("region_index", -1)))
	return ", ".join(labels) if not labels.is_empty() else "none"


func _signed_percent(value: float) -> String:
	return "%+.2f%%" % value


func _write_report(report: String) -> bool:
	var file := FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("WEATHER BALANCE REPORT: cannot write %s" % REPORT_PATH)
		return false
	file.store_string(report)
	return true
