extends Node
class_name WeatherBalanceReportV1Bench

const TELEMETRY_SERVICE := preload("res://scripts/runtime/weather_telemetry_runtime_service.gd")
const WEATHER_CATALOG := preload("res://resources/weather/weather_definition_catalog_v1.tres")
const REPORT_PATH := "res://docs/weather_v1_balance_report.md"

const PROFILE_BY_DEFINITION := {
	"ion_storm": {
		"regions": [0, 1, 0],
		"price": [18.0, 20.0, 22.0],
		"route": [16.0, 18.0, 20.0],
		"responses": ["route_after_forecast", "buy_after_forecast", "play_after_forecast"],
		"monster": [true, false, true],
		"damage": [0.0, 0.0, 0.0],
		"economic": [120.0, 160.0, 200.0],
	},
	"gravity_tide": {
		"regions": [2, 3, 2],
		"price": [-1.0, 0.0, 1.0],
		"route": [-27.0, -25.0, -23.0],
		"responses": ["route_after_forecast", "build_after_forecast", "route_after_forecast"],
		"monster": [false, true, false],
		"damage": [0.0, 0.0, 0.0],
		"economic": [-240.0, -220.0, -200.0],
	},
	"spore_season": {
		"regions": [1, 4, 4],
		"price": [13.0, 15.0, 17.0],
		"route": [-10.0, -8.0, -6.0],
		"responses": ["buy_after_forecast", "build_after_forecast", "buy_after_forecast"],
		"monster": [true, true, false],
		"damage": [0.0, 0.0, 0.0],
		"economic": [70.0, 90.0, 110.0],
	},
	"crystal_dust_storm": {
		"regions": [3, 5, 3],
		"price": [16.0, 18.0, 20.0],
		"route": [-14.0, -12.0, -10.0],
		"responses": ["play_after_forecast", "route_after_forecast", "build_after_forecast"],
		"monster": [false, true, false],
		"damage": [1.06, 1.10, 1.14],
		"economic": [-90.0, -70.0, -50.0],
	},
	"deep_freeze": {
		"regions": [0, 2, 5],
		"price": [14.0, 16.0, 18.0],
		"route": [-32.0, -30.0, -28.0],
		"responses": ["buy_after_forecast", "build_after_forecast", "route_after_forecast"],
		"monster": [true, false, true],
		"damage": [0.0, 0.0, 0.0],
		"economic": [-280.0, -260.0, -240.0],
	},
	"solar_flare": {
		"regions": [1, 3, 5],
		"price": [23.0, 25.0, 27.0],
		"route": [-17.0, -15.0, -13.0],
		"responses": ["play_after_forecast", "buy_after_forecast", "play_after_forecast"],
		"monster": [true, true, true],
		"damage": [0.0, 0.0, 0.0],
		"economic": [-130.0, -110.0, -90.0],
	},
}

@export var auto_run := true

@onready var telemetry: WeatherTelemetryRuntimeService = $WeatherTelemetryRuntimeService

var _last_result := {}


func _ready() -> void:
	if auto_run and not Engine.is_editor_hint():
		call_deferred("_run_automatically")


func run_bench(write_report: bool = true) -> Dictionary:
	telemetry.clear()
	var accepted := _record_simulation_samples()
	var aggregates := telemetry.aggregate_snapshot()
	var report := build_report_markdown(aggregates)
	var report_written := not write_report or _write_report(report)
	var definition_rows: Array = aggregates.get("definitions", []) as Array
	var passed := accepted == 54 \
		and int(aggregates.get("completed_event_count", 0)) == 18 \
		and definition_rows.size() == 6 \
		and report_written
	_last_result = {
		"bench_complete": true,
		"status": "PASS" if passed else "FAIL",
		"accepted_lifecycle_events": accepted,
		"completed_samples": int(aggregates.get("completed_event_count", 0)),
		"definition_count": definition_rows.size(),
		"report_path": REPORT_PATH,
		"report_written": report_written,
		"report_markdown": report,
		"aggregates": aggregates,
		"telemetry_debug": telemetry.debug_snapshot(),
	}
	return _last_result.duplicate(true)


func build_report_markdown(aggregates: Dictionary) -> String:
	var lines: Array[String] = [
		"# Weather v1 Balance Report",
		"",
		"> Evidence class: deterministic sample/simulation evidence generated by `WeatherBalanceReportV1Bench`. This is not live production telemetry.",
		"",
		"## Scope and method",
		"",
		"- The bench records 18 completed samples: three for each of the six canonical Weather v1 definitions.",
		"- Every sample emits forecast, activation, and end lifecycle records. Only completed end records contribute to balance aggregates.",
		"- Durations are centered on the current definition catalog values; deltas and losses are fixed simulation observations, not claims about production players.",
		"- Economic values are aggregate estimates. No player identity or index, owner, exact cash, hand/discard, card identity, hidden monster target or weights, AI plan, save state, or camera state is collected.",
		"",
		"## Definition results",
		"",
		"| Definition | Samples | Hit regions | Avg forecast / active / fade (s) | Avg price delta | Avg route revenue delta | Responses (route / buy / build / play) | Monster target changed | Region damage | Estimated economic delta | Simulated loss |",
		"|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|",
	]
	var definitions: Array = aggregates.get("definitions", []) as Array
	for definition_variant in definitions:
		var row := definition_variant as Dictionary
		var responses: Dictionary = row.get("player_response_counts", {}) as Dictionary
		var economic_delta := float(row.get("estimated_economic_delta_total", 0.0))
		lines.append("| %s (`%s`) | %d | %s | %.2f / %.2f / %.2f | %s | %s | %d / %d / %d / %d | %d/%d (%.2f%%) | %.2f | %s | %.2f |" % [
			str(row.get("display_name", "")),
			str(row.get("definition_id", "")),
			int(row.get("event_count", 0)),
			_hit_regions(row),
			float(row.get("average_forecast_duration_seconds", 0.0)),
			float(row.get("average_active_duration_seconds", 0.0)),
			float(row.get("average_fade_duration_seconds", 0.0)),
			_signed_percent(float(row.get("average_product_price_delta_percent", 0.0))),
			_signed_percent(float(row.get("average_route_revenue_delta_percent", 0.0))),
			int(responses.get("route_after_forecast", 0)),
			int(responses.get("buy_after_forecast", 0)),
			int(responses.get("build_after_forecast", 0)),
			int(responses.get("play_after_forecast", 0)),
			int(row.get("monster_target_changed_count", 0)),
			int(row.get("event_count", 0)),
			float(row.get("monster_target_changed_rate", 0.0)) * 100.0,
			float(row.get("region_damage_total", 0.0)),
			_signed_value(economic_delta),
			maxf(0.0, -economic_delta),
		])
	lines.append_array([
		"",
		"## Per-region evidence",
		"",
		"| Definition | Region | Samples | Avg forecast / active / fade (s) | Avg price delta | Avg route revenue delta | Monster target changed | Region damage | Estimated economic delta |",
		"|---|---:|---:|---:|---:|---:|---:|---:|---:|",
	])
	for definition_variant in definitions:
		var definition_row := definition_variant as Dictionary
		for region_variant in definition_row.get("regions", []):
			var region := region_variant as Dictionary
			lines.append("| `%s` | R%02d | %d | %.2f / %.2f / %.2f | %s | %s | %d/%d (%.2f%%) | %.2f | %s |" % [
				str(region.get("definition_id", "")),
				int(region.get("region_index", -1)),
				int(region.get("event_count", 0)),
				float(region.get("average_forecast_duration_seconds", 0.0)),
				float(region.get("average_active_duration_seconds", 0.0)),
				float(region.get("average_fade_duration_seconds", 0.0)),
				_signed_percent(float(region.get("average_product_price_delta_percent", 0.0))),
				_signed_percent(float(region.get("average_route_revenue_delta_percent", 0.0))),
				int(region.get("monster_target_changed_count", 0)),
				int(region.get("event_count", 0)),
				float(region.get("monster_target_changed_rate", 0.0)) * 100.0,
				float(region.get("region_damage_total", 0.0)),
				_signed_value(float(region.get("estimated_economic_delta_total", 0.0))),
			])
	lines.append_array([
		"",
		"## Reading the sample",
		"",
		"Negative route-revenue and economic deltas are simulated losses. `Monster target changed` reports only whether a public decision outcome changed; no target identity, candidate weights, or AI reasoning is present. The report is deterministic so changes between runs represent code or fixture changes rather than random sampling noise.",
		"",
	])
	return "\n".join(lines)


func debug_snapshot() -> Dictionary:
	return _last_result.duplicate(true)


func _run_automatically() -> void:
	var result := run_bench(true)
	print("WEATHER_BALANCE_REPORT_V1_BENCH|status=%s|samples=%d|definitions=%d|report=%s" % [
		str(result.get("status", "FAIL")),
		int(result.get("completed_samples", 0)),
		int(result.get("definition_count", 0)),
		REPORT_PATH,
	])
	if DisplayServer.get_name() == "headless":
		get_tree().quit(0 if str(result.get("status", "")) == "PASS" else 1)


func _record_simulation_samples() -> int:
	var accepted := 0
	var forecast_offsets := [-1.0, 0.0, 1.0]
	var active_offsets := [-2.0, 0.0, 2.0]
	var fade_offsets := [-0.5, 0.0, 0.5]
	for definition_id_variant in TELEMETRY_SERVICE.DEFINITION_IDS:
		var definition_id := str(definition_id_variant)
		var definition := WEATHER_CATALOG.definition(definition_id)
		var profile: Dictionary = PROFILE_BY_DEFINITION[definition_id]
		for sample_index in range(3):
			var region_index := int((profile["regions"] as Array)[sample_index])
			var forecast_duration := definition.forecast_duration + float(forecast_offsets[sample_index])
			var active_duration := definition.active_duration + float(active_offsets[sample_index])
			var fade_duration := definition.fade_duration + float(fade_offsets[sample_index])
			accepted += int(telemetry.record_event(_lifecycle_event(
				"forecast", definition_id, region_index, forecast_duration, 0.0, 0.0
			)))
			accepted += int(telemetry.record_event(_lifecycle_event(
				"activation", definition_id, region_index, 0.0, active_duration, 0.0
			)))
			accepted += int(telemetry.record_event({
				"schema_version": TELEMETRY_SERVICE.EVENT_SCHEMA,
				"event_type": "end",
				"definition_id": definition_id,
				"region_index": region_index,
				"forecast_duration_seconds": forecast_duration,
				"active_duration_seconds": active_duration,
				"fade_duration_seconds": fade_duration,
				"product_price_delta_percent": float((profile["price"] as Array)[sample_index]),
				"route_revenue_delta_percent": float((profile["route"] as Array)[sample_index]),
				"player_response_category": str((profile["responses"] as Array)[sample_index]),
				"monster_target_changed": bool((profile["monster"] as Array)[sample_index]),
				"region_damage": float((profile["damage"] as Array)[sample_index]),
				"estimated_economic_delta": float((profile["economic"] as Array)[sample_index]),
			}))
	return accepted


func _lifecycle_event(
	event_type: String,
	definition_id: String,
	region_index: int,
	forecast_duration: float,
	active_duration: float,
	fade_duration: float
) -> Dictionary:
	return {
		"schema_version": TELEMETRY_SERVICE.EVENT_SCHEMA,
		"event_type": event_type,
		"definition_id": definition_id,
		"region_index": region_index,
		"forecast_duration_seconds": forecast_duration,
		"active_duration_seconds": active_duration,
		"fade_duration_seconds": fade_duration,
		"product_price_delta_percent": 0.0,
		"route_revenue_delta_percent": 0.0,
		"player_response_category": TELEMETRY_SERVICE.NOT_APPLICABLE_RESPONSE,
		"monster_target_changed": false,
		"region_damage": 0.0,
		"estimated_economic_delta": 0.0,
	}


func _hit_regions(row: Dictionary) -> String:
	var labels: Array[String] = []
	for region_variant in row.get("regions", []):
		labels.append("R%02d" % int((region_variant as Dictionary).get("region_index", -1)))
	return ", ".join(labels) if not labels.is_empty() else "none"


func _signed_percent(value: float) -> String:
	return "%+.2f%%" % value


func _signed_value(value: float) -> String:
	return "%+.2f" % value


func _write_report(report: String) -> bool:
	var file := FileAccess.open(REPORT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("WEATHER BALANCE REPORT: cannot write %s" % REPORT_PATH)
		return false
	file.store_string(report)
	return true
