[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ManifestPath,[Parameter(Mandatory=$true)][string]$ExpectedManifestSha256,[Parameter(Mandatory=$true)][string]$ToolingWorktree,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;Import-Module(Join-Path $PSScriptRoot 'pr90_endpoint_listener_record_v1.psm1')-Force
$issues=[Collections.Generic.List[string]]::new();$root=(Resolve-Path -LiteralPath $ToolingWorktree).Path.TrimEnd('\');$manifestFull=(Resolve-Path -LiteralPath $ManifestPath).Path
if((Get-Pr90Sha256 $manifestFull)-cne$ExpectedManifestSha256.ToLowerInvariant()){$issues.Add('MANIFEST_HASH_MISMATCH')};$m=Get-Content -Raw -LiteralPath $manifestFull|ConvertFrom-Json -Depth 100 -DateKind String
$required=@('schema','status','characterization_eligible','formal_authorization_eligible','product_head_sha','product_tree_sha','old_tooling_head_sha','old_tooling_tree_sha','new_tooling_parent_sha','tooling_head_sha','tooling_tree_sha','tooling_files','selftest_path','selftest_sha256','selftest_status','selftest_case_count','selftest_pass_count','authorized_characterization_probe_id','allowed_changed_paths','actual_changed_paths','frozen_characterization_v3_001','netstat_target_scope_policy','netstat_target_port_prefilter_green','netstat_non_listener_state_scope_green','netstat_global_target_parse_failure_count','new_netstat_adapter_sha256','new_listener_key_formatter_sha256','new_characterization_controller_sha256','formal_mcp_execution_count','first_jsonrpc_request_sent','m6_to_m11_execution_count','canonical_payload_sha256')
foreach($field in $required){if($m.PSObject.Properties.Name-cnotcontains$field){$issues.Add("MISSING_FIELD:$field")}}
if([string]$m.schema-cne'SpaceSyndicatePr90ListenerObserverToolingManifestV3'){$issues.Add('SCHEMA_MISMATCH')};if((Get-Pr90CanonicalSha256 $m)-cne[string]$m.canonical_payload_sha256){$issues.Add('CANONICAL_HASH_MISMATCH')}
$sidecar="$manifestFull.sha256";$manifestHash=Get-Pr90Sha256 $manifestFull;$sidecarGreen=(Test-Path -LiteralPath $sidecar)-and([IO.File]::ReadAllText($sidecar).Contains($manifestHash));if(-not$sidecarGreen){$issues.Add('MANIFEST_SIDECAR_MISMATCH')}
$head=(& git -C $root rev-parse HEAD).Trim();$tree=(& git -C $root rev-parse 'HEAD^{tree}').Trim();$parent=(& git -C $root rev-parse HEAD^).Trim();if($head-cne[string]$m.tooling_head_sha){$issues.Add('HEAD_MISMATCH')};if($tree-cne[string]$m.tooling_tree_sha){$issues.Add('TREE_MISMATCH')};if($parent-cne[string]$m.new_tooling_parent_sha-or$parent-cne[string]$m.old_tooling_head_sha){$issues.Add('PARENT_MISMATCH')};if(@(& git -C $root status --porcelain=v1 --untracked-files=all).Count-ne0){$issues.Add('WORKTREE_DIRTY')}
$fileMismatch=0;foreach($file in @($m.tooling_files)){if(-not(Test-Path -LiteralPath $file.path -PathType Leaf)-or(Get-Pr90Sha256 $file.path)-cne[string]$file.sha256-or(& git -C $root hash-object -- ([string]$file.relative_path)).Trim()-cne[string]$file.git_blob){$fileMismatch+=1}};if($fileMismatch-ne0){$issues.Add("TOOLING_FILE_MISMATCH:$fileMismatch")}
$actual=@(& git -C $root diff --name-only ([string]$m.old_tooling_head_sha) $head|ForEach-Object{$_.Trim()}|Where-Object{$_}|Sort-Object);if(($actual-join'|')-cne(@($m.actual_changed_paths|Sort-Object)-join'|')-or@($actual|Where-Object{$_-cnotin@($m.allowed_changed_paths)}).Count-ne0){$issues.Add('CHANGED_PATH_MISMATCH')}
$self=Get-Content -Raw -LiteralPath $m.selftest_path|ConvertFrom-Json -Depth 100 -DateKind String;$ids=@($self.cases|ForEach-Object{[int]$_.case_id});if((Get-Pr90Sha256 $m.selftest_path)-cne[string]$m.selftest_sha256-or[string]$self.schema-cne'SpaceSyndicatePr90ListenerObserverSelfTestV3'-or[string]$self.status-cne'PASS'-or[int]$self.case_count-lt57-or[int]$self.pass_count-ne[int]$self.case_count-or@(1..57|Where-Object{$_-notin$ids}).Count-ne0-or-not[bool]$self.controller_receipt_canonical_fix_green-or-not[bool]$self.controller_zero_one_many_cardinality_fix_green-or-not[bool]$self.netstat_target_port_prefilter_green-or-not[bool]$self.netstat_non_listener_state_scope_green){$issues.Add('SELFTEST_INVALID')};if([int]$self.listener_formatter_exception_count-ne0-or-not[bool]$self.first_nonempty_listener_fixture_green-or[int]$self.cross_source_false_parity_count-ne0-or[int]$self.cross_source_false_mismatch_count-ne0-or[int]$self.listener_source_adapter_parse_failure_count-ne0-or[int]$self.netstat_global_target_parse_failure_count-ne0){$issues.Add('SELFTEST_ZERO_GATE_FAILED')}
if((Get-Pr90Sha256 $m.frozen_evidence.attempt21_result_path)-cne'83cd3d53c9b38a93cfb56f033f89f8996197c26ca2ddf9eecfe7f79b776a3d55'-or(Get-Pr90Sha256 $m.frozen_evidence.attempt21_attestation_path)-cne'13ed042cf1739a04b6af899f5100decd63af5cfd7cc54cbc2f3b5f073d6c0d44'-or(Get-Pr90Sha256 $m.frozen_evidence.old_characterization_failure_path)-cne'c9086db4f7b78c5c67c76a2b2e7586f9270a9411f2100f0ee352f09e6ee3f373'){$issues.Add('FROZEN_EVIDENCE_MISMATCH')}
if((Get-Pr90Sha256 $m.frozen_characterization_v2_001.result_path)-cne'b58a80636bb939bb793e57707040e39bd279759596d435f2cd7daa438ec7f216'-or(Get-Pr90Sha256 $m.frozen_characterization_v2_001.attestation_path)-cne'84a2ed5dc6fc588559143d96cd019879555fbc90d21d2257e8d7f349e8e59289'-or(Get-Pr90Sha256 $m.frozen_characterization_v2_001.failure_path)-cne'a3cab93b9f725010e7e59352c29b4da853f0b428d73fb53696953389d2da6685'){$issues.Add('PRIOR_CHARACTERIZATION_FROZEN_MISMATCH')}
if((Get-Pr90Sha256 $m.frozen_characterization_v3_001.result_path)-cne'9809619af94292b6dbb0c0429b8cfa4103b5c0fb57566553179a55dabbb4cdb3'-or(Get-Pr90Sha256 $m.frozen_characterization_v3_001.attestation_path)-cne'252e419edebc5d7b2baa24c6e5328317c3223ced7ebb02eea6b63ef8b52d7b88'-or(Get-Pr90Sha256 $m.frozen_characterization_v3_001.m0_receipt_path)-cne'6b2ddc06c8e930708c6e7b06a70a60a3060c28792d3b620d61e207109655d436'-or(Get-Pr90Sha256 $m.frozen_characterization_v3_001.terminal_path)-cne'a3a11d86e44553ec79ca43da63bad88b3b7439971c0e3e1a92ccd51e0dc6e10e'-or(Get-Pr90Sha256 $m.frozen_characterization_v3_001.diagnostic_path)-cne'68b5f422268c9da3bad7fb666d2f73524fe5ff6c089a728b508bbbe638924e81'-or(Get-Pr90Sha256 $m.frozen_characterization_v3_001.tooling_manifest_path)-cne'96d01aa9d5428f7e0f2c2b1c2d8bd11fa143d3baf44f065ab601a6bd01561ee0'-or(Get-Pr90Sha256 $m.frozen_characterization_v3_001.tooling_seal_path)-cne'c5390a49ae15e0744dc22348ea62a199085003c2ae81730685c549cf54c53928'){$issues.Add('V3_CHARACTERIZATION_FROZEN_MISMATCH')}
if([string]$m.netstat_target_scope_policy-cne'VALID_LOCAL_PORT_PREFILTER_BEFORE_LISTENER_STATE_VALIDATION_V1'-or-not[bool]$m.netstat_target_port_prefilter_green-or-not[bool]$m.netstat_non_listener_state_scope_green-or[int]$m.netstat_global_target_parse_failure_count-ne0){$issues.Add('NETSTAT_SCOPE_CONTRACT_MISMATCH')}
$eligible=($issues.Count-eq0);if([bool]$m.characterization_eligible-ne$true-or[string]$m.status-cne'READY_FOR_ONE_M0_M5_CHARACTERIZATION_ONLY'-or[bool]$m.formal_authorization_eligible-or[string]$m.authorized_characterization_probe_id-cne'pr90-m5-endpoint-owner-characterization-v4-001'){$issues.Add('ELIGIBILITY_SCOPE_MISMATCH')};if([bool]$m.first_jsonrpc_request_sent-or[int]$m.endpoint_application_request_count-ne0-or[int]$m.m6_to_m11_execution_count-ne0-or[int]$m.formal_mcp_execution_count-ne0-or[int]$m.authorized_run_count_consumed-ne0){$issues.Add('ZERO_EXECUTION_GATE_MISMATCH')}
$receipt=[ordered]@{schema='SpaceSyndicatePr90ListenerObserverToolingValidationV3';status=if($issues.Count-eq0){'PASS'}else{'FAIL'};validated_at_utc=[DateTimeOffset]::UtcNow.ToString('o');manifest_path=$manifestFull;manifest_sha256=Get-Pr90Sha256 $manifestFull;tooling_head_sha=$head;tooling_tree_sha=$tree;validated_file_count=@($m.tooling_files).Count;validated_case_count=[int]$self.case_count;file_mismatch_count=$fileMismatch;issue_count=$issues.Count;issues=@($issues);netstat_target_port_prefilter_green=[bool]$self.netstat_target_port_prefilter_green;netstat_non_listener_state_scope_green=[bool]$self.netstat_non_listener_state_scope_green;netstat_global_target_parse_failure_count=[int]$self.netstat_global_target_parse_failure_count;characterization_eligible=($issues.Count-eq0);formal_authorization_eligible=$false;first_jsonrpc_request_sent=$false;m6_to_m11_execution_count=0;formal_mcp_execution_count=0;authorized_run_count_consumed=0;canonical_payload_sha256=''};$receipt.canonical_payload_sha256=Get-Pr90CanonicalSha256 $receipt;Write-Pr90ImmutableJson -Path $OutputPath -Value $receipt -WriteSha256Sidecar|Out-Null;$receipt|ConvertTo-Json -Depth 100 -Compress;if($issues.Count-ne0){exit 2}
