[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$ManifestPath,[Parameter(Mandatory=$true)][string]$ExpectedManifestSha256,[Parameter(Mandatory=$true)][string]$ValidationReceiptPath,[Parameter(Mandatory=$true)][string]$ExpectedValidationReceiptSha256,[Parameter(Mandatory=$true)][string]$ToolingWorktree,[Parameter(Mandatory=$true)][string]$OutputPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;Import-Module(Join-Path $PSScriptRoot 'pr90_endpoint_listener_record_v1.psm1')-Force
$root=(Resolve-Path -LiteralPath $ToolingWorktree).Path.TrimEnd('\');$manifestFull=(Resolve-Path -LiteralPath $ManifestPath).Path;$validationFull=(Resolve-Path -LiteralPath $ValidationReceiptPath).Path
if(@(& git -C $root status --porcelain=v1 --untracked-files=all).Count-ne0){throw 'Seal requires clean tooling worktree/index.'};if((Get-Pr90Sha256 $manifestFull)-cne$ExpectedManifestSha256.ToLowerInvariant()){throw 'Manifest SHA mismatch.'};if((Get-Pr90Sha256 $validationFull)-cne$ExpectedValidationReceiptSha256.ToLowerInvariant()){throw 'Validation SHA mismatch.'}
$m=Get-Content -Raw -LiteralPath $manifestFull|ConvertFrom-Json -Depth 100 -DateKind String;$v=Get-Content -Raw -LiteralPath $validationFull|ConvertFrom-Json -Depth 100 -DateKind String
if([string]$v.status-cne'PASS'-or-not[bool]$v.characterization_eligible-or[bool]$v.formal_authorization_eligible-or[string]$m.status-cne'READY_FOR_ONE_M0_M5_CHARACTERIZATION_ONLY'-or-not[bool]$m.characterization_eligible-or[bool]$m.formal_authorization_eligible){throw 'Validation/readiness is not exact characterization-only PASS.'}
if((Get-Pr90CanonicalSha256 $m)-cne[string]$m.canonical_payload_sha256-or(Get-Pr90CanonicalSha256 $v)-cne[string]$v.canonical_payload_sha256){throw 'Canonical payload mismatch.'};if([string]$m.tooling_head_sha-cne(& git -C $root rev-parse HEAD).Trim()-or[string]$m.tooling_tree_sha-cne(& git -C $root rev-parse 'HEAD^{tree}').Trim()){throw 'Tooling git identity mismatch.'};foreach($file in @($m.tooling_files)){if((Get-Pr90Sha256 $file.path)-cne[string]$file.sha256-or(& git -C $root hash-object -- ([string]$file.relative_path)).Trim()-cne[string]$file.git_blob){throw "Tooling file mismatch: $($file.relative_path)"}}
$self=Get-Content -Raw -LiteralPath $m.selftest_path|ConvertFrom-Json -Depth 100 -DateKind String;if((Get-Pr90Sha256 $m.selftest_path)-cne[string]$m.selftest_sha256-or[string]$self.status-cne'PASS'-or[int]$self.pass_count-ne[int]$self.case_count-or[int]$self.case_count-lt35){throw 'Self-test mismatch.'}
$seal=[ordered]@{schema='SpaceSyndicatePr90ListenerObserverToolingSealV1';status='SEALED';readiness_status='READY_FOR_ONE_M0_M5_CHARACTERIZATION_ONLY';characterization_eligible=$true;formal_authorization_eligible=$false;post_repair_m0_m11_eligible=$false;sealed_at_utc=[DateTimeOffset]::UtcNow.ToString('o');authorized_characterization_probe_id=[string]$m.authorized_characterization_probe_id;authorized_characterization_probe_count=1;product_head_sha=[string]$m.product_head_sha;product_tree_sha=[string]$m.product_tree_sha;old_tooling_head_sha=[string]$m.old_tooling_head_sha;old_tooling_tree_sha=[string]$m.old_tooling_tree_sha;tooling_head_sha=[string]$m.tooling_head_sha;tooling_tree_sha=[string]$m.tooling_tree_sha;manifest_path=$manifestFull;manifest_sha256=Get-Pr90Sha256 $manifestFull;manifest_canonical_payload_sha256=[string]$m.canonical_payload_sha256;validation_receipt_path=$validationFull;validation_receipt_sha256=Get-Pr90Sha256 $validationFull;validation_canonical_payload_sha256=[string]$v.canonical_payload_sha256;selftest_path=[string]$m.selftest_path;selftest_sha256=[string]$m.selftest_sha256;selftest_canonical_payload_sha256=[string]$self.canonical_payload_sha256;tooling_file_count=@($m.tooling_files).Count;tooling_files=$m.tooling_files;new_listener_record_normalizer_sha256=[string]$m.new_listener_record_normalizer_sha256;new_listener_key_formatter_sha256=[string]$m.new_listener_key_formatter_sha256;new_getnettcp_adapter_sha256=[string]$m.new_getnettcp_adapter_sha256;new_netstat_adapter_sha256=[string]$m.new_netstat_adapter_sha256;new_listener_parity_validator_sha256=[string]$m.new_listener_parity_validator_sha256;new_process_identity_reader_sha256=[string]$m.new_process_identity_reader_sha256;new_characterization_controller_sha256=[string]$m.new_characterization_controller_sha256;new_selftest_manifest_sha256=[string]$m.new_selftest_manifest_sha256;post_seal_mutation_count=0;first_jsonrpc_request_sent=$false;endpoint_application_request_count=0;m6_to_m11_execution_count=0;post_repair_m0_m11_probe_execution_count=0;formal_mcp_execution_count=0;authorized_run_count_consumed=0;exact_sha_mcp_status='NOT_STARTED';canonical_payload_sha256=''};$seal.canonical_payload_sha256=Get-Pr90CanonicalSha256 $seal;Write-Pr90ImmutableJson -Path $OutputPath -Value $seal -WriteSha256Sidecar|Out-Null;$seal|ConvertTo-Json -Depth 100 -Compress
