[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ManifestPath,
    [Parameter(Mandatory = $true)][string]$ExpectedManifestSha256,
    [Parameter(Mandatory = $true)][string]$ToolingWorktree,
    [Parameter(Mandatory = $true)][string]$OutputPath
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'pr90_attempt21_mcp_startup_contract.psm1') -Force
$issues=[Collections.Generic.List[string]]::new();$root=(Resolve-Path -LiteralPath $ToolingWorktree).Path.TrimEnd('\')
if((Get-StartupSha256 $ManifestPath)-cne$ExpectedManifestSha256.ToLowerInvariant()){$issues.Add('MANIFEST_HASH_MISMATCH')}
$manifest=Get-Content -Raw -LiteralPath $ManifestPath|ConvertFrom-Json -Depth 100 -DateKind String
$required=@('schema','status','authorization_id','authorization_eligible','startup_probe_b_authorization_eligible','ready_for_new_exact_sha_mcp_authorization','authorized_post_repair_probe_id','authorized_post_repair_probe_count','authorized_new_probe_count','new_probe_execution_count','automatic_retry_allowed','product_head_sha','product_tree_sha','tooling_head_sha','tooling_tree_sha','base_tooling_head_sha','base_tooling_tree_sha','new_tooling_commit_count','frozen_failed_probe_id','frozen_failed_probe_execution_count','frozen_failed_probe_cumulative_execution_count','frozen_failed_probe_tooling_head_sha','frozen_failed_probe_tooling_tree_sha','frozen_failed_probe_failure_evidence_sha256','frozen_failed_probe_terminal_manifest_sha256','frozen_failed_probe_result_sha256','frozen_failed_probe_attestation_sha256','frozen_failed_probe_cleanup_sha256','frozen_failed_probe_enter_play_mode_raw_sha256','frozen_failed_probe_get_runtime_events_raw_sha256','frozen_failed_probe_exit_play_mode_raw_sha256','frozen_failed_probe_watchdog_timeline_sha256','frozen_failed_probe_watchdog_summary_sha256','m9_root_cause_class','m9_root_cause_formally_attested','runtime_bridge_ready_status_poll_before_event_bootstrap','runtime_bridge_ready_status_max_age_ms','runtime_bridge_status_poll_interval_ms','runtime_bridge_bootstrap_requested_timeout_ms','runtime_bridge_m9_completion_margin_ms','frozen_failure_witness_sha256','attempt20_startup_root_cause_class','tooling_files','startup_milestones','startup_selftest_sha256','endpoint_ownership_contract_version','endpoint_ownership_v2_selftest_case_count','endpoint_ownership_v2_false_green_count','zero_cardinality_selftest_case_count','zero_cardinality_selftest_pass_count','zero_cardinality_false_green_count','optional_property_selftest_case_count','optional_property_selftest_pass_count','optional_property_false_green_count','runtime_bridge_bootstrap_selftest_case_count','runtime_bridge_bootstrap_selftest_pass_count','runtime_bridge_bootstrap_false_green_count','failure_cleanup_selftest_case_count','failure_cleanup_selftest_pass_count','failure_cleanup_false_green_count','failure_cleanup_unrelated_termination_count','powershell_parse_error_count','probe_a_evidence_sha256','post_repair_probe_execution_count','post_repair_probe_m0_m11_green','endpoint_ownership_contract_v2_implemented','formal_mcp_execution_count','authorized_run_count_consumed','exact_sha_mcp_status','new_import_runner_sha256','new_cursor_runbook_sha256','new_startup_watchdog_sha256','new_startup_state_machine_sha256','new_endpoint_ownership_v2_sha256','new_post_repair_probe_controller_sha256','canonical_payload_sha256')
foreach($name in $required){if($manifest.PSObject.Properties.Name -notcontains $name){$issues.Add("MISSING_FIELD:$name")}}
if([string]$manifest.schema-cne'SpaceSyndicatePr90McpStartupToolingManifestV2'){$issues.Add('SCHEMA_MISMATCH')}
if([string]$manifest.tooling_head_sha-cne(& git -C $root rev-parse HEAD).Trim()){$issues.Add('TOOLING_HEAD_MISMATCH')}
if([string]$manifest.tooling_tree_sha-cne(& git -C $root rev-parse 'HEAD^{tree}').Trim()){$issues.Add('TOOLING_TREE_MISMATCH')}
if(@(& git -C $root status --porcelain=v1 --untracked-files=all).Count-ne0){$issues.Add('TOOLING_WORKTREE_DIRTY')}
if([string]$manifest.authorization_id-cne'PR90_MCP_ENDPOINT_OWNERSHIP_V2_POST_REPAIR_M9_RUNTIME_BRIDGE_HEARTBEAT_BOOTSTRAP_TOOLING_REPAIR_AUTHORIZATION'){$issues.Add('AUTHORIZATION_ID_MISMATCH')}
if(-not[string]::IsNullOrEmpty([string]$manifest.authorized_post_repair_probe_id)-or[int]$manifest.authorized_post_repair_probe_count-ne0-or[int]$manifest.authorized_new_probe_count-ne0-or[int]$manifest.new_probe_execution_count-ne0-or[bool]$manifest.automatic_retry_allowed){$issues.Add('NEW_PROBE_MUST_REMAIN_UNAUTHORIZED')}
if([string]$manifest.base_tooling_head_sha-cne'd7386e901f2d0f4fdf994f640f6e91b49d7d5ed8'-or[string]$manifest.base_tooling_tree_sha-cne'7b756bb9f3039125e63d035d49eb5776ca60178a'-or[int]$manifest.new_tooling_commit_count-ne1){$issues.Add('TOOLING_BASE_OR_COMMIT_COUNT_MISMATCH')}
if((& git -C $root rev-parse 'HEAD^').Trim()-cne[string]$manifest.base_tooling_head_sha){$issues.Add('TOOLING_PARENT_MISMATCH')}
if([string]$manifest.frozen_failed_probe_id-cne'pr90-mcp-endpoint-ownership-v2-post-repair-m0-m11-003'-or[int]$manifest.frozen_failed_probe_execution_count-ne1-or[int]$manifest.frozen_failed_probe_cumulative_execution_count-ne3-or[string]$manifest.frozen_failed_probe_tooling_head_sha-cne'd7386e901f2d0f4fdf994f640f6e91b49d7d5ed8'-or[string]$manifest.frozen_failed_probe_tooling_tree_sha-cne'7b756bb9f3039125e63d035d49eb5776ca60178a'-or[string]$manifest.frozen_failed_probe_failure_evidence_sha256-cne'4a7ef49aa6ac64dd61b90ac51f32fa1938c78894b312f7b3c776c485e1a0f6f8'-or[string]$manifest.frozen_failed_probe_terminal_manifest_sha256-cne'39138585999d6f5e403df1a897ef0163fe48964c22ab3f1a7a81730cbac2e689'-or[string]$manifest.frozen_failed_probe_result_sha256-cne'2846a76ca673095b08c045875d921d0059034f78557a95fcf73ec9ad2072b5b8'-or[string]$manifest.frozen_failed_probe_attestation_sha256-cne'd669b5fe0791e4ee1bf1cb1475417ee2a708db53741d07158647339e22818321'-or[string]$manifest.frozen_failed_probe_cleanup_sha256-cne'39138585999d6f5e403df1a897ef0163fe48964c22ab3f1a7a81730cbac2e689'-or[string]$manifest.frozen_failed_probe_enter_play_mode_raw_sha256-cne'85b67a9d08541358c69f4874835acd69a39aa974db53cb5444d6ad120a7141fd'-or[string]$manifest.frozen_failed_probe_get_runtime_events_raw_sha256-cne'c6e306d57ca02c9d6644c3507db7ada7f1c8e79d87bc248b17a0e8fdae1f9825'-or[string]$manifest.frozen_failed_probe_exit_play_mode_raw_sha256-cne'ffa160d30fa8b7c0cfb31e297c4fd08a9d8b1a345a0288641473d6b30d663eb7'-or[string]$manifest.frozen_failed_probe_watchdog_timeline_sha256-cne'7e24b20197727a29706d31b51dcbccbafa4ab7e47041b59e923f319ee58908e7'-or[string]$manifest.frozen_failed_probe_watchdog_summary_sha256-cne'f593ff7b56595fa11dd6e0034e8e54a7f57af4a5ed8608ca70e15c99eaf8eccb'){$issues.Add('FROZEN_FAILED_PROBE_IDENTITY_MISMATCH')}
if([string]$manifest.m9_root_cause_class-cne'TOOLING_MAIN_THREAD_RUNTIME_BOOTSTRAP_SCHEDULING_RACE'-or-not[bool]$manifest.m9_root_cause_formally_attested-or-not[bool]$manifest.runtime_bridge_ready_status_poll_before_event_bootstrap-or[int]$manifest.runtime_bridge_ready_status_max_age_ms-ne3000-or[int]$manifest.runtime_bridge_status_poll_interval_ms-ne250-or[int]$manifest.runtime_bridge_bootstrap_requested_timeout_ms-ne10000-or[int]$manifest.runtime_bridge_m9_completion_margin_ms-ne2000){$issues.Add('M9_RUNTIME_BRIDGE_REPAIR_CONTRACT_MISMATCH')}
foreach($file in @($manifest.tooling_files)){
    if(-not(Test-Path -LiteralPath $file.path -PathType Leaf)){$issues.Add("FILE_MISSING:$($file.relative_path)");continue}
    if((Get-StartupSha256 $file.path)-cne[string]$file.sha256){$issues.Add("FILE_HASH_MISMATCH:$($file.relative_path)")}
    if((& git -C $root hash-object -- ([string]$file.relative_path)).Trim()-cne[string]$file.git_blob){$issues.Add("FILE_BLOB_MISMATCH:$($file.relative_path)")}
}
if(@($manifest.startup_milestones).Count-ne12){$issues.Add('MILESTONE_COUNT_MISMATCH')}
for($i=0;$i-lt@($manifest.startup_milestones).Count;$i+=1){if([string]$manifest.startup_milestones[$i].id-cne"M$i"){$issues.Add("MILESTONE_ORDER_MISMATCH:$i")}}
$selftest=Get-Content -Raw -LiteralPath $manifest.startup_selftest_path|ConvertFrom-Json -Depth 100 -DateKind String
if((Get-StartupSha256 $manifest.startup_selftest_path)-cne[string]$manifest.startup_selftest_sha256-or[string]$selftest.status-cne'PASS'-or[int]$selftest.case_count-lt100-or[int]$selftest.pass_count-ne[int]$selftest.case_count-or[int]$selftest.endpoint_ownership_contract_version-ne2-or[int]$selftest.endpoint_ownership_v2_case_count-lt15-or[int]$selftest.endpoint_ownership_v2_pass_count-ne[int]$selftest.endpoint_ownership_v2_case_count-or[int]$selftest.endpoint_ownership_v2_false_green_count-ne0-or[int]$selftest.zero_cardinality_case_count-lt13-or[int]$selftest.zero_cardinality_pass_count-ne[int]$selftest.zero_cardinality_case_count-or[int]$selftest.zero_cardinality_false_green_count-ne0-or[int]$selftest.optional_property_case_count-lt12-or[int]$selftest.optional_property_pass_count-ne[int]$selftest.optional_property_case_count-or[int]$selftest.optional_property_false_green_count-ne0-or[int]$selftest.runtime_bridge_bootstrap_case_count-lt16-or[int]$selftest.runtime_bridge_bootstrap_pass_count-ne[int]$selftest.runtime_bridge_bootstrap_case_count-or[int]$selftest.runtime_bridge_bootstrap_false_green_count-ne0-or[int]$selftest.failure_cleanup_case_count-lt12-or[int]$selftest.failure_cleanup_pass_count-ne[int]$selftest.failure_cleanup_case_count-or[int]$selftest.failure_cleanup_false_green_count-ne0-or[int]$selftest.failure_cleanup_unrelated_termination_count-ne0-or[int]$selftest.powershell_parse_error_count-ne0){$issues.Add('SELFTEST_INVALID')}
$probe=Get-Content -Raw -LiteralPath $manifest.probe_a_evidence_path|ConvertFrom-Json -Depth 100 -DateKind String
if((Get-StartupSha256 $manifest.probe_a_evidence_path)-cne[string]$manifest.probe_a_evidence_sha256){$issues.Add('PROBE_A_HASH_MISMATCH')}
$frozenProbeEvidence=([string]$probe.probe_id-ceq'pr90-mcp-endpoint-ownership-v2-post-repair-m0-m11-003'-and[string]$probe.status-ceq'BLOCKED'-and[string]$probe.first_failure_class-ceq'STARTUP_M9_RUNTIME_STREAM_MISSING'-and[int]$probe.post_repair_probe_execution_count-eq1-and[int]$probe.new_probe_execution_count-eq1-and[int]$probe.cumulative_post_repair_probe_execution_count-eq3-and-not[bool]$probe.automatic_retry_allowed-and-not[bool]$probe.second_new_probe_created-and[bool]$probe.stops_cleanly-and-not[bool]$probe.forced_stop-and[int]$probe.godot_process_count_after-eq0-and[int]$probe.port_7576_count_after-eq0-and[int]$probe.port_7586_count_after-eq0-and[int]$probe.unrelated_process_termination_count-eq0)
if(-not$frozenProbeEvidence){$issues.Add('FROZEN_PROBE_003_CONTRACT_MISMATCH')}
if([int]$manifest.new_probe_execution_count-ne0-or[int]$manifest.post_repair_probe_execution_count-ne0-or[bool]$manifest.post_repair_probe_m0_m11_green){$issues.Add('NEW_PROBE_EXECUTION_COUNT_MUST_REMAIN_ZERO')}
if([bool]$manifest.authorization_eligible){$issues.Add('FORMAL_AUTHORIZATION_MUST_REMAIN_FALSE')}
if([bool]$manifest.startup_probe_b_authorization_eligible){$issues.Add('PROBE_B_READINESS_MUST_REMAIN_FALSE')}
if([string]$manifest.status-cne'BLOCKED_PENDING_NEW_POST_REPAIR_M0_M11_PROBE_AUTHORIZATION'){$issues.Add('READINESS_STATUS_MISMATCH')}
if([bool]$manifest.ready_for_new_exact_sha_mcp_authorization){$issues.Add('EXACT_SHA_READINESS_MUST_REMAIN_FALSE')}
if([int]$manifest.formal_mcp_execution_count-ne0-or[int]$manifest.authorized_run_count_consumed-ne0-or[string]$manifest.exact_sha_mcp_status-cne'NOT_STARTED'){$issues.Add('FORMAL_ZERO_COUNT_MISMATCH')}
if((Get-StartupCanonicalSha256 $manifest)-cne[string]$manifest.canonical_payload_sha256){$issues.Add('CANONICAL_HASH_MISMATCH')}
$receipt=[ordered]@{schema='SpaceSyndicatePr90McpStartupToolingValidationV2';status=if($issues.Count-eq0){'PASS'}else{'FAIL'};validated_at_utc=[DateTimeOffset]::UtcNow.ToString('o');manifest_path=[IO.Path]::GetFullPath($ManifestPath);manifest_sha256=Get-StartupSha256 $ManifestPath;tooling_head_sha=[string]$manifest.tooling_head_sha;tooling_tree_sha=[string]$manifest.tooling_tree_sha;authorization_eligible=$false;startup_probe_b_authorization_eligible=[bool]$manifest.startup_probe_b_authorization_eligible;ready_for_new_exact_sha_mcp_authorization=$false;endpoint_ownership_contract_version=2;issue_count=$issues.Count;issues=@($issues);formal_mcp_execution_count=0;authorized_run_count_consumed=0;canonical_payload_sha256=''}
$receipt.canonical_payload_sha256=Get-StartupCanonicalSha256 $receipt;Write-StartupImmutableJson -Path $OutputPath -Value $receipt -WriteSha256Sidecar|Out-Null;$receipt|ConvertTo-Json -Depth 100 -Compress
if($issues.Count-ne0){exit 2}
