[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$ToolingWorktree,
    [Parameter(Mandatory=$true)][string]$SelfTestPath,
    [Parameter(Mandatory=$true)][string]$ExpectedSelfTestSha256,
    [Parameter(Mandatory=$true)][string]$OutputPath
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'pr90_endpoint_listener_record_v1.psm1') -Force
$root=(Resolve-Path -LiteralPath $ToolingWorktree).Path.TrimEnd('\')
if(@(& git -C $root status --porcelain=v1 --untracked-files=all).Count-ne0){throw 'Manifest requires clean tooling worktree/index.'}
$oldHead='3ce3f0fb9e63def5455f25481a11c28964e74821';$oldTree='5591b46669f8f3cc223182283d3c48aaa984e8d8'
$head=(& git -C $root rev-parse HEAD).Trim();$tree=(& git -C $root rev-parse 'HEAD^{tree}').Trim();$parent=(& git -C $root rev-parse HEAD^).Trim();$branch=(& git -C $root branch --show-current).Trim()
if($head-ceq$oldHead-or$tree-ceq$oldTree-or$parent-cne$oldHead){throw 'New tooling git identity/parent is invalid.'}
$paths=@(
 'tools/pr90_endpoint_listener_record_v1.psm1','tools/pr90_endpoint_listener_key_formatter_v1.psm1',
 'tools/pr90_getnettcp_listener_adapter_v1.psm1','tools/pr90_netstat_listener_adapter_v1.psm1',
 'tools/pr90_listener_process_identity_reader_v1.psm1','tools/pr90_listener_parity_validator_v1.psm1',
 'tools/pr90_listener_observer_characterization_controller_v2.ps1','tools/pr90_listener_observer_selftest_v1.ps1',
 'tools/pr90_listener_observer_tooling_manifest_builder_v1.ps1','tools/pr90_listener_observer_tooling_validator_v1.ps1',
 'tools/pr90_listener_observer_tooling_seal_builder_v1.ps1'
)
$actual=@(& git -C $root diff --name-only $oldHead $head|ForEach-Object{$_.Trim()}|Where-Object{$_}|Sort-Object)
if(@($actual|Where-Object{$_-cnotin$paths}).Count-ne0-or@($paths|Where-Object{$_-cnotin$actual}).Count-ne0){throw 'Tooling changed-path allowlist mismatch.'}
$roles=@('record_normalizer','key_formatter','getnettcp_adapter','netstat_adapter','process_identity_reader','parity_validator','characterization_controller','selftest_runner','manifest_builder','manifest_validator','seal_builder')
$files=@();for($i=0;$i-lt$paths.Count;$i+=1){$path=Join-Path $root $paths[$i];if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Missing tooling file: $($paths[$i])"};$files+=[ordered]@{role=$roles[$i];relative_path=$paths[$i];path=[IO.Path]::GetFullPath($path);bytes=[int64](Get-Item -LiteralPath $path).Length;sha256=Get-Pr90Sha256 $path;git_blob=(& git -C $root hash-object -- $paths[$i]).Trim()}}
$selfPath=(Resolve-Path -LiteralPath $SelfTestPath).Path;if((Get-Pr90Sha256 $selfPath)-cne$ExpectedSelfTestSha256.ToLowerInvariant()){throw 'Self-test hash mismatch.'};$self=Get-Content -Raw -LiteralPath $selfPath|ConvertFrom-Json -Depth 100 -DateKind String
$requiredCases=1..35;$caseIds=@($self.cases|ForEach-Object{[int]$_.case_id});$selfGreen=([string]$self.status-ceq'PASS'-and[int]$self.case_count-ge35-and[int]$self.pass_count-eq[int]$self.case_count-and@($requiredCases|Where-Object{$_-notin$caseIds}).Count-eq0-and[int]$self.listener_formatter_exception_count-eq0-and[bool]$self.first_nonempty_listener_fixture_green-and[int]$self.cross_source_false_parity_count-eq0-and[int]$self.cross_source_false_mismatch_count-eq0-and[int]$self.listener_source_adapter_parse_failure_count-eq0-and[int]$self.listener_canonical_key_culture_delta-eq0-and[int]$self.listener_canonical_key_order_delta-eq0)
$frozenResult='C:\pr90-a21-final-minimal-m0-m11-probe-001\pr90_attempt21_minimal_m0_m11_probe_result.json';$frozenAttestation='C:\pr90-a21-final-minimal-m0-m11-probe-001\pr90_attempt21_minimal_m0_m11_probe_attestation.json';$oldFailure='C:\pr90-m5-endpoint-ownership-v2\pr90-m5-endpoint-owner-characterization-001\evidence\characterization-failure.json';$oldController='C:\pr90-m5-endpoint-ownership-v2\characterize-endpoint-owner.ps1'
$pins=[ordered]@{attempt21_result_path=$frozenResult;attempt21_result_sha256=Get-Pr90Sha256 $frozenResult;attempt21_attestation_path=$frozenAttestation;attempt21_attestation_sha256=Get-Pr90Sha256 $frozenAttestation;old_characterization_failure_path=$oldFailure;old_characterization_failure_sha256=Get-Pr90Sha256 $oldFailure;old_characterization_controller_path=$oldController;old_characterization_controller_sha256=Get-Pr90Sha256 $oldController}
if($pins.attempt21_result_sha256-cne'83cd3d53c9b38a93cfb56f033f89f8996197c26ca2ddf9eecfe7f79b776a3d55'-or$pins.attempt21_attestation_sha256-cne'13ed042cf1739a04b6af899f5100decd63af5cfd7cc54cbc2f3b5f073d6c0d44'-or$pins.old_characterization_failure_sha256-cne'c9086db4f7b78c5c67c76a2b2e7586f9270a9411f2100f0ee352f09e6ee3f373'-or$pins.old_characterization_controller_sha256-cne'dd05e0c3e687a8c1c3fd4d5f18bcce7927b99f28803ebfd726ede902753cc9bf'){throw 'Frozen evidence pin mismatch.'}
$unchanged=[ordered]@{import_runner_sha256=Get-Pr90Sha256 (Join-Path $root 'tools\pr90_attempt19_import_runner_v3.ps1');cursor_runbook_sha256=Get-Pr90Sha256 (Join-Path $root 'tools\pr90_attempt21_cursor_aware_exact_mcp_v5.ps1');startup_watchdog_sha256=Get-Pr90Sha256 (Join-Path $root 'tools\pr90_attempt21_mcp_startup_watchdog.ps1');formal_m5_state_machine_sha256=Get-Pr90Sha256 (Join-Path $root 'tools\pr90_mcp_startup_state_machine_v1.psm1');launcher_sha256=Get-Pr90Sha256 (Join-Path $root 'tools\launch_role_godot_mcp.ps1')}
if($unchanged.import_runner_sha256-cne'acc4d08ef5d4fc40496c97a33c70364a3a06a0afd63b72ac943f615d384bd3c3'-or$unchanged.cursor_runbook_sha256-cne'3f6cf15435751999154ae35c7a241a6756c1846a6958119024f61ea1921c995b'-or$unchanged.startup_watchdog_sha256-cne'e7ae19424cb36814ef9da2bf819f11b26fbe4949d7de398bc1b85b8f7ca71a40'-or$unchanged.formal_m5_state_machine_sha256-cne'a6090dab98b7158f789c6b196b9267770991c8811d3ca7ec4bce9ff27e8e1b9f'-or$unchanged.launcher_sha256-cne'ff5fd757f817ffef92039ba00e795c15cfaf7a47cc15c0075aac896051f3f2d7'){throw 'Unchanged formal/import/runbook dependency mismatch.'}
function FileSha([string]$Role){$match=@($files|Where-Object{[string]$_['role']-ceq$Role});if($match.Count-ne1){throw "Tooling role is not unique: $Role"};return [string]$match[0]['sha256']}
$eligible=$selfGreen
$manifest=[ordered]@{
 schema='SpaceSyndicatePr90ListenerObserverToolingManifestV1';status=if($eligible){'READY_FOR_ONE_M0_M5_CHARACTERIZATION_ONLY'}else{'BLOCKED'};characterization_eligible=$eligible;formal_authorization_eligible=$false;post_repair_m0_m11_eligible=$false
 task_id='PR90_MCP_LISTENER_OBSERVER_KEY_FORMATTER_REPAIR_AND_ENDPOINT_OWNER_CHARACTERIZATION_V2';execution_mode='REPAIR_EXTERNAL_LISTENER_OBSERVER_SEAL_TOOLING_RUN_ONE_M0_M5_CHARACTERIZATION_ONLY';authorized_listener_observer_tooling_repair_count=1;authorized_characterization_probe_id='pr90-m5-endpoint-owner-characterization-v2-001';authorized_characterization_probe_count=1;created_at_utc=[DateTimeOffset]::UtcNow.ToString('o')
 product_head_sha='770d741f05964facda4afcbddcdeb3e7f40571d5';product_tree_sha='f5bb584ceea065b13c9b5621b1976af7907c62ad';old_tooling_head_sha=$oldHead;old_tooling_tree_sha=$oldTree;new_tooling_parent_sha=$parent;tooling_head_sha=$head;tooling_tree_sha=$tree;tooling_branch=$branch;tooling_worktree_clean=$true;tooling_index_clean=$true;preseal_revision_count=2;committed_revision_count=1
 frozen_attempt21_probe_id='pr90-attempt21-final-minimal-m0-m11-probe-001';frozen_characterization_probe_id='pr90-m5-endpoint-owner-characterization-001';frozen_characterization_disposition='LISTENER_OBSERVER_FIRST_NONEMPTY_TUPLE_FORMATTER_FAILURE';frozen_evidence=$pins;m5_root_cause_working_hypothesis='D_ENDPOINT_ARCHITECTURE_CONTRACT_DRIFT';m5_root_cause_formally_attested=$false
 allowed_changed_paths=$paths;actual_changed_paths=$actual;tooling_files=$files;product_code_change_count=0;product_test_change_count=0;addon_change_count=0;formal_m5_acceptance_change_count=0
 unchanged_tooling=$unchanged;endpoint_listener_record_schema_version='EndpointListenerRecordV1';endpoint_listener_record_filetime_type='LOSSLESS_DECIMAL_STRING';canonical_key_field_order=@('address_family','local_address_normalized','local_port','tcp_state','owning_pid','owner_creation_time_filetime_utc');address_equivalence_policy='EXACT_IP_LITERAL_NO_IPV4_IPV6_OR_MAPPED_MERGE';state_normalization_policy='LISTEN_AND_LISTENING_TO_LISTEN_REJECT_OTHER';observer_source_count=2
 selftest_path=$selfPath;selftest_sha256=Get-Pr90Sha256 $selfPath;selftest_sidecar_path="$selfPath.sha256";selftest_status=[string]$self.status;selftest_case_count=[int]$self.case_count;selftest_pass_count=[int]$self.pass_count;selftest_canonical_payload_sha256=[string]$self.canonical_payload_sha256;selftest_required_case_ids=$requiredCases
 listener_formatter_exception_count=[int]$self.listener_formatter_exception_count;first_nonempty_listener_fixture_green=[bool]$self.first_nonempty_listener_fixture_green;cross_source_false_parity_count=[int]$self.cross_source_false_parity_count;cross_source_false_mismatch_count=[int]$self.cross_source_false_mismatch_count;source_adapter_parse_failure_count=[int]$self.listener_source_adapter_parse_failure_count;canonical_key_culture_delta=[int]$self.listener_canonical_key_culture_delta;canonical_key_order_delta=[int]$self.listener_canonical_key_order_delta;raw_listener_direct_string_format_count_after=[int]$self.raw_listener_direct_string_format_count_after;raw_listener_used_as_dictionary_key_count_after=[int]$self.raw_listener_used_as_dictionary_key_count_after;raw_listener_property_guess_count_after=[int]$self.raw_listener_property_guess_count_after
 frozen_failure_input_type='NOT_PERSISTED_IN_FROZEN_EVIDENCE';reconstructed_old_formatter_row_type='System.Collections.Specialized.OrderedDictionary';listener_formatter_failure_class='POWERSHELL_FORMAT_OPERATOR_ARGUMENT_COLLAPSE_FROM_FUNCTION_CALL_ARRAY_LITERAL';real_getnettcp_raw_runtime_type=[string]$self.real_getnettcp_raw_inventory.dotnet_type;real_netstat_raw_runtime_type=[string]$self.real_netstat_raw_inventory.dotnet_type
 new_listener_record_normalizer_sha256=FileSha -Role 'record_normalizer';new_listener_key_formatter_sha256=FileSha -Role 'key_formatter';new_getnettcp_adapter_sha256=FileSha -Role 'getnettcp_adapter';new_netstat_adapter_sha256=FileSha -Role 'netstat_adapter';new_listener_parity_validator_sha256=FileSha -Role 'parity_validator';new_process_identity_reader_sha256=FileSha -Role 'process_identity_reader';new_characterization_controller_sha256=FileSha -Role 'characterization_controller';new_selftest_manifest_sha256=Get-Pr90Sha256 $selfPath
 first_jsonrpc_request_sent=$false;endpoint_application_request_count=0;m6_to_m11_execution_count=0;post_repair_m0_m11_probe_execution_count=0;formal_mcp_execution_count=0;authorized_run_count_consumed=0;probe_b_execution_count=0;viewport_execution_count=0;headless_matrix_execution_count=0;product_headless_2000_execution_count=0;exact_sha_mcp_status='NOT_STARTED';canonical_payload_sha256=''
}
$manifest.canonical_payload_sha256=Get-Pr90CanonicalSha256 $manifest;Write-Pr90ImmutableJson -Path $OutputPath -Value $manifest -WriteSha256Sidecar|Out-Null;$manifest|ConvertTo-Json -Depth 100 -Compress
