[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$ManifestPath,
 [Parameter(Mandatory=$true)][string]$ToolingWorktree,
 [Parameter(Mandatory=$true)][string]$OutputPath
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
Import-Module (Join-Path $PSScriptRoot 'pr90_probe_b_attempt22_contract_v1.psm1') -Force
if(-not(Test-Pr90ProbeBShaSidecar $ManifestPath "$ManifestPath.sha256")){throw 'Listener Parity V2 Tooling manifest sidecar mismatch.'}
$manifest=Get-Content -Raw -LiteralPath $ManifestPath|ConvertFrom-Json -Depth 100
$root=(Resolve-Path -LiteralPath $ToolingWorktree).Path;$head=(& git -C $root rev-parse HEAD).Trim();$tree=(& git -C $root rev-parse 'HEAD^{tree}').Trim();$parent=(& git -C $root rev-parse 'HEAD^').Trim()
$ready=([string]$manifest.schema-ceq'Pr90ListenerParityV2ToolingManifestV1'-and[string]$manifest.status-ceq'READY'-and[bool]$manifest.startup_probe_b_authorization_eligible-and[string]$manifest.tooling_head_sha-ceq$head-and[string]$manifest.tooling_tree_sha-ceq$tree-and[string]$manifest.tooling_parent_sha-ceq$parent-and
 [string]$parent-ceq'c9508c47f0aec647151dfb4ae58a720014ab3702'-and[int]$manifest.new_tooling_diff_count-eq19-and[int]$manifest.new_tooling_modified_count-eq15-and[int]$manifest.new_tooling_added_count-eq4-and[int]$manifest.tooling_scope_violation_count-eq0-and[int]$manifest.product_code_change_count-eq0-and[int]$manifest.product_test_change_count-eq0-and[int]$manifest.base_unchanged_file_hash_mismatch_count-eq0-and[int]$manifest.tooling_file_hash_mismatch_count-eq0-and
 [int]$manifest.base_selftest_pass_count-eq170-and[int]$manifest.new_listener_parity_selftest_count-ge41-and[int]$manifest.new_listener_parity_selftest_pass_count-eq[int]$manifest.new_listener_parity_selftest_count-and[int]$manifest.total_selftest_pass_count-ge211-and[int]$manifest.total_selftest_failure_count-eq0-and[int]$manifest.listener_core_parity_key_field_count-eq5-and[int]$manifest.observer_specific_field_in_key_count-eq0-and[int]$manifest.process_enrichment_field_in_key_count-eq0-and[bool]$manifest.bracketed_sample_model-and[string]$manifest.listener_parity_root_cause_class-ceq'J'-and[int]$manifest.characterization_probe_execution_count-eq0)
if(-not$ready){throw 'Listener Parity V2 Tooling manifest is not exact READY.'}
if(@(& git -C $root status --porcelain=v1 --untracked-files=all).Count-ne0){throw 'Tooling worktree mutated before Listener Parity V2 seal.'}
$mismatch=0
foreach($row in @($manifest.tooling_files)){$path=Join-Path $root ([string]$row.relative_path);$blob=if(Test-Path -LiteralPath $path -PathType Leaf){(& git -C $root rev-parse "HEAD:$([string]$row.relative_path)").Trim()}else{''};if(-not(Test-Path -LiteralPath $path -PathType Leaf)-or(Get-Pr90ProbeBSha256 $path)-cne[string]$row.sha256-or$blob-cne[string]$row.git_blob_sha){$mismatch+=1}}
if($mismatch-ne0){throw 'Listener Parity V2 Tooling file inventory changed before seal.'}
$seal=[pscustomobject][ordered]@{
 schema='Pr90ListenerParityV2ToolingSealV1';status='SEALED';created_at_utc=[DateTimeOffset]::UtcNow.ToString('o');product_head_sha=[string]$manifest.product_head_sha;product_tree_sha=[string]$manifest.product_tree_sha
 tooling_repository=[string]$manifest.tooling_repository;tooling_remote_branch=[string]$manifest.tooling_remote_branch;tooling_head_sha=$head;tooling_tree_sha=$tree;tooling_parent_sha=$parent;manifest_path=[IO.Path]::GetFullPath($ManifestPath);manifest_sha256=Get-Pr90ProbeBSha256 $ManifestPath;tooling_file_count=[int]$manifest.tooling_file_count;tooling_file_hash_inventory_sha256=[string]$manifest.tooling_file_hash_inventory_sha256
 base_tooling_manifest_sha256=[string]$manifest.base_tooling_manifest_sha256;base_tooling_seal_sha256=[string]$manifest.base_tooling_seal_sha256;frozen_probe_b_result_sha256=[string]$manifest.frozen_probe_b_result_sha256;listener_forensics_sha256=[string]$manifest.listener_forensics_sha256;listener_parity_root_cause_class=[string]$manifest.listener_parity_root_cause_class;characterization_probe_execution_count=0
 listener_parity_contract_version=2;protected_ports=@($manifest.protected_ports);startup_contract_sha256=[string]$manifest.startup_contract_sha256;getnettcp_source_adapter_sha256=[string]$manifest.getnettcp_source_adapter_sha256;netstat_source_adapter_sha256=[string]$manifest.netstat_source_adapter_sha256;listener_core_normalizer_sha256=[string]$manifest.listener_core_normalizer_sha256;listener_parity_comparator_sha256=[string]$manifest.listener_parity_comparator_sha256;bracketed_cohort_controller_sha256=[string]$manifest.bracketed_cohort_controller_sha256;process_identity_enricher_sha256=[string]$manifest.process_identity_enricher_sha256;endpoint_ownership_validator_sha256=[string]$manifest.endpoint_ownership_validator_sha256;failure_cleanup_sha256=[string]$manifest.failure_cleanup_sha256;probe_b_controller_sha256=[string]$manifest.probe_b_controller_sha256;probe_b_result_builder_sha256=[string]$manifest.probe_b_result_builder_sha256;probe_b_attestation_builder_sha256=[string]$manifest.probe_b_attestation_builder_sha256
 authorized_probe_scene_path=[string]$manifest.authorized_probe_scene_path;authorized_probe_scene_sha256=[string]$manifest.authorized_probe_scene_sha256;authorized_probe_b_v2_id=[string]$manifest.authorized_probe_b_v2_id;startup_probe_b_authorization_eligible=$true;new_selftest_sha256=[string]$manifest.new_selftest_sha256;total_selftest_pass_count=[int]$manifest.total_selftest_pass_count;total_selftest_failure_count=0;post_seal_mutation_count=0;formal_mcp_execution_count=0;authorized_run_count_consumed=0;canonical_payload_sha256=''
}
$seal.canonical_payload_sha256=Get-Pr90ProbeBCanonicalSha256 $seal
Write-Pr90ProbeBImmutableJson -Path $OutputPath -Value $seal -WriteSha256Sidecar|Out-Null
$seal|ConvertTo-Json -Depth 100 -Compress
